### ISSUE TITLE
Provide wxFileDialog implementation using IFileDialog to be able to select initial directory under Windows 7

### ISSUE THREAD

**Issue by wxtrac** [wxWidgets/wxWidgets#14770]
*Issue migrated from trac ticket # 14770*

**component:** wxMSW | **priority:** normal

#### 2012-10-22 12:35:11: jondo (Robert Pollak) created the issue

___
I have set both the defaultFile and the matching defaultDir to an existing path, but instead of opening this path, my wxFileDialog instance reuses the path that was selected in a former wxFileDialog instance. This wrong path even persists when the application is restarted.

According to [this MSDN page](http://msdn.microsoft.com/en-us/library/windows/desktop/ms646839%28v=vs.85%29.aspx), `lpstrInitialDir` in the `OPENFILENAME` structure is interpreted differently in Windows 7. Maybe that is connected to my problem here?

The page also suggests that the "Common Item Dialog API" should be used instead. Is this already used in newer wxWidgets versions?

**Comment by PBfordev** [comment]
Seeing the issue mentioned in the mailing list...

I tried to look into this and IMO the biggest challenge would be to keep compatibility, i.e., having two implementations: One for the old one and one for the new, limited one.

My idea was to introduce `wxFileDialogExtraControlsSimpl` class, which would have API with limited controls, mimicking `IFileDialogCustomize`. On Windows, the implementation would use `IFileDialogCustomize` implementation (`wxFileDialogExtraControlsSimpleImplIFD`) and on other platforms it would use normal wxWidgets controls (`wxFileDialogExtraControlsSimpleImplGeneric`). 

I wrote some test code but I abandoned the project before I thought out how to best plug it into `wxFileDialog`. Mostly because I would need to test the code on wxGTK and wxOSX which I could not do. Also, it was not that easy and perhaps the whole idea was wrong. IIRC, I also ran into the known limitation about retrieving a value from a text control which was probably the straw that broke my back here.

FWIW, I am attaching `wxFileDialogExtraControlsSimpl`  and some test code here anyway. Feel free to ignore.
[filedlg-ifd.zip](https://github.com/wxWidgets/wxWidgets/files/7873069/filedlg-ifd.zip)

**Comment by vadz** [comment]
Just in case anybody finds this interesting, I finally have something working. It's still not ready to be merged (e.g. all the docs still remain to be written), but I think the API is reasonable by now. Here is the code in the dialogs sample which does the same thing as the current version but using the new API:
```cpp
// This class does the same thing as MyExtraPanel above, but uses newer API for
// wxFileDialog customization.
class MyCustomizeHook : public wxFileDialogCustomizeHook
{
public:
    explicit MyCustomizeHook(wxFileDialog& dialog)
        : m_dialog(&dialog)
    {
    }

    // Override pure virtual base class method to add our custom controls.
    virtual void AddCustomControls(wxFileDialogCustomize& customizer) wxOVERRIDE
    {
        customizer.AddStaticText("Just some extra text:");
        m_text = customizer.AddTextCtrl();
        m_check = customizer.AddCheckBox("Enable Custom Button");
        m_button = customizer.AddButton("Custom Button");
        m_label = customizer.AddStaticText("Nothing selected");
    }

    // Override another method called whenever something changes in the dialog.
    virtual void UpdateCustomControls() wxOVERRIDE
    {
        // Enable the button if and only if the checkbox is checked.
        m_button->Enable(m_check->GetValue());

        // Also show the current dialog state->
        m_label->SetLabelText(GetFileDialogStateDescription(m_dialog));
    }

    // And another one called when the dialog is accepted.
    virtual void TransferDataFromCustomControls() wxOVERRIDE
    {
        m_info.Printf("checkbox=%d, text=\"%s\"",
                      m_check->GetValue(), m_text->GetValue());
    }


    // This is just a helper function allowing to show the values of the custom
    // controls.
    wxString GetInfo() const { return m_info; }

private:
    wxFileDialog* const m_dialog;

    wxFileDialogButton* m_button;
    wxFileDialogCheckBox* m_check;
    wxFileDialogTextCtrl* m_text;
    wxFileDialogStaticText* m_label;

    wxString m_info;

    wxDECLARE_NO_COPY_CLASS(MyCustomizeHook);
};

void MyFrame::FileOpen(wxCommandEvent& WXUNUSED(event) )
{
    ...
    // Note: this object must remain alive until ShowModal() returns.
    MyCustomizeHook myCustomizer(dialog);
    dialog.SetCustomizeHook(myCustomizer);
    ...
    if (dialog.ShowModal() == wxID_OK)
        ... can use myCustomizer.GetInfo() here ...

}
```

@imciner2 I've grepped KiCad sources for the existing uses of `SetExtraControlCreator()` and AFAICS you should have no trouble to migrate to the new API (there is also `AddRadioButton()`). The only thing that is missing compared to the old API is support for tooltips as this is just not something supported by [IFileDialogCustomize](https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/nn-shobjidl_core-ifiledialogcustomize).
