### ISSUE TITLE
ClientDC doesn't support wxINVERT Logical Function under wxGTK3

### ISSUE THREAD

**Issue by wxtrac** [wxWidgets/wxWidgets#16890]
*Issue migrated from trac ticket # 16890*

**component:** wxGTK | **priority:** normal | **keywords:** gtk3

#### 2015-03-03 03:00:33: @swt2c created the issue

___
Calling SetLogicalFunction(wxINVERT) on a ClientDC doesn't seem to work under GTK3.  Looking at the code, this seems to be because wxGTKCairoDCImpl inherits from wxGCDCImpl, which doesn't support INVERT.  Should wxGTKCairoDCImpl perhaps override SetLogicalFunction to call cairo_set_operator() on the cairo_t?

**Comment by GillesDuvert** [comment]
Hi, how about to ask Cairo to support INVERT? It looks strange they have not implemented all the 16 basic graphic functions

**Comment by vadz** [comment]
I've finally done what was discussed here, please check #22546. Any comments would be welcome, but I'd like to merge it (in the beginning of the) next week, so it's included in 3.2.0-rc1, if there are no huge problems with it.

**Comment by asmwarrior** [comment]
Hi, I would like to ask a question here, as this ticket's title: ClientDC doesn't support wxINVERT Logical Function under wxGTK3

My question is: Does this really fixed? We have try to improve the wxMathPlot control in https://github.com/GitHubLionel/wxMathPlot, especially we have a new "Magnet" feature, which shows cross lines around the mouse position.

What we want to do is we first draw some cross lines using the wxINVERT method, and if the mouse moves, the will use the wxINVERT method to draw on the old mouse position to remove the cross, and draw new cross. Is this works under Linux?

Thanks.

**Comment by GillesDuvert** [comment]
Hi, thanks for asking, for GDL the free IDL clone, we have to support code written in the old days where graphic functions were logical function on bytes, and wxINVERT was widely used for crosshairs, "marching ants" delimiters etc.

I forgot to report here ( on wxWidgets ) that I [further contacted the CAIRO people](https://gitlab.freedesktop.org/cairo/cairo/-/issues/575) about the absence of all 'old-fashioned' logical functions in CAIRO, and (rightly I think) they replied that CAIRO is uses compositing functions on an abstract representation of the "image" (my words are probably quite inexact) and not bit-logical function on bytes, as INVERT does. 

So we cannot rely on CAIRO to do the job.

In fact, other wxwidgets wxRasterMode are [not OK](https://forums.wxwidgets.org/viewtopic.php?f=23&t=48646) by just passing the baby to some seemingly compatible CAIRO function.

We, as wxWidgets users, could either use a wxWidgets with GTK but without CAIRO ( is that even possible nowadays?) or kindly ask wxWidgets to provide a workaround for this special wxRasterMode only.  The point is that wxINVERT is not [supposed to work with white background only](https://github.com/wxWidgets/wxWidgets/issues/16890#issuecomment-1011100648), but with any possible background image of any combination of RGB bytes (or words). Basically, it would probably mean for wxWidgets to work directly on the underlying X11 bitmap of GTK? Or using a buffer bitmap on which such byte operations can be directly made, bypassing CAIRO? On OSX, wxINVERT workd nice, because CAIRO is not there.

**Comment by asmwarrior** [comment]
> The point is that wxINVERT is not https://github.com/wxWidgets/wxWidgets/issues/16890#issuecomment-1011100648, but with any possible background image of any combination of RGB bytes (or words). Basically, it would probably mean for wxWidgets to work directly on the underlying X11 bitmap of GTK? Or using a buffer bitmap on which such byte operations can be directly made, bypassing CAIRO?

I don't know, hopefully some wx dev or Linux wx user can answer this.

**Comment by vadz** [comment]
For an application to work under Wayland (using GTK 3) or macOS, you can't use `wxClientDC` for drawing **at all**. So even if `wxINVERT` "works", it doesn't really help you there, you need to change your drawing logic to refresh (parts of) the window (that must change) and then repaint it entirely in your `wxEVT_PAINT` handler.

And no, there is no way around it with the architecture used by these systems.

**Comment by asmwarrior** [comment]
> For an application to work under Wayland (using GTK 3) or macOS, you can't use `wxClientDC` for drawing **at all**. So even if `wxINVERT` "works", it doesn't really help you there, you need to change your drawing logic to refresh (parts of) the window (that must change) and then repaint it entirely in your `wxEVT_PAINT` handler.
> 
> And no, there is no way around it with the architecture used by these systems.
Hi, VZ, thanks for the reply and explanation. 

As you said under Wayland(GTK 3), only drawing under `OnPaint` works. What about others, such as the traditional/old X11?

**Comment by asmwarrior** [comment]
> With X11 you can still use `wxClientDC` and so `wxINVERT` could work (on white background only?), but, honestly, who is interested in supporting only X11 nowadays? You need to write code supporting Wayland, and to do this you have to change it to use `wxPaintDC` anyhow and then `wxINVERT` is irrelevant.

OK, I see, thanks!
