### ISSUE TITLE
AddCatalog doesn't fail with wxLANGUAGE_DEFAULT

### ISSUE THREAD

**Issue by wxtrac** [wxWidgets/wxWidgets#18227]
*Issue migrated from trac ticket # 18227*

**component:** wxMSW | **priority:** normal | **keywords:** addcatalog translations locale

#### 2018-09-22 17:47:19: @lanurmi created the issue

___
When `wxLocale` is inited with `wxLANGUAGE_DEFAULT`, and the default language is non-English, `wxTranslations::AddCatalog` returns `true` even if the requested catalog in the *preferred language* was not found. This is specific to Windows, possibly also Mac, but *nix is not affected.

What happens is that on non-English Windows (for example, Windows 7 in Finnish), [GetPreferredUILanguage](https://github.com/wxWidgets/wxWidgets/blob/cc931612eec2e3ea49200ebff45042135f3c3f9c/src/common/translation.cpp#L130) returns *two* languages: `fi_FI` and `en_US`. Now, if the catalog for Finnish was not found, the original msgid language English is still considered to satisfy what the caller asked for, so no error is returned. This is however not what the caller expected, and on *nix an error would be returned.

I also tested this on a Windows 10 installed in German, and again two preferred languages are returned. On neither machine has the user (me) done anything to choose English as a secondary language.

In wx 2.8 `AddCatalog` used to fail when a catalog in the default language was not found. On *nix it still does.

Steps to reproduce in the unmodified *internat* sample:
0. Have something else than English as the preferred language.
1. Remove all **.mo* files, so no catalog exists.
2. Select *System default* as the language in *internat*.
3. Observe there is no error message about failing to load the catalog.

**Comment by vadz** [comment]
After returning to this, I realize that I actually have a problem with adding `msgIdLanguage` to the "available translations" which was done back in 01f953efb2 (Add wxTranslations::GetBestTranslation()., 2012-09-08). This seems wrong because this translation is not actually available -- it is fine not to use it at all, but this is not quite the same thing.

Unfortunately to solve this we'd need to change `AddCatalog()` to return a 3-state enum with possible values of "Loaded", "Not loaded" and "Not needed" which is going to be difficult to implement in a backwards compatible way. So I guess the only thing we can do is to add yet _another_ function behaving like this.

For the record, I've toyed with the idea of returning false from `AddCatalog(domain)` overload in the case when there is no translation but the language is still considered to be acceptable, while continuing to return true from `AddCatalog(domain, msgIdLanguage)` overload, but decided this would be too confusing, finally.

So I've created #23918 which is supposed to address this. Please let me know what do you think!

**Comment by vslavik** [comment]
> After returning to this, I realize that I actually have a problem with adding msgIdLanguage to the "available translations" which was done back in https://github.com/wxWidgets/wxWidgets/commit/01f953efb211daf5275cbb10aa3dd000eeed6d48 (Add wxTranslations::GetBestTranslation()., 2012-09-08). This seems wrong because this translation is not actually available -- it is fine not to use it at all, but this is not quite the same thing.

Would it feel OK to you if the function was called GetBestUILanguage() instead? That is, I think, the rationale behind that behavior: it is meant to return the *language* available for use, which is usually "translation", but not in the msgid/English case.  But omitting msgIdLanguage from the list would require special-casing that one language everywhere.

**Comment by vadz** [comment]
I agree that calling it `GetBestUILanguage()` would have been much better/more clear but I'm not sure that adding yet another synonym now, while still keeping the current name for compatibility, is worth it.

But mostly, renaming it is still not going to solve the problem of `en-US` being -- apparently -- always present in the preferred UI languages list and so `AddCatalog()` always succeed, so the other changes would still be needed, AFAICS.

**Comment by vadz** [comment]
Is this issue still a problem, after all the changes done to this code? I don't have any non-English Windows system and I'm not sure if changing the language of the installed system is/was enough to reproduce the bug, so could someone using Windows in another language please check if this is still broken? TIA!

**Comment by lanurmi** [comment]
Sadly it still seems to work the same way as before. Now testing on Windows 10, Finnish. `GetPreferredUILanguage()` still returns two languages, the second one being `en_US`.

If I either insert `preferred.resize(1);` [right after the call to `wxUILocale::GetPreferredUILanguages()`](https://github.com/wxWidgets/wxWidgets/blob/master/src/common/translation.cpp#L122), or [comment out these two lines](https://github.com/wxWidgets/wxWidgets/blob/master/src/common/translation.cpp#L1468-L1469), then `AddCatalog()` will fail. But otherwise not, because the msgid language English always matches the English on the list of preferred languages.

**Comment by utelle** [comment]
> Sadly it still seems to work the same way as before. Now testing on Windows 10, Finnish. `GetPreferredUILanguage()` still returns two languages, the second one being `en_US`.

The reason is that the Windows API function `GetUserPreferredUILanguages()` (which is called from `wxUILocale::GetPreferredUILanguages()`) seems to return always the UI language selected in the Windows settings **and** `en-US` as the second language. I observe this phenomenon also on my German Windows 11 system. English is nowhere explicitly set in my Windows settings.

To overcome this problem PR https://github.com/wxWidgets/wxWidgets/pull/24855 queries the installed preferred UI languages from the Windows registry. Additionally, the algorithm to select the best translation catalog has been reworked in that PR as well.

Hopefully the PR solves this issue, too. However, the PR has not been merged yet.
