### ISSUE TITLE
wxDataViewModel::ItemChanged() doesn't redraw view on GTK or MSW

### ISSUE THREAD

**Issue by wxtrac** [wxWidgets/wxWidgets#18712]
*Issue migrated from trac ticket # 18712*

**component:** GUI-all | **priority:** normal

#### 2020-03-30 22:58:39: JeffYoung created the issue

___
It works on OSX (ie: the wxDataViewCtrl calls the model's GetValue() and GetAttrs() methods to refresh the display of the item).

It does not work on GTK: all it does is spit out an event that the client program can catch.  But it doesn't inform the view to call GetValue()/GetAttrs() or refresh the display.

Same on MSW.

Tested on 3.0.4 and 3.1.3.  (MSW further asserts on 3.1.3.)

**Comment by vadz** [comment]
Sorry, just stumbled upon this old issue and I'd like to finally close it because I do think this works as expected: choosing "Change ninth title" in the dataview sample results in `ItemChanged()` being called which updates the display.

FWIW `wxgtk_tree_model_get_value ()` doesn't get called here and, AFAICS, the calls to it are suppressed by our use of `gtk_tree_view_column_set_cell_data_func()`, so it's `wxGtkTreeCellDataFunc()` which ends up being called instead. But the net effect is the same, as `wxDataViewModel::GetValue()` is called to retrieve the updated value.

So AFAICS this works as expected and, as previously mentioned, we really need to be able to reproduce this in the dataview sample to do anything about it. I think this issue was originally opened by @jey5nd6, so please let me know if you can still reproduce it. TIA!

**Comment by jey5nd6** [comment]
I don't have a GTK machine, so I've never been able to test this (either in KiCad or in the dataview sample).

However, I looked up our work-around in KiCad (we have a massive hack that increases and then decrease the column widths of the dataView).  It turns out that we *also* use this work-around to avoid On^2 sorting behaviour in the OSX implementation of `ItemChanged()`, so we'd need it irrespective of the state of this bug.

I think Seth runs GTK; I can see if he can reproduce it with our hack removed....
