### ISSUE TITLE
wxBitmapButton problems with scaled wxBitmaps on macOS

### ISSUE THREAD

**Issue by dkulp** [wxWidgets/wxWidgets#22019]
As mentioned on the group, there seems to be an issue with wxBitmapButtons with scaled bitmaps with the latest code in master.  I can easily reproduce the problem with the aui demo using the changes attached.

With 3.1.5, the bitmap is displayed properly in full resolution on retina displays in the proper 16x16 bitmap button.  
  
[diff.txt](https://github.com/wxWidgets/wxWidgets/files/7873795/diff.txt)
[butterfly_32.xpm.txt](https://github.com/wxWidgets/wxWidgets/files/7873794/butterfly_32.xpm.txt)
<img width="308" alt="bb-3 1 5" src="https://user-images.githubusercontent.com/91569/149598433-26830c22-8e0a-454a-95f3-b4ba0fea0e04.png">
<img width="445" alt="bb-master" src="https://user-images.githubusercontent.com/91569/149598566-0453632f-5613-4350-8c19-1bd6d7b708cd.png">

**Comment by vadz** [comment]
I do see the problem under macOS 12 in high DPI. It seems to be specific to `wxButton`, as if I replace the button with a `wxStaticBitmap` the image looks correctly.

The weird thing is that the button is too big, but not by a factor of 2, it's 56x54 pixels here somehow. Looking...

**Comment by vadz** [comment]
@csomor I'm pushing the fix for this without review because I'm pretty sure it is correct, for once. Also, look at the results of using/not using size and this style before my fix:
![image](https://user-images.githubusercontent.com/146917/149603980-2d187493-e0ed-4981-98ec-cd5009606074.png)

And after it:
![image](https://user-images.githubusercontent.com/146917/149604075-414020d8-1ae2-4e6e-97df-62a1a08c55f8.png)

To @dkulp: I'm surprised that you don't use `wxBORDER_NONE` for your bitmap buttons, IMO they look really ugly without it and I don't think this has changed since 3.1.5. But if it did, please let us know.

And thanks again for reporting this!
