### ISSUE TITLE
wxGetFreeMemory() can't be called from non-main thread under Linux (was: wxExecute generates zombies and wxEVT_END_PROCESS event doesn't rise)

### ISSUE THREAD

**Issue by rossanoparis** [wxWidgets/wxWidgets#22092]
**Description**
I'm facing an issue in an application of mine using wxExecute and wxProcess.

The problem is related to wxExecute, called in a cycle of 1min, which creates zombie processes and does not permit wxEVT_END_PROCESS execution at the end of such processes.
After the first "zombie", more less after a dozen of cycles, every other calls to wxExecute fails in the same way, even tough the executed process is different; it doesn't matter the kind of process is launched, neither executables, scripts nor system commands.

I'm sure, wxExecute is called in the main thread, as I use wxTread::IsMain() to check it.
The starting function I use to execute wxExecute is called from an event which is launched from another thread by using  wxEvtHandler::QueueEvent()

remark
This behavior happens only using LINUX as OS, using MSW everything works well ... that's why I'm getting crazy :)

I bag your pardon for this general description, I've already tryied to prepare a smal applicatrion trying to reproduce it, yet honestly, in this small application the issue reported doesn't appear, thus the problem, I suppose, should be find in my application which execute many threads for other contexts.

**My request**
Someone of you, who knows deeply wxWidgets, would be so kind to start a discussion with me in order to help me understanding what is going on ? For example, could some causes be listed ?

**Platform and version information**
wxWidgets 3.1.5 (built as static library)
OS: LINUX Kernel 5.4.0-89-generic 64bit
GTK: 3.24.20

Best regards
Rossano Paris

**Comment by vadz** [comment]
Sorry, it's going to be really hard to understand what's going on here without being able to reproduce it. All I can say is that if a process ends up in a zombie state, it means that its parent process has somehow ended without waiting for it. But if the parent process is really your main GUI application, I don't see how it can happen.

FWIW it's not surprising at all that the code works differently under MSW and Unix, the underlying APIs are completely different between the two platforms.

**Comment by hobbitdev** [comment]
Thank you for the prompt reply

For sure you are right the two APIs for LINUX and MSW are different.
Excuse but, I don't want to sound rude, I'm using wxWidgets for this reason because it offers the same interface among different OSs.
Classes and their member functions I'm using, are the same, I didn't find any particular specification reading the documentation.
Apart the racomandation to call wxExecute from the main thread.

For sure what I'm facing, depends on my implementation and because of my ignorance, I'm not ruling out it at all.
As a normal user what should I do if with the same source code on MSW it works fine and on LINUX it doesn't.

I don't claim someone else will solve my problem, yet I'm tring to understand what I'm doing wrong asking for some suggestions and considerations.
Unfortunately I'm not able to reproduce the same behaviour in a small application, I'm sorry for that I feel at fault, I can only try to describe the behaviour itself.

In my case, the main application is healthy, I mean the GUI is responsive to other events as usual, what I noticed, setting a break point before calling wxExecute(...) is, the function doesn't exit and from that moment all other calls to wxExecute() generate zombies.
This beaviuor remains same, even changing wxExecute parameters from ASYNC to SYNC, using a wxProcess or not, getting outputs and errors or not.
I even tryied to use wxShell instead of wxExecute, without any result.

I'm going ahead in my investigation, I hope to will be able to report a sort of cause and it solution ...

**Comment by hobbitdev** [comment]
Hi @vadz 

I was lucky and after a deep investigation I discovered the cause of the issue.
It is due to this function "wxGetFreeMemory()" called in another thread.
Here attached you can find a small repro, I'm sorry I can provide only a CODELITE workspace.
It contains few files, the DEBUGGING section is present in this file "MainFrame.cpp".

As you run the executable you can observe, after lets say 100 or 200 cycles they are not always the same number, the counter "m_Counter" will remain at the same value because the function wxExecute() doesn't exit anymore.
If you comment the line 148 in "MainFrame.cpp", everything works fine.

I hope it could be helpful.

Regards
Rossano

[wxTest.tar.gz](https://github.com/wxWidgets/wxWidgets/files/8008407/wxTest.tar.gz)

**Comment by vadz** [comment]
I guess this is due to calling `wxGetCommandOutput("uname -r")` from `wxGetFreeMemory()`. The simplest "fix" would be to just drop support for Linux < 2.6 which shouldn't be used anywhere any longer, but it also seems wrong that we don't seem to cache the version info and keep querying it again and again.

**Comment by hobbitdev** [comment]
Thank you @vadz 

I modified my application in order to call the `wxGetFreeMemory()` from the main thread.
This correct way to use it is not mentioned in its documentation.

Regards 
Rossano
