### ISSUE TITLE
MSW: Toolbar bitmap size not adjusted correctly if moved to a lower DPI screen.

### ISSUE THREAD

**Issue by TcT2k** [wxWidgets/wxWidgets#22105]
**Describe the bug**
Toolbar bitmap size not adjusted correctly if a window is moved to a lower DPI screen.
The same issue probably occurs if a screen is changed to a lower DPI while the window is open.

**To Reproduce**
1. Start webview sample _(on 125% screen)_
2. Move the window to higher DPI screen _(200% screen)_
3. Move the window back to original screen _(125% screen)_
4. Bitmaps are to large for the screen

_Obviously the exact scaling is irrelevant just to illustrate_

**Expected vs observed behaviour**
I think the check in [tbarbase.cpp:484](https://github.com/wxWidgets/wxWidgets/blob/f0c6b42ad032c2d8651f8cceeb9407bb7ce82b1d/src/common/tbarbase.cpp#L484):
```cpp
        if ( sizePreferred.x > sizeOrig.x || sizePreferred.y > sizeOrig.y )
```
Should probably be changed to `!=`. I've made the changed and it fixed the problem but I assume there could be side effects?

**Platform and version information**
 - wxWidgets version you use: 3.1.6 ( 1eabbf5ec7a52bdf096c8116be04bd5457ce93b0 )
 - wxWidgets port you use: wxMSW
 - OS and its version: Windows 10.0

**Comment by vadz** [comment]
Oops, sorry, I rebroke this in 27d5306bdd (Make wxToolBar::SetToolBitmapSize() work again, 2022-01-06). Unfortunately, as the commit subject says, just restoring the `!=` would break the tools appearance because we had historically interpreted the bitmap size as the minimum, and not the actual size (probably related to the fact that it's just 16x15 under MSW and nobody wants their bitmaps to be that tiny since 30 years).

I guess we're going to have to distinguish between the bitmap size set by default and bitmap size set because of the DPI change somehow.
