### ISSUE TITLE
SetBitmap no longer works in wxEVT_TOGGLEBUTTON event

### ISSUE THREAD

**Issue by taler21** [wxWidgets/wxWidgets#22109]
This change in behavior was introduced with commit [ee93f4cae82cc56b22b3d15026eaea64281665b2](https://github.com/wxWidgets/wxWidgets/commit/ee93f4cae82cc56b22b3d15026eaea64281665b2).

Please use the attached patch for the widgets sample to reproduce this issue: [widgets-sample_patch.zip](https://github.com/wxWidgets/wxWidgets/files/8024306/widgets-sample.zip)
(I'm sorry, I had to put the patch file in a ZIP archive because I didn't manage to attach the patch file directly.)

**To Reproduce**
1. Go to 'ToggleButton' page
2. Click on the 'ToggleButton'

If using wxWidgets-3.1.5 the bitmap of the 'ToggleButton' will be changed, but not if using the lastest master.

**Platform and version information**
 - wxWidgets version you use: **latest master**
 - wxWidgets port you use: **wxMSW**
 - OS and its version: Windows 7

**Comment by MaartenBent** [comment]
It happens because `SetBitmap` only sets the bitmap for the `normal` state, not the `pressed`, `hot` or `disabled` state. (Except when no bitmap is set, then all bitmaps are initialized with this bitmap).

This has indeed changed in the mentioned commit. Previously it only initialized the `normal` and `disabled` state, now it initializes all states. Like `wxXPButtonImageData` already did.

I'm reading the documentation and this behavior is indeed wrong: `This method sets up a single bitmap which is used in all button states`. A possible fix would be to reset the bitmap data first.

```diff
```
