### ISSUE TITLE
No HiDPI in some windows inside wxAUI on OSX

### ISSUE THREAD

**Issue by valid-ptr** [wxWidgets/wxWidgets#22126]
Simply run **auidemo** sample:
<img width="903" alt="Screenshot 2022-02-12 at 12 50 36" src="https://user-images.githubusercontent.com/25028460/153706603-a218cef7-b92f-4359-b630-1f97d73bc892.png">
Some texts and icons are blurred.

 - wxWidgets version you use: 3.1.6 (current master)
 - wxWidgets port you use: wxOSX
 - OS and its version:  macOS 10.14.6

**Comment by vadz** [comment]
It's normal that some icons are jagged, as we don't provide them in x2 sizes, but it's not normal at all that the tab labels are blurry. I think this is due to creating the off screen bitmap with x1 scale factor in `wxAuiTabContainer::Render()` instead of using the scale factor of `raw_dc`.

But then we probably shouldn't use a `wxMemoryDC` here at all under Mac, as under any platform where `wxALWAYS_NATIVE_DOUBLE_BUFFER==1`. IOW just this:
```diff
diff --git a/src/aui/auibook.cpp b/src/aui/auibook.cpp
index 1f9cdef222..2a178b21fa 100644
--- a/src/aui/auibook.cpp
+++ b/src/aui/auibook.cpp
@@ -21,6 +21,7 @@
 
 #ifndef WX_PRECOMP
     #include "wx/settings.h"
+    #include "wx/dcbuffer.h" // just for wxALWAYS_NATIVE_DOUBLE_BUFFER
     #include "wx/dcclient.h"
     #include "wx/dcmemory.h"
     #include "wx/frame.h"
@@ -414,6 +415,9 @@ void wxAuiTabContainer::Render(wxDC* raw_dc, wxWindow* wnd)
     if (m_rect.IsEmpty())
         return;
 
+#if wxALWAYS_NATIVE_DOUBLE_BUFFER
+    wxDC& dc = *raw_dc;
+#else
     wxMemoryDC dc;
 
     // use the same layout direction as the window DC uses to ensure that the
@@ -431,6 +435,7 @@ void wxAuiTabContainer::Render(wxDC* raw_dc, wxWindow* wnd)
 
     if (!dc.IsOk())
         return;
+#endif
 
     // ensure we show as many tabs as possible
     while (m_tabOffset > 0 && IsTabVisible(page_count-1, m_tabOffset-1, &dc, wnd))
```
might be enough to fix it.

**Comment by vadz** [comment]
I've tested this and while the patch above (or a slightly modified version of it which actually compiles...) does fix the text being blurry in wxGTK, it also breaks the tabs layout.

Also, looking at the code, it seems like the scale factor should be already correct under Mac as `wxBitmap::Create(wxDC)` does inherit the scale factor of the source DC there. This is not done in wxGTK however, but should be, so I'm definitely changing this.

**Comment by vadz** [comment]
This is getting weirder and weirder because I've now tested under Mac too and I don't see the problem there. I'm still going to commit the fix for wxGTK and a (variant) of the patch above as it should optimize things a bit, but this doesn't change anything under Mac for me, the text there already looks good for me:

![aui_mac_2x](https://user-images.githubusercontent.com/146917/153733596-ed6d3f3a-b982-4ca7-b9ee-7afd4ad00dd4.png)

I'm testing under macOS 12.0.1, could it be that this problem somehow only happens under 10.14? Or could you be using not quite the latest master? My initial test was with cd7b6f55075ed1aff39ebc38528e6bcc6d4247e9, could you please retest with it or d00aeb5813b87c45b4a75b76ab4414139e1113ab which includes my fixes? TIA!

**Comment by vadz** [comment]
Thanks for testing!

I'm closing this one, the icons/bitmaps "just" need to be provided in 2x (or SVG) versions.
