### ISSUE TITLE
MSW: wxButton doesn't always resize to allow padding around label

### ISSUE THREAD

**Issue by willco007** [wxWidgets/wxWidgets#22125]
**Describe the bug**
When creating a button with a label that causes the button to resize larger than the default size, the button doesn't resize to allow additional padding around the label. 

**Expected vs observed behaviour**
Expected:
The button to resize with additional padding around the label. 
Observed:
The button only resizes to fit the label (see screenshot).

**Patch or snippet allowing to reproduce the problem**

Create a standard button and insert it into the UI.  PLEASE NOTE: I am on a hidpi display which may be causing this issue, I don't have a standard DPI display to test with.

wxButton *button= new wxButton(this, wxID_ANY, "A very long title for a button");

![Button Label](https://user-images.githubusercontent.com/4294739/153655214-3c96736f-4291-4390-8fe3-2070f71849f7.png)

**Platform and version information**
 - wxWidgets version you use: 3.1.5
 - wxWidgets port you use: wxMSW
 - OS and its version: Windows 11 22000.493

**Comment by vadz** [comment]
This is not high-DPI-specific, the same happens at 100% scaling. And the reason for the problem is that `BCM_GETIDEALSIZE` doesn't add margins, i.e. it's really useless and I think the best would be to simply revert de10f054c4 (Improve calculating wxButton best size under wxMSW, 2021-04-08) which introduced it as we have to second-guess it anyhow.

@a-wi In which situation exactly does using it result in better results than our own code? I've tested with `wxBU_EXACTFIT` and I don't see any difference at all.

**Comment by vadz** [comment]
Yes, we could add margins to the size returned by `BCM_GETIDEALSIZE`, but it would be just as arbitrary as what we do now (see `wxMSWButton::GetFittingSize()`), so what's the point of using the standard message in the first place? I just don't see what do we gain from it.

**Comment by a-wi** [comment]
With e.g widgets sample you can see that wxButton (with 'fit exactly' style set) fits better to the label with the implementation based on BCM_GETIDEALSIZE.
Current implementation (BCM_GETIDEALSIZE):
![button_idealsize](https://user-images.githubusercontent.com/7330332/153750824-552ab1f9-4f95-4c3e-bf7d-69a27824abdc.png)
Previous implementation (https://github.com/wxWidgets/wxWidgets/commit/de10f054c4b0557ee1d97f2420f884959e189d6a reverted):
![button_no_idealsize](https://user-images.githubusercontent.com/7330332/153750845-0f8bdce2-5b44-43b6-8a00-ea1befb8830c.png)

**Comment by vadz** [comment]
This is certainly due to the code here https://github.com/wxWidgets/wxWidgets/blob/a2076a3dd77ed950231dcbad12d571537f0e0680/src/msw/anybutton.cpp#L519-L524 and IMO if we really prefer the tighter version (personally I don't, it seems to be too cramped, but it's just a subjective preference, of course), so I think it would still be simpler to stop using `BCM_GETIDEALSIZE` and reduce the margins here.

I just don't see what does this message give us if it doesn't take the margins into account -- it's not like we couldn't calculate the string extent ourselves.

**Comment by vadz** [comment]
Please check #22149 and let me know if you see any problems with it. TIA!
