### ISSUE TITLE
wxWebResponse::GetHeader returns broken string on Win32

### ISSUE THREAD

**Issue by tveerman** [wxWidgets/wxWidgets#22181]
In the wxMSW port wxWebResponse::GetHeader invokes wxWinHTTPQueryHeaderString which uses WinHttpQueryHeaders to return the contents of a header (https://github.com/wxWidgets/wxWidgets/blob/master/src/msw/webrequest_winhttp.cpp#L151). Upon first invocation of WinHttpQueryHeaders it returns in its lpdwBufferLength parameter the size in bytes a buffer is required to have to store the header value. A wxWCharBuffer object is created with this size and WinHttpQueryHeaders is invoked again to store the data into the buffer. The wxWCharBuffer is then assigned to a wxString.

It appears that wxWCharBuffer should be created with a size of lpdwBufferLength / 2.

For example, when I do a GetHeader on a header with the contents "Accept-Ranges: bytes" the resulting wxString contains "bytes\0garbag" and has a length of 12. If I then do a compare on the wxString with == "bytes" the comparison returns false. In wxOSX this works as expected.

**Comment by vadz** [comment]
Thanks, there is indeed a bug here, we need to remove `bufferLen` to `bufferSize` because it's in bytes and not characters and divide it by 2. Ideal would also be to have a unit test for this function, i.e. call `GetHeader()` somewhere in `tests/net/webrequest.cpp`.

PRs doing this would be welcome, otherwise I'll try to do it myself after 3.1.6 release.
