### ISSUE TITLE
mouse capture release in grid: checks required

### ISSUE THREAD

**Issue by DietmarSchwertberger** [wxWidgets/wxWidgets#22257]
Mouse capture release in grid does not do any checks and so I get assertions/exceptions.

wxPython issues 1841 / 1851 are a result of this:
https://github.com/wxWidgets/Phoenix/issues/1841
https://github.com/wxWidgets/Phoenix/issues/1851
This is related to wxPython's lib.gridmovers which is a Python implementation for dragging rows/columns and which does handle some mouse events and this probably results in a loss of mouse capture before `wxGrid::EndDraggingIfNecessary` is called

I did not see this issue with older wxPython versions. I would guess that the problem started with this commit:
https://github.com/wxWidgets/wxWidgets/commit/408ebfd253144ef3535932314a42fe34256d4a56
(If I add a `captureMouse = false` for the `WXGRID_CURSOR_SELECT_...` cases, then the problem is gone.)

As workaround, I have just added a check in `grid.cpp` whether `GetCapture` and `m_winCapture` are identical.
I'm not sure whether this should be handled in a more sophisticated way, though.

```
void wxGrid::EndDraggingIfNecessary()
{
    if ( m_winCapture )
    {
        wxWindow* const winCapture = GetCapture();
        if (winCapture==m_winCapture)
            m_winCapture->ReleaseMouse();

        DoAfterDraggingEnd();
    }
}
```

**Platform and version information**
 - wxWidgets version you use: current wxPython (4.1.2a)
 - wxWidgets port you use: wxMSW
 - OS and its version: Windows 10

**Comment by vadz** [comment]
It's a really bad idea to interfere with any control mouse handling from the outside. This is not (and can not) be supported at all for the native controls like `wxButton` and it would be very difficult to support it even for the generic ones like `wxGrid`. Basically I don't think it's reasonable to expect the things to work if the code outside of the control can capture (or release) mouse at any arbitrary moment. Adding a check like the one above is almost certainly insufficient to fix it, we'd have to add many more such checks and even if the problem could be fixed in this way, it would make the grid code even more complicated to reason about and it's already bad enough, so I'm rather strongly against doing it.

The proper solution would be to integrate Python-specific functionality into `wxGrid` itself.

**Comment by DietmarSchwertberger** [comment]
It's not about capturing the mouse by outside code, it's mainly that the capturing can get lost and wx is then still releasing it without check.

**Comment by vadz** [comment]
If capture gets lost, `wxGrid` should receive the mouse capture lost event and react to it accordingly. If it doesn't do this, this is definitely a bug, but I'd like to know how to reproduce it to be able to understand what exactly is going wrong before fixing it.

If, however, the capture loss is due to another `CaptureMouse()` call, it's a different matter.

**Comment by DietmarSchwertberger** [comment]
I had a closer look at the code of `gridmovers`. An older version was unconditionally calling `CaptureMouse` and `ReleaseMouse`.
The commit https://github.com/wxWidgets/Phoenix/commit/1a8d0fa9bb9552b5e7afe1b727cbca54b638f025 did not fix things as the check is probably wrong (should be `is None`, not `is not None`).
And, the check before `ReleaseMouse` does check whether the window has the capture, but this is probably due to grid.cpp having captured. Also, `evt.Skip()` is probably wrong at this place as the event is actually handled to start dragging.

I would like to get rid of gridmovers.py (from 2002) anyway. In the last days I did some work on implementing `EnableDragRowMove / EVT_GRID_ROW_MOVE`. I will submit a PR in the next days. Unfortunately, this can take some time until it propagates into wxPython.

I'm not sure whether wxGrid would handle a lost mouse capture.
The event table in grid.cpp is only for the main window, but the capture is for the label windows.
```
wxBEGIN_EVENT_TABLE(wxGridSubwindow, wxWindow)
    EVT_MOUSE_CAPTURE_LOST(wxGridSubwindow::OnMouseCaptureLost)
wxEND_EVENT_TABLE()
```

Thanks a lot.

**Comment by vadz** [comment]
> I would like to get rid of gridmovers.py (from 2002) anyway. In the last days I did some work on implementing `EnableDragRowMove / EVT_GRID_ROW_MOVE`. I will submit a PR in the next days. 

That would be great, thanks!

> I'm not sure whether wxGrid would handle a lost mouse capture. The event table in grid.cpp is only for the main window, but the capture is for the label windows.
> 
> ```
> wxBEGIN_EVENT_TABLE(wxGridSubwindow, wxWindow)
>     EVT_MOUSE_CAPTURE_LOST(wxGridSubwindow::OnMouseCaptureLost)
> wxEND_EVENT_TABLE()
> ```

There could be bugs in `wxGrid`, of course, but this event handler is defined for the subwindows and the label windows are subwindows, so I don't see anything wrong with this per se.
