### ISSUE TITLE
wxScrolled<> ScrollRate 

### ISSUE THREAD

**Issue by bloodfantasy** [wxWidgets/wxWidgets#22277]
I wrote a scroll bar, everything works fine, but when I set SetUserScale(2.0, 2.0), I set SetScrollRate(24, 24), the scrolling distance should be 24 each time, but the actual scrolling distance is 48, SetUserScale (2.0,2.0) seems to enlarge the ScrollRate (24*2), how can I keep the scrolling distance still 24 each time

**Comment by vadz** [comment]
You seem to start from a wrong premise that `SetUserScale()` (somehow) affects `SetScrollRate()`. It does not and I don't know why do you think it should.

Moreover, you seem to have a question, rather than reporting a bug, so please some more appropriate place for questions (mailing list, forum, etc) rather than the issue tracker.
