### ISSUE TITLE
Latest 3.1.6 does not build on mac anymore

### ISSUE THREAD

**Issue by guzmanpaco** [wxWidgets/wxWidgets#22272]
**Describe the problem**
Compile errors are encountered when building on Mac using latest commit, 4da102f2b177bec948e8e060d5c792e54a73f505.
```
../src/osx/core/uilocale.mm:231:39: error: property 'count' cannot be found in forward class object 'NSArray'
    NSUInteger count = preferredLangs.count;
                       ~~~~~~~~~~~~~~ ^
../include/wx/defs.h:2747:8: note: forward declaration of class here
@class NSArray;
       ^
../src/osx/core/uilocale.mm:234:53: error: expected method to read array element not found on object of type 'NSArray *'
        preferred.push_back(wxCFStringRef::AsString(preferredLangs[j]));
                                                    ^
1 warning and 2 errors generated.
make: *** [basedll_core_uilocale.o] Error 1
```
This was not encountered on commit 3900ece2eeb355d43b84c74a5d9eccc22ba40e9e.

Build steps:
1. Create build_cocoa_debug folder
2. Call in build_cocoa_debug folder "../configure --enable-debug"
3. Call in build_cocoa_debug folder "make"

Attached is the build and configure logs.
[build.zip](https://github.com/wxWidgets/wxWidgets/files/8413858/build.zip)

**Platform and version information**
 - wxWidgets 3.1.6 RC (4da102f2b177bec948e8e060d5c792e54a73f505)
 - wxWidgets port you use: wxOSX
 - OS and its version: Mac OSX 10.12.6
 - Compiler being used: XCode 8.3

**Comment by csomor** [comment]
I remember having such spurious errors as well under some system < 10.14, but we shouldn't have to change the source. IIRC a clean install of xcode solved things. And is there a reason to use Xcode 8.3 and not 9.2 ?

**Comment by csomor** [comment]
btw, this is a good overview for macOS and corresponding Xcode versions

https://xcodereleases.com

**Comment by vadz** [comment]
I'd like to ask @guzmanpaco to check if adding the `#import <Foundation/NSArray.h>` line above helps first. If it is, there should be no real problem with adding it, should there?

**Comment by dconnet** [comment]
I ran into the same thing on my old system. Then I remembered I was working with an old SDK (10.11 I think). After removing those and using the current one, everything built correctly.

**Comment by vadz** [comment]
But we're still supposed to support 10.11 SDK, so I'd like to fix it if it can be done easily.

Otherwise we need to increase the minimum required SDK version in the docs.

**Comment by guzmanpaco** [comment]
Hi.

I tried adding #import <Foundation/NSArray.h> to uilocale.mm and compilation using make works. Although 2 items I've reported are still broken:

1. wxCocoa project still missing volume.mm on static (Linking error)
2. Locale->AddCatalog("file.mo") loads file.mo.mo in Mac (Locale text is not loaded correctly in 3.1.6 OSX)

Preferably we would like to not adjust wxWidgets source code as it is against our policy to edit open source code.

**Comment by vadz** [comment]
Thanks for testing, I'm pushing a fix for this.

The Xcode project needs to be updated, but someone else would need to do it. It would be nice to have a separate issue for it, so that it doesn't get forgotten.

Is the translations issue the same as #22198? I'm sorry, but I don't see where did you report it?

**Comment by vadz** [comment]
The original issue has been fixed in the commit above, the Xcode project has been updated in 533958be10a2bd0246e6ce740873f7377c14f906 and is now being tested by the CI builds as of db49f840aba0fd7f1d86d8c032af6dc8a5258b76 and I still don't know what the translation issue is, so I think that this issue is fixed and we need another one for the message catalog loading problem with more details -- could you please open one if it's different from #22198? TIA!
