### ISSUE TITLE
wxFileName::AppendDir with UNC Windows paths inserts an unexpected volume separator

### ISSUE THREAD

**Issue by hobbitdev** [wxWidgets/wxWidgets#22275]
**Describe the bug**
The function wxFileName::AppendDir inserts an unexpected volume separator working with UNC paths.
This behavior has appeared using the new wxWidgets version 3.1.6, with the previous version 3.1.5 was OK.
The code written using such class doesn't work anymore.

**Expected vs observed behaviour**
Executing the code below I expect a path like this one: \\\\192.168.84.1\workspace\develop\tools
... but the result is: \\\\192.168.84.1:\workspace\develop\tools

![image](https://user-images.githubusercontent.com/33904565/161734955-f2c5e9c6-092c-41ca-a986-312dcf5e18bf.png)

**Patch or snippet allowing to reproduce the problem**
```
wxString path("\\\\192.168.84.1\\workspace\\develop");
wxFileName fn;
fn.SetPath(path);
fn.AppendDir("tools");
fn.Normalize();
wxLogMessage(fn.GetPath());
```

Same behaviour using this code
```
wxString path("\\\\192.168.84.1\\workspace\\develop");
wxFileName fn(path);
fn.AppendDir("tools");
fn.Normalize();
wxLogMessage(fn.GetPath());
```

**Platform and version information**
 - wxWidgets version you use: 3.1.6
 - wxWidgets port you use: wxMSW
 - OS and its version: Windows 10

**Comment by hobbitdev** [comment]
@PBfordev Thank you for your post

I can confirm the same issue with an existing path, and with the version 3.1.5 it was fine

**Comment by hobbitdev** [comment]
@PBfordev I could test the code without `wxPATH_NORM_LONG` flag

Using these flags
`fn.Normalize(wxPATH_NORM_ENV_VARS | wxPATH_NORM_DOTS | wxPATH_NORM_TILDE | wxPATH_NORM_CASE | wxPATH_NORM_ABSOLUTE | wxPATH_NORM_SHORTCUT);`
The issue disappears

Only for my knowledge ... despite the flags, in case of UNC path the volume separator should not be added, am I missing something ?
Avoiding to add the volume separator the function should be more secure, even concerning compatibility with old code.

Regards

**Comment by PBfordev** [comment]
I cannot reproduce the issue for an existing UNC path. However, I can when using your code, which constructs `wxFileName` from a string without a trailing `0`.

For example (where `<myIPAddress>` is my actual IPv4 address) the appended directory is added "incorrectly":
```cpp
wxString   path(R"(\\<myIPAddress>\ts)");        
wxFileName fn(path);
        
if ( !fn.AppendDir("testDir") )
    wxLogError("Could not append dir!");

wxLogDebug(fn.GetFullPath()); //  prints "\\<myIPAddress>\testDir\ts"
fn.Normalize(wxPATH_NORM_ALL);       
wxLogDebug(fn.GetPath());    // prints "\\<myIPAddress>:\testDir"
```

When a `wxFileName` is constructed from a string with a trailing slash, (e.g., `R"(\\<myIPAddress>\ts\)"`), its last part is considered a folder and not file name; it works as expected and these two are printed
```
\\<myIPAddress>\ts\testDir\
\\<myIPAddress>\ts\testdir
```

The volume separator being extraneously added is a bug, probably caused by the [last change in the source](https://github.com/wxWidgets/wxWidgets/commit/549e0a59b1157e8606d70c1ed4192676d7080e1a).

Until it is fixed, I would try:
1. If a `wxFileName` is created for a folder, use a trailing slash.
2. Use only necessary flags when calling `wxFileName::Normalize()`.

**Comment by hobbitdev** [comment]
Thank you @PBfordev, got it !

Best regards

**Comment by PBfordev** [comment]
Just to be sure I was clear, if the last part of your path string used for creating a `wxFileName` is a folder, a trailing path separator should always be used, otherwise the part is considered a file name. 

AFAIK, this is not a wxWidgets bug but intended behaviour and it has always worked like this.

**Comment by hobbitdev** [comment]
@PBfordev you was clear, the only issue I wanted to report is related to volume separator wich is added using UNC paths

**Comment by vadz** [comment]
Thanks for finding this regression, this will definitely need to be fixed.

**Comment by hobbitdev** [comment]
@PBfordev, @vadz Thanks to you guys

**Comment by vadz** [comment]
I've finally fixed this in the linked PR, which I'll merge soon if nobody sees any problems with it.

Thanks again for reporting this!
