### ISSUE TITLE
wxMSW 3.1.6 wxLocale::Init() doesn't detect UI language same as 3.0.5

### ISSUE THREAD

**Issue by aullidolunar** [wxWidgets/wxWidgets#22281]
I just compiled wxWidgets 3.1.6 in Windows 7, vc 2010 with the following command:
`nmake /f makefile.vc BUILD=release SHARED=1 TARGET_CPU=X64`
I test my current project coded with wxMSW 3.0.5;
```
bool MyApp::OnInit()
{
m_locale.Init(); // default english strings in 3.1.5+ / spanish strings in 3.0.5
m_locale.AddCatalogLookupPathPrefix( wxT(PACKAGE_LOCALEDIR) ); // some/locale
m_locale.AddCatalog( wxT(PACKAGE_NAME) );
MyFrame *frm = new MyFrame();
frm->Show( true );
return true;
}
```
The above code compiled with 3.1.6 doesn't detect my spanish UI same as in 3.0.5, had to make a version checking in order to work:
```
#if wxCHECK_VERSION(3, 1, 5)
m_locale.Init(wxLANGUAGE_SPANISH_MEXICAN); // show  spanish strings as expected in 3.1.5+
#else
m_locale.Init(); // shows spanish string as expected in 3.0.5
#endif
```

**Comment by vadz** [comment]
Thanks for reporting, I'm going to try to look at this a.s.a.p.

**Comment by vadz** [comment]
I can't reproduce this problem here. Could you please show the output of
```cpp
    wxLocale loc;
    loc.Init();
    wxLogMessage("Locale: %s, canonical name: %s", loc.GetLocale(), loc.GetCanonicalName());
```
for you?

**Comment by aullidolunar** [comment]
From code:
```
m_locale.Init();
wxLogMessage("Locale from %s: %s, canonical name: %s", wxVERSION_STRING, m_locale.GetLocale(), m_locale.GetCanonicalName());
```
See the screenshots:
![wx305](https://user-images.githubusercontent.com/7794756/162094522-4c669f82-248d-47e5-baf8-904ab2d1bc41.png)
![wx316](https://user-images.githubusercontent.com/7794756/162094526-237b235a-36d8-4e12-835a-296bfc26a3d5.png)
In both wxWidgets versions my app has access to the same locale dir with mo files.

**Comment by utelle** [comment]
Could you please provide screenshots of the **language and region settings** of your system?

You find this information in the _Windows Control Panel_ under _Time, Language, and Region settings_ and there under _Language and Region_. The first tab of that dialog shows the _Formats_ settings - at the top a combo box with a language/region combination; the second tab shows the _geographical location_ settings - a combo box with a geographical region. Please make screenshots of both tabs. TIA.

**Background:**
To determine the system default locale wxWidgets 3.0.5 used system function `GetUserDefaultLCID`. This was changed in wxWidgets 3.1.5 to using system function `GetUserDefaultUILanguage`. wxWidgets 3.1.6 tries to use system function `GetUserPreferredUILanguages` (or `GetUserDefaultUILanguage`, if the former function is not supported by the operating system). This change was introduced, because newer Windows versions (Windows 10 and above) support many locales, for which no LCID is defined.

**Comment by aullidolunar** [comment]
Attaching screenshots:
![locale01](https://user-images.githubusercontent.com/7794756/162228648-2a1bb28e-8562-428b-b05b-e51f51b03ee4.png)
![locale02](https://user-images.githubusercontent.com/7794756/162228656-0129e0fa-9220-4060-bb8a-b2bfded4dd46.png)
![locale03](https://user-images.githubusercontent.com/7794756/162228658-345e95c6-a3d1-4dc0-9d46-c08950f7a48b.png)
![locale04](https://user-images.githubusercontent.com/7794756/162228661-949c9beb-0ac8-481f-9231-078c98f62a44.png)

**Comment by vadz** [comment]
This is probably specific to Windows 7 (this still doesn't explain why it doesn't work, of course).

Also, do I understand correctly that you only have `es_MX` catalogs and no just `es` ones? Because even if misdetect the region now, we should still fall back to `es` if nothing is found for `es_ES`.

**Comment by utelle** [comment]
In the meantime I made a small experiment with the _internat_ sample. I used a Windows 7 VM to replicate your environment. I changed the Windows locale settings to "Spanish (Mexico)" and the location to "Mexico". I restarted Windows thereafter. However, the UI language of Windows was not changed - I have a German version installed. Nevertheless, in the internat sample the call to `wxUILocale::UseDefault()` changed the locale to "Spanish (Mexico)", but the default language retrieved by `wxLocale::GetLanguageInfo(wxLANGUAGE_DEFAULT)` was "German (Germany)". I have no clue why the function `GetUserPreferredUILanguages` does not return the language selected in the Windows system settings.

**Comment by aullidolunar** [comment]
> This is probably specific to Windows 7 (this still doesn't explain why it doesn't work, of course).
> 
> Also, do I understand correctly that you only have `es_MX` catalogs and no just `es` ones? Because even if misdetect the region now, we should still fall back to `es` if nothing is found for `es_ES`.

Yes. I have one mo file for spanish version named "${DATA_DIR}/locale/es_MX/LC_MESSAGES/myapp.mo". But guess what: if rename **es_MX** to **es** 3.1.6 compiled app show spanish strings same as 3.0.5

**Comment by vadz** [comment]
Yes, this is expected: we always fall back on `lang` if `lang_REGION` is not found. But this is still a bug, e.g. you might want to have (slightly) different `es_ES` and `es_MX` catalogs (and you will always want to have different `pt_PT` and `pt_BR` ones, for example).

**Comment by aullidolunar** [comment]
So, the possible bug is responsable that some strings still in english from wxWidgets std.mo?
![locale05](https://user-images.githubusercontent.com/7794756/162284313-faa7a35f-fdae-4434-a40c-025ccff909b1.png)

**Comment by vadz** [comment]
Sorry, I don't know. Please do `$ WXTRACE=i18n your-app` and check which message catalogs are (not) being loaded.

**Comment by utelle** [comment]
> [...] we always fall back on `lang` if `lang_REGION` is not found.

One possible enhancement could be to check for availability of a message catalog for the requested language, but a different region. That is, if neither an `es_ES` nor an `es` message catalog is available, but an `es_MX` message catalog is, the latter could be selected as a fallback. I don't know whether this is a reasonable approach or not.

> But this is still a bug, e.g. you might want to have (slightly) different `es_ES` and `es_MX` catalogs (and you will always want to have different `pt_PT` and `pt_BR` ones, for example).

The problem we now have is that prior versions of wxWidgets always looked at the default **locale**, while since version 3.1.5 the **UI language** is inspected. Actually, at least since Windows 7 the operating system distinguishes between UI language (used for displaying text) and locale (used for formatting numbers, dates etc). Most of the time the UI language will most likely correspond to the locale, but as can be seen in this issue this is obviously not always the case.

AFAICT for Windows 7 there exists only one generic Spanish version (i.e. "es_ES"). This is different for Windows 10 where 2 different Spanish versions are available, namely "es_ES" and "es_MX". That seems to be the reason that "es_ES" is determined as the default system language under Windows 7.

@vadz We will have to decide how `wxUILocale` should behave resp what wxWidgets users will expect. Currently, `wxUILocale::UseDefault` uses the default user **locale**, while `wxUILocale::GetPreferredUILanguages` uses the preferred UI **language** (that may differ from the default locale). This is perfectly legal and IMHO it should be supported that the default UI language doesn't match the default locale. However, `wxLocale` should probably behave as in previous versions and should use the default **locale** to determine the default UI language. Additionally, `wxUILocale` should offer a method to determine the default **locale**, not only the default/preferred UI language.

**Comment by vadz** [comment]
> > [...] we always fall back on `lang` if `lang_REGION` is not found.
> 
> One possible enhancement could be to check for availability of a message catalog for the requested language, but a different region. That is, if neither an `es_ES` nor an `es` message catalog is available, but an `es_MX` message catalog is, the latter could be selected as a fallback. I don't know whether this is a reasonable approach or not.

I think it should be, it's obviously not perfect, but I don't see how it could be worse than not using the wanted language at all.
 
> > But this is still a bug, e.g. you might want to have (slightly) different `es_ES` and `es_MX` catalogs (and you will always want to have different `pt_PT` and `pt_BR` ones, for example).
> 
> The problem we now have is that prior versions of wxWidgets always looked at the default **locale**, while since version 3.1.5 the **UI language** is inspected. Actually, at least since Windows 7 the operating system distinguishes between UI language (used for displaying text) and locale (used for formatting numbers, dates etc). Most of the time the UI language will most likely correspond to the locale, but as can be seen in this issue this is obviously not always the case.

Sorry, I don't understand: one of the screenshots above shows that the locale is "Spanish (Mexico)" (translating from Spanish) and another one shows that the region is set to "Mexico" too. I could understand that we'd have trouble in case of a conflict between these settings, but here both of them unambiguously select `es_MX` -- so I still don't understand why we don't use it.

> AFAICT for Windows 7 there exists only one generic Spanish version (i.e. "es_ES"). This is different for Windows 10 where 2 different Spanish versions are available, namely "es_ES" and "es_MX". That seems to be the reason that "es_ES" is determined as the default system language under Windows 7.

This seems very surprising and doesn't explain where does the "Mexico" part in the first screenshot above come from -- surely it must be returned by some function even under Windows 7?
 
> @vadz We will have to decide how `wxUILocale` should behave resp what wxWidgets users will expect. Currently, `wxUILocale::UseDefault` uses the default user **locale**, while `wxUILocale::GetPreferredUILanguages` uses the preferred UI **language** (that may differ from the default locale). This is perfectly legal and IMHO it should be supported that the default UI language doesn't match the default locale. However, `wxLocale` should probably behave as in previous versions and should use the default **locale** to determine the default UI language. Additionally, `wxUILocale` should offer a method to determine the default **locale**, not only the default/preferred UI language.

Could we do whatever 3.0 did for old Windows versions in `GetPreferredUILanguages()`? I don't immediately see the difference with what we did there, to be honest, but there must be some if it returns different results.

**Comment by utelle** [comment]
> > One possible enhancement could be to check for availability of a message catalog for the requested language, but a different region. That is, if neither an `es_ES` nor an `es` message catalog is available, but an `es_MX` message catalog is, the latter could be selected as a fallback. I don't know whether this is a reasonable approach or not.
> 
> I think it should be, it's obviously not perfect, but I don't see how it could be worse than not using the wanted language at all.

Well, it probably depends on the language. Whether one chooses "es_MX" instead of "es_ES" most likely doesn't make much of a difference. However, if originally "pt_AO" was requested most likely "pt_PT" would be more appropriate than "pt_BR" (but "pt_BR" might be the first match).

> Sorry, I don't understand: one of the screenshots above shows that the locale is "Spanish (Mexico)" (translating from Spanish) and another one shows that the region is set to "Mexico" too. I could understand that we'd have trouble in case of a conflict between these settings, but here both of them unambiguously select `es_MX` -- so I still don't understand why we don't use it.

This is Windows 7. The screenshots are all related to the default **locale**. The default UI language usually can't be changed (unless you use Windows 7 Ultimate or Enterprise) and corresponds to the installation language (which is "es_ES" here - not shown in any system screenshot, but in the wx 3.1.6 screenshot).

Just as Windows 10, Windows 7 also differentiates between UI language and default locale. In the system settings of Windows 10 you can select the default UI display language from a list of preferred languages, and additionally you can select a regional format (locale) - often matching the UI language, but not necessarily. In Windows 7 you have usually only access to the locale settings, while the UI language is determined at installation time of the OS.

> > AFAICT for Windows 7 there exists only one generic Spanish version (i.e. "es_ES"). This is different for Windows 10 where 2 different Spanish versions are available, namely "es_ES" and "es_MX". That seems to be the reason that "es_ES" is determined as the default system language under Windows 7.
> 
> This seems very surprising and doesn't explain where does the "Mexico" part in the first screenshot above come from -- surely it must be returned by some function even under Windows 7?

The CRT function `setlocale` (that `wxLocale` invokes) returns "es_MX" for the default locale (""). However, the method `wxUILocaleImpl::GetPreferredUILanguages` that is called by `wxUILocale::GetSystemLanguage` returns "es_ES", because that is the underlying system language, although the **locale** (for formatting) is set to "es_MX".

> Could we do whatever 3.0 did for old Windows versions in `GetPreferredUILanguages()`?

IMHO we must differentiate between what `wxLocale` does and what `wxUILocale` does. The new class `wxUILocale` should use the **locale** settings for the formatting and the **language** settings for the UI language (resp message catalogs). To make the difference between **locale** and **UI language** clear, there should be a way to determine not only the preferred UI languages, but also the default locale (actually the locale set by `wxUILocale::UseDefault`).

> I don't immediately see the difference with what we did there, to be honest, but there must be some if it returns different results.

In versions prior to 3.1.5 system functions were used that accessed **locale** data only.

**Comment by vadz** [comment]
> > > One possible enhancement could be to check for availability of a message catalog for the requested language, but a different region. That is, if neither an `es_ES` nor an `es` message catalog is available, but an `es_MX` message catalog is, the latter could be selected as a fallback. I don't know whether this is a reasonable approach or not.
> > 
> > I think it should be, it's obviously not perfect, but I don't see how it could be worse than not using the wanted language at all.
> 
> Well, it probably depends on the language. Whether one chooses "es_MX" instead of "es_ES" most likely doesn't make much of a difference. However, if originally "pt_AO" was requested most likely "pt_PT" would be more appropriate than "pt_BR" (but "pt_BR" might be the first match).

But the alternative is between using `pt_BR` or `en_US` and the former would seem to be clearly better, even if `pt_PT` would be better still.

> This is Windows 7. The screenshots are all related to the default **locale**. The default UI language usually can't be changed (unless you use Windows 7 Ultimate or Enterprise) and corresponds to the installation language (which is "es_ES" here - not shown in any system screenshot, but in the wx 3.1.6 screenshot).

I see, thanks.

> > This seems very surprising and doesn't explain where does the "Mexico" part in the first screenshot above come from -- surely it must be returned by some function even under Windows 7?
> 
> The CRT function `setlocale` (that `wxLocale` invokes) returns "es_MX" for the default locale (""). 

But where does this value come from? CRT is not magic under MSW, it uses the same Win32 API as everybody else. There must be some way of retrieving it.

>However, the method `wxUILocaleImpl::GetPreferredUILanguages` that is called by `wxUILocale::GetSystemLanguage` returns "es_ES", because that is the underlying system language, although the **locale** (for formatting) is set to "es_MX".

I think the value returned by `GetSystemLanguage()` is wrong under Windows 7. The system language there isn't used for anything, AFAIK, and it's not useful to return it, even if it could be formally seen as the right thing to do.

> > Could we do whatever 3.0 did for old Windows versions in `GetPreferredUILanguages()`?
> 
> IMHO we must differentiate between what `wxLocale` does and what `wxUILocale` does.

Sorry, I don't see any real need to do this. IMO it's not useful to return Spanish from `wxUILocale` neither.

> > I don't immediately see the difference with what we did there, to be honest, but there must be some if it returns different results.
> 
> In versions prior to 3.1.5 system functions were used that accessed **locale** data only.

This isn't completely correct, we used them at least here:

https://github.com/wxWidgets/wxWidgets/blob/f5977dee2123a342601250b9a87bc2549c13cdd0/src/common/translation.cpp#L129

**Comment by utelle** [comment]
> > Well, it probably depends on the language. Whether one chooses "es_MX" instead of "es_ES" most likely doesn't make much of a difference. However, if originally "pt_AO" was requested most likely "pt_PT" would be more appropriate than "pt_BR" (but "pt_BR" might be the first match).
> 
> But the alternative is between using `pt_BR` or `en_US` and the former would seem to be clearly better, even if `pt_PT` would be better still.

I just wanted to discuss this in detail, so that chances are higher to make the right decision.

**Conclusion:** enhance `wxTranslation` to pick the first combination "language_region" for which only the _language_ matches if a direct match for "language_region" or "language" is not among the available translations.

> > The CRT function `setlocale` (that `wxLocale` invokes) returns "es_MX" for the default locale ("").
> 
> But where does this value come from? CRT is not magic under MSW, it uses the same Win32 API as everybody else. There must be some way of retrieving it.

`setlocale` probably uses `GetUserDefaultLocaleName` (not `GetPreferredUILanguages`).

> > However, the method `wxUILocaleImpl::GetPreferredUILanguages` that is called by `wxUILocale::GetSystemLanguage` returns "es_ES", because that is the underlying system language, although the **locale** (for formatting) is set to "es_MX".
> 
> I think the value returned by `GetSystemLanguage()` is wrong under Windows 7. The system language there isn't used for anything, AFAIK, and it's not useful to return it, even if it could be formally seen as the right thing to do.

That depends on the Windows version. For Windows 7 Ultimate or Enterprise it is legitimate to assume that the UI display language is the preferred language - it's the language returned by `GetPreferredUILanguages`. Why should we claim to know it better than the OS?

> > IMHO we must differentiate between what `wxLocale` does and what `wxUILocale` does.
> 
> Sorry, I don't see any real need to do this. IMO it's not useful to return Spanish from `wxUILocale` neither.

Since Windows 7 (maybe Vista, too) the OS differentiates between UI language and default locale. And `wxUILocale` should do that, too. IMHO `wxUILocale` should therefore use the value returned by `GetPreferredUILanguages` as the system language even under Windows 7. OTOH `wxLocale` should use the default locale for that purpose, because that is what it always did in the past (prior to wxWidgets 3.1.6).

> > In versions prior to 3.1.5 system functions were used that accessed **locale** data only.
> 
> This isn't completely correct, we used them at least here:
> 
> https://github.com/wxWidgets/wxWidgets/blob/f5977dee2123a342601250b9a87bc2549c13cdd0/src/common/translation.cpp#L129

Yes, that's true. I looked only at the `wxLocale` implementation. However, for this issue it didn't matter, because there didn't exist a message catalog for "es_ES" (as returned by `GetPreferredUILanguages`). Therefore `wxTranslation` called `GetPreferredUILanguageFallback` that returned the language based on the default locale prior to 3.1.5, and thus the language "es_MX" was used as expected by the user.

**Comment by vadz** [comment]
> I just wanted to discuss this in detail, so that chances are higher to make the right decision.
> 
> **Conclusion:** enhance `wxTranslation` to pick the first combination "language_region" for which only the _language_ matches if a direct match for "language_region" or "language" is not among the available translations.

I agree with this, but I think that this is a separate enhancement that is not directly related to this issue per se.

> > I think the value returned by `GetSystemLanguage()` is wrong under Windows 7. The system language there isn't used for anything, AFAIK, and it's not useful to return it, even if it could be formally seen as the right thing to do.
> 
> That depends on the Windows version.

Yes, absolutely, and I think we should trust the value returned by Windows in Windows 10 (or maybe even 8) and later, just not for 7 (nor, a fortiori, Vista).

> For Windows 7 Ultimate or Enterprise it is legitimate to assume that the UI display language is the preferred language - it's the language returned by `GetPreferredUILanguages`. Why should we claim to know it better than the OS?

Because I think they changed their own mind about it in later versions, which seems to confirm that Windows 7 behaviour was not useful. AFAIR (I have to leave right now so I can't confirm this, but will try to do it later), the system language in Windows 7 was fixed at the moment of installation and couldn't be changed later, so the user could change their UI to use a completely different language and some Windows functions would still return the installation language and not the one actually used for the UI. I.e. I suspect we might have worse problems than `es_ES` vs `es_MX` mismatch and could even have mismatches in the language part too. But, again, I'd need to confirm it.

> However, for this issue it didn't matter, because there didn't exist a message catalog for "es_ES" (as returned by `GetPreferredUILanguages`). Therefore `wxTranslation` called `GetPreferredUILanguageFallback` that returned the language based on the default locale prior to 3.1.5, and thus the language "es_MX" was used as expected by the user.

Thanks for digging into this and explaining what happens here.

Anyhow, even if you're absolutely certain that `wxUILocale` should behave differently, I think we can start by restoring the old `wxLocale` behaviour, which would already fix this bug. And then check if it really makes sense to diverge from this in `wxUILocale` or not. If you agree, and could please make a PR changing `wxLocale` like this, it would be great, TIA!

**Comment by utelle** [comment]
> > **Conclusion:** enhance `wxTranslation` to pick the first combination "language_region" for which only the _language_ matches if a direct match for "language_region" or "language" is not among the available translations.
> 
> I agree with this, but I think that this is a separate enhancement that is not directly related to this issue per se.

You are right, of course. Nevertheless, this enhancement seems to be useful, and it should not be too hard to implement. I will look into this.

> > > I think the value returned by `GetSystemLanguage()` is wrong under Windows 7. The system language there isn't used for anything, AFAIK, and it's not useful to return it, even if it could be formally seen as the right thing to do.
> > 
> > That depends on the Windows version.
> 
> Yes, absolutely, and I think we should trust the value returned by Windows in Windows 10 (or maybe even 8) and later, just not for 7 (nor, a fortiori, Vista).

I have essentially no practical experience with Windows 8. I never installed or used it anywhere. So, regarding the decision for which Windows versions we should trust the value (and for which not) will be up to you.

> > [...] Why should we claim to know it better than the OS?
> 
> Because I think they changed their own mind about it in later versions, which seems to confirm that Windows 7 behaviour was not useful. AFAIR (I have to leave right now so I can't confirm this, but will try to do it later), the system language in Windows 7 was fixed at the moment of installation and couldn't be changed later, so the user could change their UI to use a completely different language and some Windows functions would still return the installation language and not the one actually used for the UI. I.e. I suspect we might have worse problems than `es_ES` vs `es_MX` mismatch and could even have mismatches in the language part too. But, again, I'd need to confirm it.

Ok, then let's restore the pre-3.1.5 behaviour for Windows version below Windows 10 (or maybe Windows 8).

> Anyhow, even if you're absolutely certain that `wxUILocale` should behave differently, I think we can start by restoring the old `wxLocale` behaviour, which would already fix this bug. And then check if it really makes sense to diverge from this in `wxUILocale` or not. If you agree, and could please make a PR changing `wxLocale` like this, it would be great, TIA!

Ok, I will restore the old `wxLocale` behaviour (i.e. selecting the default UI language based on the default locale). Regarding `wxUILocale` I will change the implementation of `GetPreferredUILanguages` to determine the result based on the default locale for Windows 7 and lower - actually, I tend to do it for Windows 8 and lower, but I'm open, of course, to further input.

I think I will be able to prepare a PR until Easter.

**Comment by utelle** [comment]
@vadz Today I inspected the `wxLocale` and `wxUILocale` code to analyze how to fix the issue.

IMHO we have to discuss the implementation of `wxUILocale` in general, before we start to modify anything.

Before `wxUILocale` was introduced actually no distinction was made between _language_ and _locale_. For all systems `wxLocale` called `setlocale(LC_ALL, "...")` internally to set the language and the locale-specific formatting. Thus, language and locale were always in sync with the default locale, when `wxLocale` was initialized for `wxLANGUAGE_DEFAULT`.

Then `wxUILocale` was introduced in version 3.1.5. And this also introduced implicitly a distinction between language and locale - at least for Windows. The default UI language is determined by calling `GetUserPreferredUILanguages`, while the default locale is determined via `LOCALE_NAME_USER_DEFAULT`. Thus, language and locale can be different (like in this issue "es_ES" vs "es_MX", but in general it could also be completely different like "de_DE" vs "fr_FR"). When method `wxUILocaleImpl::Use()` is called, it calls internally the function `SetThreadPreferredUILanguages`. In case of `LOCALE_NAME_USER_DEFAULT` this probably doesn't matter, because the list of preferred UI languages is cleared. However, if the `wxUILocale` was initialized with an explicit locale name, that name would be used in the call to `SetThreadPreferredUILanguages` (potentially conflicting with the preferred UI language).

Under Unix-like system it would be theoretically also possible to distinguish between language and locale by using different environment variables like 

```
LANG=es_ES.UTF-8
LANGUAGE=en_US
LC_CTYPE="es_ES.UTF-8"
LC_NUMERIC=en_EN.UTF-8
LC_TIME=en_EN.UTF-8
LC_COLLATE="es_ES.UTF-8"
LC_MONETARY=en_EN.UTF-8
LC_MESSAGES=de_DE.UTF-8
```

However, this is not supported, because the first non-empty environment variable of `LC_ALL`, `LC_MESSAGES`,  and `LANG` is used to determine the preferred UI language.

So, it has to be clarified how `wxUILocale` should behave.

**Comment by vadz** [comment]
The primary goal of `wxUILocale` is to make the application use the correct locale-dependent options in its UI. This includes the language, e.g. it should also affect the language of the buttons shown by the message boxes, by using whatever the current user default is -- even if it's different from the locale. I'm not sure if it's the case now, but if not, it should be. At least under MSW because I don't think you can mix and match things like this elsewhere, i.e. AFAIK neither GTK nor macOS support it, do they?

The secondary goal is to provide the OS-dependent information about the different locales, but this is probably not relevant here.

**Comment by utelle** [comment]
> The primary goal of `wxUILocale` is to make the application use the correct locale-dependent options in its UI. This includes the language, e.g. it should also affect the language of the buttons shown by the message boxes, by using whatever the current user default is -- even if it's different from the locale.

The description of `wxUILocale` reads _"UI locale determines all culture-dependent conventions used in the user interface, including numbers, currencies and dates formatting. It also determines the language used by the native dialogs[...]."_

The problem is that at least under Windows you can have very different settings for the culture-dependent conventions and for the UI language. For example, my development system is a German Windows system. However, I can easily specify _"Spanish (Mexico)"_ for the culture-dependent conventions, while the UI language stays _"German (Germany)"_. In the _internat_ sample this leads to the situation that the main UI language is _German_, while the calendar control will show Spanish month and weekday names, because "Spanish (Mexico)" is selected for date formatting. At first glance, that seems to be strange, but it's what's the user specified in the system.

In the situation of the above example `wxUILocale::GetName` will return the locale name "es-MX", while the static method `wxUILocale::GetSystemLanguage` will return `wxLANGUAGE_GERMAN_GERMANY` (corresponding to "de-DE"). At the moment, the class `wxUILocale` doesn't offer a method to easily identify the default user locale ("es-MX"), before actually setting it. IMHO, we need such a function, so that for example in the _internat_ sample this information can be shown to the user, before setting the locale.

> I'm not sure if it's the case now, but if not, it should be.

Up to now I accomplished in my development environment that `wxLocale` shows the behaviour as in previous wxWidgets versions for all Windows versions. That is, the default locale ("es-MX" in the above example) will be used also for the UI language. `wxUILocale` will show the same behaviour for Windows 7 and below, but will otherwise use the preferred UI language (via `wxTranslation`). (We will have to decide, how to handle Windows 8.x - like Windows 7 or like Windows 10?)

>At least under MSW because I don't think you can mix and match things like this elsewhere, i.e. AFAIK neither GTK nor macOS support it, do they?

As I tried to explain in my previous post, GTK allows in principle to specify different settings for various categories. However, AFAIK wxWidgets uses internally always `LC_ALL` (or `LC_MESSAGES` if `LC_ALL` is not set, while other categories are ignored). Nevertheless, even if the environment uses `LC_ALL` for the locale settings, you could specify a different UI language via `LANGUAGE` (while `LANG` will be overridden by `LC_ALL` IIRC). However, again wxWidgets does not take the environment setting for `LANGUAGE` into consideration - at least not in `wxUILocale` at the moment (but probably should, as `wxTranslation` uses it). I don't know details about the situation under macOS.

> The secondary goal is to provide the OS-dependent information about the different locales, but this is probably not relevant here.

No. If the locale id is explicitly specified you get information about exactly that locale, if it is valid, that is.

**Comment by vadz** [comment]
In the example above I think showing "Ja" and "Nein" in the message box but "abril" or "mayo" in the calendar is indeed the right thing to do, so I'd expect `wxUILocale` to do it, under all Windows versions. The rationale I see for it is that we should definitely use Spanish date format in this case because it's probably common to select a locale just because you want to use dates in its format, even though the rest of the system is in English, and if we use Spanish format, we must also use Spanish names.

So the most important question is, can we do this, even under Windows 10 (and 8 too, although I can't say I really care about the latter one way or the other, it must have a really minuscule amount of users)?

I'm not sure if having `GetSystemLocale()` is really that useful -- how would you actually use it in your application? -- but I definitely don't have any objections to adding it.

Concerning GTK, does it really work well with `LC_ALL` and `LANG` being set to different values? I admit I've never tested this, but if it does, I agree that we should, ideally, handle it too. It's not exactly a priority, but this would definitely be the right thing to do.

**Comment by utelle** [comment]
> In the example above I think showing "Ja" and "Nein" in the message box but "abril" or "mayo" in the calendar is indeed the right thing to do, so I'd expect `wxUILocale` to do it, under all Windows versions.

I understand **all** as _"from Windows 10 (or maybe 8.x) upward"_ as Windows 7 returns the installation language as the preferred UI language.

> So the most important question is, can we do this, even under Windows 10 (and 8 too, although I can't say I really care about the latter one way or the other, it must have a really minuscule amount of users)?

In principle, it should be doable. However, this may require changes to `wxUILocale`. The loading of the message catalogs is handled separately in `wxTranslation`, and `wxTranslation` uses the preferred UI language, if the language was not explicitly specified. If `wxUILocale::UseDefault` is called, all should work as expected. However, if `wxUILocale::UseLocaleName` is called the UI language will be set based on the locale (not based on the preferred UI language). Since this is the `wxLocale` compatibility method the behaviour should be acceptable and is most likely, what the user expects.

Regarding Windows 8.x I have no experience and no test system at hand. Therefore I tend to handle it like Windows 7. That is, I would use the new behaviour for Windows 10 and upward.

> I'm not sure if having `GetSystemLocale()` is really that useful -- how would you actually use it in your application? -- but I definitely don't have any objections to adding it.

Most likely there aren't many use cases for `GetSystemLocale`, but if an application wants to inform a user about the default UI language and default locale, before actually applying them, such a method may be convenient.

> Concerning GTK, does it really work well with `LC_ALL` and `LANG` being set to different values? I admit I've never tested this, but if it does, I agree that we should, ideally, handle it too. It's not exactly a priority, but this would definitely be the right thing to do.

AFAIK `LANG` will be ignored/overridden, if `LC_ALL` is specified. However, `LANGUAGE` will override the `LC_ALL` setting regarding the UI language. I have to admit that I never tested that in practice.

I will make a PR on (or shortly after) Easter.
