### ISSUE TITLE
Class descriptions are missing in annotated doc list

### ISSUE THREAD

**Issue by oneeyeman1** [wxWidgets/wxWidgets#22288]
**Describe the bug**
The documentation on master is not very friendly.

I usually go to the class list in the doc to search for the class I'm looking for. But currently this page becomes unusable. See the screenshot for details.
The "Class List" page is unusable right now.

**Expected vs observed behaviour**
Expect the to see a liost of classes with the documentation explaining what each of them do.

**Patch or snippet allowing to reproduce the problem**

**Platform and version information**
 - wxWidgets version you use: Windows, Linux
 - wxWidgets port you use: documentation of the current master (page Class list)
 - Browsers: Google Chrome and Firefox

**Comment by vadz** [comment]
What do you mean by unusable? https://docs.wxwidgets.org/3.1.6/annotated.html looks just fine to me.

**Comment by TcT2k** [comment]
It seems like the new doxygen version doesn't include the class description in the table if the description includes headlines. The older doxygen included the first line after the headline.

**Comment by vadz** [comment]
Thanks to both you and @PBfordev for explaining what the problem is.

It looks like the brief documentation is now only shown for the classes _not_ using `@class` in their docs. Probably worth testing with a different (1.9.x) doxygen version to see if it's not just another Doxygen bug, but OTOH we probably could remove `@class` lines too.

**Comment by PBfordev** [comment]
I have noticed another major issue, which I believe has not been reported yet.

 In pages for modules of _Functions and Macros by Category_, the macros and functions are entirely missing, only the module description is displayed, for example
https://docs.wxwidgets.org/trunk/group__group__funcmacro__appinitterm.html
vs
https://docs.wxwidgets.org/3.1.5/group__group__funcmacro__byteorder.html

BTW, the link to the related **class** group on those pages is mislabeled, since forever. It reads "Related **macros/global-functions** group:" .

**Comment by vadz** [comment]
The original issue has been corrected in Doxygen 1.9.1 that I plan to use for 3.2.0 docs, but the issue with the group pages being empty remains and I have no idea how to convince Doxygen to generate anything there.

**Comment by oneeyeman1** [comment]
Vadim,

On Thu, Apr 7, 2022 at 5:00 PM VZ ***@***.***> wrote:
>
> What do you mean by unusable? https://docs.wxwidgets.org/3.1.6/annotated.html looks just fine to me.

Sorry I couldn't find where to attach a screenshot in there.

Attaching it now to this message...

Thank you.

**Comment by vadz** [comment]
You can easily attach files to comments on GitHub. If you attached anything to your email, it hasn't made it through email-to-GitHub gateway.
