### ISSUE TITLE
wxBitmap does not free gdi handles of DIBs

### ISSUE THREAD

**Issue by marekr** [wxWidgets/wxWidgets#22293]
Another bug that is eating GDI handles like crazy for us in KiCad

It appears to be primarily from using the wxBitmap constructor that accepts a wxImage object.

wxBitmap::CreateFromImage in the code path from that constructor kicks off the problem:
https://github.com/wxWidgets/wxWidgets/blob/master/src/msw/bitmap.cpp#L902

Where it detaches the DIB from the wxDIB class
and then on line 929, the dib handle is assigned to `m_handle`

Nowhere in wxBitmap is an attempt made to free m_handle from GDI.

Interestingly, the `wxBitmapRefData` class instead checks if `m_hBitmap` is set and frees that gdi object instead.

m_handle apparently is defined in `wxGDIImageRefData`, the parent class of `wxBitmapRefData` but also it makes no attempt to do a DeleteObject on m_handle either.

**Comment by marekr** [comment]
Ah I screwed up because m_handle is unioned to m_hBitmap in the parent class. And the usage is weirdly mixed in wxBitmap.

The leak still exists somewhere via the wxBitmap(wxImage) constructor and I am working on figuring it out

**Comment by vadz** [comment]
Yes, the use of the union is not very obvious, but I don't know how to reuse all the common functionality of bitmaps, icons and cursors that basically have the same API but are represented by different types without either losing all type safety (i.e. using only `HANDLE`) or adding a bunch of virtual functions that could have non-trivial effect on performance (mainly due to making it impossible to inline them).

If you can make a SSCCE showing the leak, I'd like to look at it before 3.2.0.
