### ISSUE TITLE
wxWindowListNode missing in msw build

### ISSUE THREAD

**Issue by WilliamBehrens** [wxWidgets/wxWidgets#22304]
I recently upgraded my project from wxWidgets 3.1.2 to 3.1.5 and I'm getting the error: `'wxWindowListNode': undeclared identifier`. I'm assuming that this class was deprecated an I was wondering what the replacement was?

**Comment by vadz** [comment]
No, this symbol wasn't removed (if it were deprecated you'd get a warning about this, not an error), and should still be defined in `wx/window.h` if `wxUSE_STD_CONTAINERS==0`. If you do use standard containers, then this class isn't available, but this is not new (must have been the case since 3.0, I think).

So please check whether you're using this (non default) build option or not and, if you don't, please show some minimal code reproducing the problem.

**Comment by PBfordev** [comment]
This is odd as this code works for me with the current master (i.e., post 3.1.6):
```cpp
#include <wx/wx.h>

class MyApp: public wxApp
{
public:
    bool OnInit() override
    {
        wxFrame*          frame = new wxFrame(nullptr, wxID_ANY, "Test");
        wxWindowListNode* node = nullptr;

        new wxButton(frame, wxID_ANY, "Button");
        node = frame->GetChildren().GetFirst();
        if ( node )
            wxLogDebug("First node name: %s", node->GetData()->GetName());

        frame->Show();
        return true;
    }
}; wxIMPLEMENT_APP(MyApp);
```

However, wxWidgets code itself uses `wxWindowList::iterator` instead of `wxWindowListNode`, like this (in the user code it would probably be better to use `auto i = ...`) https://github.com/wxWidgets/wxWidgets/blob/ce46d773609154f9e6c663e08aca96e2314db23d/src/common/wincmn.cpp#L1270-L1279.

Maybe it depends on wxWidgets build options, such as using STL containers....

**Comment by WilliamBehrens** [comment]
> 

so whenever I compile wxWidgets with cmake I have to add `-DwxUSE_STD_CONTAINERS=OFF`?

**Comment by vadz** [comment]
> so whenever I compile wxWidgets with cmake I have to add `-DwxUSE_STD_CONTAINERS=OFF`?

No, this is the default. 

The problem is probably related to this build option, but it's really difficult to say without having more information. At the very least, please check which value of this option you are currently using.
