### ISSUE TITLE
Add wxBitmapBundle support to wxRibbonBar

### ISSUE THREAD

**Issue by Runtemund** [wxWidgets/wxWidgets#22336]
I would like to add support of `wxBitmapBundle` in `wxRibbonBar`, but there are some issues I would like to discuss first. Because it also could have impact to 'wxBitmapBundle'.

In general it seems not very complicated to switch `wxBitmap` used the to `wxBitmapBundle`, but the following points should have a solution first:

- `wxRibbonBar` does not store any default sizes of a tool icon size. It will display the bitmap in the size it is. Wheter it is suqare or rectangular. This possibility is good especially if you create custom tools. So this functionality should be preserved. But we also need default sizes which the programmer can modify. `wxBitmapBundle` uses the size of the first bitmap as default size. Actually you cannot change the default size. In the past I also had to manage icon size depending on screen dpi by myself. What is better, defining a default icon size in wxRibbon or give the developer the possibility to change default icons size of the `wxBitmapBundle`?

- `wxRibbonBar` creates "disabled" icons by converting them to greyscale if they are not provided. But acutally it is not possible to convert this method, because `wxBitmapBundle` does not have a possibility to iterate over the containing bitmaps, like it is possible in `wxIconBundle`. Could we add the possibility to wxBitmapBundle? Or should I extract needed bitmaps and cache them in the tools of the wxRibbonBar?

- Have I something forgotten, which I should consider?

**Comment by vadz** [comment]
`wxBitmapBundle::GetDefaultSize()` can be used to get the size of the bitmap at normal DPI, but typically you don't need to call it directly and should just use `GetPreferredBitmapSizeFor(this)` or even directly `GetBitmapFor(this)` where `this` is some window. This will return the correct size to use.

For the disabled bitmaps, the code needs to continue working at individual bitmaps level (just as in `wxToolBar`), there is indeed no way to currently get a "disabled bundle". This is something it might be useful to add, but it can't be done by allowing to iterate over individual bitmaps, if only because there may not _be_ any individual bitmaps, as in an SVG bundle. Realistically, for 3.2.0 time frame we really just need to keep using `MakeDisabledBitmap()`.

**Comment by Runtemund** [comment]
Ok, "default size" was perhaps a little inaccurately expressed. what I mean by that. The `wxRibbonBar` has no default/preferred logical size of an icon. I can display it with 16x16, 32x32 etc. (also mixed) and it appears in different sizes depending on provided `wxBitmap`. There is no scaling by default, only for minimized icons. But, if I provide an image without a fixed size, which is what a wxBitmapBundle from SVG would be then, I have to give it a preferred size, otherwise the ribbon does not know which size to take. In my test case I convert a `wxIconBundle` to `wxBitmapBundle` which has the smallest icon first and provide then 16x16 as default size. So just using `GetBitmapFor(this)` will return a too small bitmap. But I would like to show 32x32 or bigger. 

And my thinking was whether I pass preferred size individually in each `wxBitmapBundle` before passing it to the `wxRibbon{Tool|Button}` (which needs to set it in `wxBitmaBundle`) or I set a "default" value in the ribbon bars and set individual values in the individual tools and not in the bitmap bundle itself. Perhaps the second one is the better way.

**Comment by vadz** [comment]
The default size of `wxBitmapBundle` corresponds to the size of the bitmap, so I don't think there is any reason to do anything special here. I.e. if you previously used a bitmap of size 32x32 and now you use a bitmap bundle containing bitmaps of size 32x32 and 64x64, it will still use 32x32 in normal DPI and 64x64 in high DPI.

Note that `wxBitmapBundle` always has a preferred size, even for SVG-based ones.

**Comment by Runtemund** [comment]
In my imagination`wxBitmapBundle` shouldn't be just a container for managing high resolution representations of one bitmap. Actually I use `wxIconBundle` in my software for managing icons/bitmaps for the UI elements. In this bundles are representations from 16x16 up to 64 x 64 usually, sometimes higher, depending on usage. I use this bundle as a single resource for all components. For example as 16x16 bitmaps for `wxDataViewCtrl` or `wxMenuItem` and higher resolutions for  `wxRibbon{Button|Tool}Bar`.  Actually the "size management" and converting I have to do by my own and it would be appreciate if I can "outsource" it to the UI library, because this handling is in my eyes a task of the UI, not me.
I agree, that `wxBitmapBundle` is probably not the ideal place for storing this control dependent "preferred size". On the other hand, the method `GetBitmapFor(this)` suggests to return exactly that.

Actually `wxRibbonBar` does not handle high resolution well. I have to do scale them like this: 
`int32 iconSize = std::max((int)(24 * GetDPIScaleFactor()), 32);`

I would like to close this gap to make the work easier. Together with my wish to combine all image resources in one bundle, the question of the best place for determining the preferred sizes arises.

**Comment by vadz** [comment]
> In my imagination`wxBitmapBundle` shouldn't be just a container for managing high resolution representations of one bitmap.

It's almost this, but it's more abstract than that: it's a resolution-independent bitmap. It can be implemented as a container of several representations or use SVG and render the required representation on demand or, potentially, something else.

> On the other hand, the method `GetBitmapFor(this)` suggests to return exactly that.

This returns the bitmap with the size best fitting the ideal size, which is the default size scaled up by the DPI scaling factor. But it's not clear to me if this is exactly what you need or not?

> Actually `wxRibbonBar` does not handle high resolution well.

What exactly is/are the problem(s)?

> I have to do scale them like this: `int32 iconSize = std::max((int)(24 * GetDPIScaleFactor()), 32);`

Sorry, I don't understand what does this accomplish, i.e. why would you do this with these particular numbers and how does it help with the problems that `wxRibbonBar` has. But if you really need to do exactly this, you will have to implement your custom `wxBitmapBundleImpl`-derived class because this is just too specific to do in wx itself.
 
> I would like to close this gap to make the work easier. Together with my wish to combine all image resources in one bundle, the question of the best place for determining the preferred sizes arises.

For wx, the preferred size is the default size multiplied by the DPI scaling factor. The actual bitmap size may be different from it, however, depending on the bitmaps available.

Sorry, but I'm a bit lost here and don't know what are we discussing exactly any more. Could you please explain what exactly is the problem (or the question)? TIA!

**Comment by Runtemund** [comment]
No, deriving classes is not necessary for that.

Maybe it's eseasier if I will prepare a pull request with added `wxBitmapBundle` support to `wxRibbon{Tool|Button}Bar` within the next time and we discuss along the code if necessary.

**Comment by vadz** [comment]
Yes, sure, everything doesn't need to be done in a single PR, please feel free to make a PR with some minimal, and hopefully uncontroversial, changes first and we may add/change more things later.
