### ISSUE TITLE
Flatpak SDK extension

### ISSUE THREAD

**Issue by tinywrkb** [wxWidgets/wxWidgets#22370]
As part of maintaining the Flatpak packaging of Codeblocks IDE, [I proposed adding an wxWidgets Flatpak SDK extension](https://github.com/flathub/flathub/pull/3077) that will work with Codeblocks and any other IDE that is packaged as a Flatpak app.  

Note that I'm not affiliated with the Codeblocks IDE project, and I'm not the original submitter of the Codeblocks Flatpak app, but I'm now trying to make the Flatpak packaging more useful for wxWidgets development by adding the SDK extension.

It would be great if a wxWidgets Flatpak SDK extension could be maintained officially by one of the developers here, or at least have a co-maintainer that is a wxWidgets developer.  
But if not, I think I'll still move forward with publishing the extension.

flathub/flathub#3077

**Comment by vadz** [comment]
Sorry, personally I know nothing about Flatpak SDK extensions (and very little about Flatpak itself), so I can't really help with maintaining it. We would, of course, be glad to make using wx in Flatpak easier and would be ready to help you with any questions you might have or even make some changes to make this simpler if necessary, but you'd have to ask us about them rather than counting on us (or at least me) finding and solving the problems ourselves. Please don't hesitate to do it and thanks for creating this extension!

I also have a question: would it make sense to provide 3.1.6, rather than the very old 3.0.5, as part of Flatpak? I.e. is the ABI compatibility as crucial for Flatpaks as for the "classic" Linux packages? If not, I'd strongly advise using 3.1.6, it works much better than 3.0 on contemporary Linux systems (e.g. those using Wayland).

**Comment by vadz** [comment]
There shouldn't be any API-incompatible changes between now and 3.2.0, so I think it would already make sense to target 3.1.x.

I think this issue can be closed then, as there doesn't seem to be any real problem here, please do it if you agree. And, again, please don't hesitate to post to wx-dev if you have any questions or run into any problems.

Good luck!

**Comment by tinywrkb** [comment]
Alright then, I'll target the 3.1.x development releases, and switch to stable when 3.2.0 will be out.
Thanks again!
