### ISSUE TITLE
Signature of wxRadioBox::Enable encourages errors

### ISSUE THREAD

**Issue by timrprobocom** [wxWidgets/wxWidgets#22394]
The signature of wxRadioBox::Enable is `(unsigned int n, bool enable=true)`, so that the "enable" is optional.  Every other class derived from wxWindow has an enable signature of `(bool enable=true)`.

So, why is that a problem?  Consider the common idiom of setting the enable flag based on the value of some variable state:
```
    m_rbOptions->Enable( advancedMode == 1 );
```
To someone versed in wxWidgets, that is a natural thing to write.  Because of the default value for the `enable` parameter, wxRadioBox accepts that call without complaint, but it does not do what one expects.  What that will do is enable control #0 or #1 within the radio box.  I just encountered this in software I've had running for many, many years.

Now, I clearly understand that the `enable=true` default is present in the `wxWindow::Enable` signature, and there is a certain appeal in having parallel behavior in wxRadioBox, but in my opinion this is just an opportunity for errors that could be eliminated through the minor inconvenience of requiring both parameters.  My suggestion is to change the signature at line 44 in `include/wx/radiobox.h` to:
```
    virtual bool Enable(unsigned int n, bool enable) = 0;
```
without the default.

I also clearly understand that this might not be popular.  I'm just pointing out an issue.

I'm using wxWidgets 3.0.4 on wxGTK and wxWidgets 3.1.3 on wxMSW, but the problem is generic and long-standing.

**Comment by vadz** [comment]
No, sorry, removing the default parameter value is not going to happen, it would break the existing code using it and the problem is not bad enough to justify doing this.

FWIW I agree that this is unfortunate and if we had thought about this problem when adding the original API, we would have done it differently, e.g. maybe call it `EnableItem()` or something like that, but it's way too late to do anything about it now.
