### ISSUE TITLE
Border line of GUI not working on different scale and resolutions

### ISSUE THREAD

**Issue by chris12342534** [wxWidgets/wxWidgets#22405]
**Describe the bug**
The bug am having is that my screen is connected to a monitor, and they have different percentage of scale. My computer screen is 100% and my monitor is 125%. When I run my GUI its normal on my pc screen but when I bring it on the monitor screen the border line is only covering half of the rectangle. I have attached 2 screenshots below to see the difference

**Expected vs observed behaviour**
I was expecting the GUI to scale to the monitor screen size and stay the same.

**Patch or snippet allowing to reproduce the problem**
This happen even when I started a brand-new project with widgets

Skip this step if the problem can be reproduced in one of the samples without any changes.

**To Reproduce**
Steps to reproduce the behaviour, please make them as detailed as possible, e.g.

**Platform and version information**
 - wxWidgets version you use: 3.0.0
 - wxWidgets port you use: 
 - OS and its version: Windows 120.2212.4170.0
 - For wxGTK only:
   + GTK version: 
   + Which GDK backend is used: 
   + If relevant, i.e. for appearance-related problems: 

![Correct](https://user-images.githubusercontent.com/105078299/167207319-29200702-a5bf-4f9f-abc8-0821db7ce263.png)
![Error](https://user-images.githubusercontent.com/105078299/167207321-82f5a651-484a-4c69-b72b-47e87032678a.png)

**Comment by oneeyeman1** [comment]
Hi,
Is it the same result when you try the current release - 3.1.6?
Is you program contains a manifest with "PerMonitor DPI Aware v2" turn to 1?

**Comment by MaartenBent** [comment]
Based on the screenshot it uses `System DPI` scaling. It looks crisp on the first (125%) screenshot, but a bit blurry on the second (100%) screenshot. This scaling is done by Windows, wxWidgets has no control over it. wxWidgets does not support any scaling in 3.0 so there is nothing we can do.
Other scaling options provided by Windows that you can use are `None` (crisp at 100%,  and zoomed in at 125%), or [System (enhanced) / GDI scaling](https://blogs.windows.com/windowsdeveloper/2017/04/04/high-dpi-scaling-improvements-desktop-applications-windows-10-creators-update/), which will re-render the text instead of just zooming in/out.

In wxWidgets 3.1 there is support for [PerMonitor V2 scaling](https://docs.microsoft.com/en-us/windows/win32/hidpi/high-dpi-desktop-application-development-on-windows), and the window will automatically adjust to the zoom-level / DPI of the monitor it is shown on. Providing you don't use any hardcoded pixel sizes, see [here ](https://docs.wxwidgets.org/trunk/overview_high_dpi.html)for more info.

One thing you could try is putting all the controls in a `wxPanel` and the `wxPanel` in the `wxFrame`, instead of putting everything directly in the `wxFrame`.

**Comment by vadz** [comment]
Also note that if you really use wxWidgets 3.0.0 for a new project -- please don't. Start with wx 3.1.6, it has much better (even if still not perfect) support for high DPI displays than that almost 10 year old version.

Please reopen if you still see the problem with wx 3.1.6 and per-monitor scaling.

**Comment by chris12342534** [comment]
Hello again so I updated to version 3.1.6 like I was suggested. I have created a new project with my wxFrame style said too wxDEFAULT_DIALOG_STYLE. I still have the same problem. Then I tried to migrate my project that I had already from version 3.0.0 and that works even though I have wxFrame style said too wxDEFAULT_DIALOG_STYLE. How is that possible?

**Comment by vadz** [comment]
First of all, check that you've actually enabled per-monitor DPI support as [explained in the docs](https://docs.wxwidgets.org/3.1.7/overview_high_dpi.html#high_dpi_platform_msw). If you still see the problem with it, please try to provide a [small example](https://sscce.org/) showing the problem, maybe as (the smallest possible) diff to an existing sample, as otherwise it's really difficult to know what's going on.

I'm not sure what does this have to do with the dialog style to be honest.
