### ISSUE TITLE
menu  "Window" in parent form's menubar

### ISSUE THREAD

**Issue by Stormfinger** [wxWidgets/wxWidgets#22408]
**Describe the bug**
a menu "Window" appears in my applications barmenu but its not in code. when i run docView sample menu "Window" not there. Menu "Window" has some menu items that dont work.

**Expected vs observed behaviour**
I expect to hide this menu "Window" if i dont want to use it.

**Patch or snippet allowing to reproduce the problem**
Creating menubar in main window with wxAuiMDIParentForm

**Platform and version information**
 - wxWidgets version 3.1.7
 - wxWidgets port you use:  wxGTK,
 - OS and its version: debian bookworm with Mate
 - For wxGTK only:
   + GTK version: 3
   + Which GDK backend is used: X11

**Comment by vadz** [comment]
MDI parent frame always adds this "Window" menu, this is the expected behaviour and the menu commands do work for me in the docview sample.

If you don't want to have the "Window" menu at all, you probably shouldn't be using MDI at all. If you do want to use but its commands don't work for you, please provide a minimal patch to the docview sample allowing to reproduce the problem.
