### ISSUE TITLE
Which wxWidgets version will distribute new Corsican language?

### ISSUE THREAD

**Issue by Patriccollu** [wxWidgets/wxWidgets#22416]
Hello @vadz ,

When I added **Corsican** to *wxWidgets*, you commented the [following to the same question](https://github.com/wxWidgets/wxWidgets/pull/22276#issuecomment-1089191948):

> It will be included in the next wx release which should normally be 3.2.0. As for "when", this is a bit more delicate, currently we aim at releasing it on 2022-06-06 but our release dates have been known to slip in the past, so please take it with a grain of salt...

I just checked the [Milestones](https://github.com/wxWidgets/wxWidgets/milestones) and noticed that another version 3.1.7 is now planned before 3.2.0, so the previous plans could have changed. Additionally, this version 3.1.7 is scheduled to be released on 2022-06-06 whereas 3.2.0 is due by July 7<sup>th</sup>. Please can you clarify?

Is there a way to distribute Corsican with version 3.1.7? Or do we have to wait for version 3.2.0?

Best regards,
Patriccollu.

**Comment by vadz** [comment]
It will be included in 3.1.7, the plans have simple changed since then due to the amount of bugs that were found and fixed.

Also, please don't use the issue tracker for questions like this, we have mailing lists/forum/... for this and try to keep the issue tracker for the actual bugs only. Thanks for your understanding!
