### ISSUE TITLE
Dropdown button of wxOwnerDrawnComboBox looks enabled even though the box is disabled (wxGTK)

### ISSUE THREAD

**Issue by taler21** [wxWidgets/wxWidgets#22431]
With wxGTK, the default dropdown button of a `wxOwnerDrawnComboBox` is always displayed as if the box is enabled, even if it is disabled.
This is the case when using GTK2 as well as with GTK3.
It also makes no difference whether GDK backend X11 or Wayland is used.

It can also be seen in the combo sample.
1. Start the combo sample.
2. Click on 'File' > 'Compare against wxComboBox...'

Disabled `wxOwnerDrawnComboBox` of wxGTK using GTK2:
![disabled_odcb_GTK2_openSUSE](https://user-images.githubusercontent.com/99262969/168742223-ec95b988-f390-43eb-a885-ad244e722f4f.png)

Disabled `wxOwnerDrawnComboBox` of wxGTK using GTK3:
![disabled_odcb_GTK3_openSUSE](https://user-images.githubusercontent.com/99262969/168742263-346f0fd3-de20-4d66-8a1b-babef1fe08ae.png)

I am using wxWidgets-3.1.6.

**Comment by oneeyeman1** [comment]
Hi,
Which theme do you use?

Thank you.

**Comment by taler21** [comment]
I don't think it's a theme specific issue.

But for the record, I tested it with:
* openSUSE 42.3 (KDE desktop with 'Adwaita' theme for GTK2 and GTK3 applications)
* Ubuntu 16.04 (Unity desktop with standard theme 'Ambiance')
* Ubuntu 22.04 (GNOME desktop using Wayland)
* Linux Mint 19 (Cinnamon desktop with standard theme 'Mint-Y')

**Comment by vadz** [comment]
Thanks for reporting and this indeed has nothing to do with themes (@oneeyeman1 please avoid asking questions unless you have good reasons to believe the answers to your questions are needed, e.g. in this case if you don't see the problem with the default theme -- which is, of course, *not* the case here, as it's perfectly visible with the default theme too).

There is one obvious problem in the code, fixed in ed264087ec (Use flags for drawing arrow in wxGTK DrawComboBoxDropButton(), 2022-05-17), but this still doesn't fix the problem (at least for GTK 3, it might be enough for GTK 2 but I didn't bother to test it there). There is also a visually obvious problem of the arrow being quite different from the one used by the GTK 3 combobox.

I'm afraid both of those might be due to not using the new CSS-based rendering functions in `wxRendererGTK`, i.e. I think that we need to totally change its code to fix this and I unfortunately can't do this, at least not in the near future.

**Comment by taler21** [comment]
Thanks for looking at this.

I can confirm both:
Commit ed264087ec (Use flags for drawing arrow in wxGTK DrawComboBoxDropButton(), 2022-05-17)

1. fixes this issue for GTK2
   ![odcb_openSUSE_GTK2_fixed](https://user-images.githubusercontent.com/99262969/168963525-36514410-1624-45a1-adaa-ca0f4370ade9.png)

2. but doesn't change anything for GTK3
      ![odcb_openSUSE_GTK3](https://user-images.githubusercontent.com/99262969/168742263-346f0fd3-de20-4d66-8a1b-babef1fe08ae.png)

**Comment by paulcor** [comment]
Closed via 0b33e08dfe61c3ec3838bb10041c80294cc5ca2a
