### ISSUE TITLE
wxTextCtrl is not showing correctly on 3.1.7 Mac

### ISSUE THREAD

**Issue by BrutalSoloH** [wxWidgets/wxWidgets#22498]
**Description**
The default height and width are not correct with the wxTextCtrl on the Mac wx3.1.7. It still was good in 3.1.6.

Now it is showing too tall. Higher then the wxComboBox. Should be the same height.
Also when leaving the width to -1, it should at least be of some width when displaying (like 150px). Now it is showing like 8px width.

 - wxWidgets version you use: 3.1.7
 - wxWidgets port you use: wxOSX
 - OS and its version: macOS 15

**Comment by vadz** [comment]
Thanks for reporting this, if it's the same thing as mentioned in [this comment](https://github.com/wxWidgets/wxWidgets/issues/22374#issuecomment-1148506288) then it's definitely wrong.

@csomor I have no idea how to fix it otherwise than reverting dc2ff0d6b4 (wxOSX: Rewiring GetBestSize for single line text control again, 2022-04-30), which I'd rather not do, as it seems correct, but this must be fixed before 3.2.0 somehow. Would you have any idea about it please? TIA!

**Comment by csomor** [comment]
@vadz I am already looking at this

**Comment by csomor** [comment]
ok, I'm counting the bezel twice right now - the native best size of course already includes it and then it is added once again via `TEXTCTRL_BORDER_SIZE`, I'll try whether I can get rid of that `TEXTCTRL_BORDER_SIZE` at least for single lines. But I'll commit a quick fix now.

**Comment by whalley** [comment]
@csomor That fix helps, great work.

**Comment by vadz** [comment]
Closing as this seems to have been fixed, thanks Stefan!
