### ISSUE TITLE
Add Method to Disable Dark mode behavior on Mac

### ISSUE THREAD

**Issue by guzmanpaco** [wxWidgets/wxWidgets#22496]
On our project, we use wxChoice and wxGrid. We have requirements that these classes use the appearance they have on non-dark mode. WxChoice changes background and text color and wxGrid changes border color when Mac OS is on Dark Mode. On current documentation, there does not seem to be a way to force dark mode to be disabled. I checked and wxChoice's appearance cannot be altered. We would like to request if we can disable dark mode behavior in wxWidgets on Mac.

We found a workaround for it by using ../configure in Sierra and still building it on Monterey. Is this safe for future versions of wxWidgets? Will this cause issues that we are not aware of.

Thank you

**Comment by vadz** [comment]
Apparently it's possible to choose light or dark appearance for individual windows at macOS level, see https://developer.apple.com/documentation/appkit/nsappearancecustomization/choosing_a_specific_appearance_for_your_macos_app?language=objc but I'm not sure if we want to wrap this in wx API because I have no idea about how to do anything like this with wxGTK.

Of course, if you want to disable dark mode entirely, you can just set `NSRequiresAquaSystemAppearance` in your `Info.plist`.

**Comment by guzmanpaco** [comment]
OK. For now, we will consider this as a workaround for the issue. Thank you.

**Comment by vadz** [comment]
This is actually almost the same as #19185, so let's close this one.
