### ISSUE TITLE
`wxDC::DrawRoundedRectangle` broken in master: random radius

### ISSUE THREAD

**Issue by aardappel** [wxWidgets/wxWidgets#22493]
**Describe the bug**
I pass a radius of `3` to `wxDC::DrawRoundedRectangle` which has always worked fine in the 15 years I've used that API, but lately this draws seemingly random arcs on screen with very large radii.

**Expected vs observed behaviour**
See above.

All the round looking things in the screenshot below were produced by `wxDC::DrawRoundedRectangle` when passed 3 or similar small positive integer for radius.

![image](https://user-images.githubusercontent.com/4663648/172216029-cf73180c-13b9-4a81-859d-3749cb331795.png)

**To Reproduce**

Sorry, can't reduce this to a small sample.

- Clone and build https://github.com/aardappel/treesheets as per the included instructions.
- in `mywxtools.h` replace the call on line 14 of `DrawRectangle` with `DrawRoundedRectangle`.

**Platform and version information**
 - wxWidgets version you use: latest master
 - wxWidgets port you use: wxMSW
 - OS and its version: Windows 10 latest public release.

**Comment by vadz** [comment]
Thanks for reporting this, but it would be really great to be able to reproduce this in the drawing sample, which already uses this function -- do you see anything you're doing differently/specially?

The only thing I can think about right now is that this got broken by 4f9186f1a1 (Increase usable scrolling range in wxMSW by a factor of 10,000, 2022-04-30), but this would only explain it if this only happens when scrolling, which doesn't seem to be the case from the screenshot.

Also, when you say "lately", can you narrow it down further, i.e. what is the last version which is known to have worked for you? Could you please try running git-bisect to find the commit when it stopped if it's not the one above?

Thanks in advance!

**Comment by aardappel** [comment]
Sorry, don't have time to further narrow it down.

And yes, scrolling makes it.. worse. Without scrolling (first render) the radius seems wrong only in the X direction, and then when scrolling the `wxScrolledWindow` down it also happens in the Y direction.

**Comment by vadz** [comment]
If there is a problem/regression at all without scrolling, it must not be related to this commit, as it has no effect without scrolling, hence it must be something else.

It would be _really_ helpfully to know what was the last working version.

**Comment by aardappel** [comment]
Confirmed fixed on our end, thanks!

**Comment by Kochise** [comment]
Good, thanks everybody.
