### ISSUE TITLE
wxDynamicLibrary 

### ISSUE THREAD

**Issue by chris12342534** [wxWidgets/wxWidgets#22509]
**Describe the bug**
I updated my wxWidgets to version 3.1.6. I had a project working on 3.0.0 and now I am trying to run it in the newer version. The problem is for some reason my wxDynamicLibrary.LOAD() is failing to load the DLL file of wincap and I don't know whats the problem since i didn't change the code.

**Expected vs observed behaviour**

**Patch or snippet allowing to reproduce the problem**

**To Reproduce**
Steps to reproduce the behaviour, please make them as detailed as possible, e.g.

**Platform and version information**
wxWidgets version you use: 3.1.6
wxWidgets port you use:
OS and its version: Windows 120.2212.4170.0
For wxGTK only:
GTK version:
Which GDK backend is used:
If relevant, i.e. for appearance-related problems:

![Screenshot (15)](https://user-images.githubusercontent.com/105078299/172918111-dcaca342-ab13-4708-bc79-db9e040a6f96.png)
![Screenshot (16)](https://user-images.githubusercontent.com/105078299/172918114-a7745261-a4a4-4966-a3c0-b6b6ec9faa68.png)
.0.19042.867, Ubuntu 22.10, macOS 15]

**Comment by vadz** [comment]
"not a valid Win32 application" is a Win32 error which has nothing to do with wxWidgets. I'd start by checking that you don't have a bitness mismatch (i.e. are trying to load a 32-bit DLL into a 64-bit application or vice versa), but even if it isn't the case, you really ought to debug it using the normal Windows tools, e.g. use gflags to enable loader snaps.

But this is completely unrelated to wxWidgets and I'm 99.9% sure that the change is not due to upgrading to wx 3.1, but to some other change in your environment.
