### ISSUE TITLE
Segmentation fault on any dialog opening

### ISSUE THREAD

**Issue by ethanarns** [wxWidgets/wxWidgets#22523]
Anything from wxMessageDialog to wxFileDialog seg faults as soon as it tries to open. I've tried both the Apt repo version, as well as building both the stable and latest builds myself with a myriad of configurations. Running the debugger makes something about "/build/glibc-SzIz7B/glibc-2.31/sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S" pop up, but that's the most I could find about the error. Here is an example of the code that causes a segfault. I can provide full examples if necessary:
```
wxMessageDialog *dial = new wxMessageDialog(this,  wxT("Download completed"), wxT("Info"), wxOK);
```
```
    wxFileDialog* openFileDialog = new wxFileDialog(this, _("Open XYZ file"), "", "",
                       "XYZ files (*.xyz)|*.xyz", wxFD_OPEN|wxFD_FILE_MUST_EXIST);
```

**Platform and version information**
- Version from `wx-config --version-full`: 3.0.5.0 (the most recent one I tried)
- OS: Linux Mint 20.3 Cinnamon

**Comment by ethanarns** [comment]
Sorry, GCC version: `gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0`

**Comment by oneeyeman1** [comment]
Please get the latest release from wxwidgets.org download page, build it using --enable-debug and try to run the dialogs sample.

**Comment by vadz** [comment]
Sorry but I think that the problem must be due to a "myriad of configurations". Please make sure to build one, and only one, build of the library and the same headers and, of course, compiler and compiler options to build both the library and your application. Only mixing them up can result in "impossible" crashes like this -- the samples definitely don't crash when opening a dialog.

Sorry but we can't help you find the problem, only you can solve it by

1. Deleting all your existing wxWidgets headers/libraries.
2. Getting one, and only one version, and building using it.
