### ISSUE TITLE
wxLocale + Swedish + Linux not working

### ISSUE THREAD

**Issue by roenck** [wxWidgets/wxWidgets#22529]
OS: Ubuntu 20.04 Linux, Default-OS-Language 'German', 'Swedish' Language not installed on System
wxVersion: 3.1.7 + 3.1.5

wxLocale::IsAvailable(wxLANGUAGE_SWEDISH) fails within linux.

```
    nativeLanguage = wxLANGUAGE_SWEDISH;
    catalog = wxT("my_existing_catalog"); // note: lies under "resources/locale/sv/" within the app-directory

    if(wxLocale::IsAvailable(nativeLanguage))
    {
        m_locale = new wxLocale(nativeLanguage);
        m_locale->AddCatalogLookupPathPrefix(wxT("resources/locale"));
        m_locale->AddCatalog(catalog);
        ...
```

Same thing is working fine with Windows (at least 'wine'), means I can choose Swedish, catalog can be load and translation working perfectly.

Within Linux this fails before the 'app'-Catalog could be loaded.

**Comment by vadz** [comment]
Sorry, I don't understand: do you mean that `IsAvailable()` returns false when you do *not* have `sv_SE` (or some form thereof) in your `locale -a` output? If so, this would be the expected behaviour, so why are you surprised by this?

Note that you can still use translations even if a locale is not available, but you won't be able to e.g. format dates or numbers using this locale in this case.

**Comment by roenck** [comment]
Because it is working as Windows-Binary (Wine5 and a 'German'-only Windows 10).

My expected behaviour is, that on both Systems exactly the same should happen.

Take a look into the "Installed Languages" shows that only German (Germany) and English (United States) is installed.

**Comment by utelle** [comment]
> Because it is working as Windows-Binary (Wine5 and a 'German'-only Windows 10).

Under Windows 10 almost all locales are selectable. That is, it is not necessary to perform any special installation processes. I don't know how exactly Wine works internally, but most likely it mimicks the Windows behaviour.

> My expected behaviour is, that on both Systems (Windows and Linux) exactly the same should happen.

Your expectation is based on the false assumption that Windows and Linux behave identically in respect to locale and language support. They do **not**. On Linux systems you need to explicitly install all locales for which you want support. And as you said _Swedish_ is **not** installed on your Linux system. Therefore method `wxLocale::IsAvailable(wxLANGUAGE_SWEDISH)` will return _false_ on your Linux system, but _true_ on Windows 10 systems.

> Take a look into the "Installed Languages" (on Windows 10) shows that only German (Germany) and English (United States) is installed.

This is again a misunderstanding: support for additional UI languages has to be installed on Windows, but locales can usually be selected without installing anything. Method `wxLocale::IsAvailable(wxLANGUAGE_SWEDISH)` checks for the availability of the Swedish locale, **not** for the availability of Swedish UI language support.

The wxWidgets class `wxLocale` deals with the _locale_. Unfortunately, the support for loading translation catalogs is linked to a specific `wxLocale` instance. To remove this interdependency wxWidgets 3.1.6 introduced the new class `wxUILocale`. Loading of translation catalogs is not linked to a `wxUILocale` instance anymore. Instead translation catalogs can be loaded independently, even if the corresponding locale is not available on the system.

**Comment by vadz** [comment]
Yes, I don't think this bug report is valid. `wxLocale::IsAvailable()` checks if a locale is available (duh). It returns true under Windows 10 because Swedish locale is available there (this wasn't the case under e.g. Windows XP), and it returns false under Linux if it's not available. If this function always returned true under Linux, what would be the point of having it?

Again, it's perfectly fine to use `wxTranslations` to load Swedish translations no matter what. But you shouldn't use `IsAvailable()` if you're not really interested in knowing whether the locale is available.
