### ISSUE TITLE
wxLocale + wxLANGUAGE_DEFAULT not working with Linux

### ISSUE THREAD

**Issue by roenck** [wxWidgets/wxWidgets#22526]
OS: Ubuntu 20.04 Linux, Default-OS-Language 'German'
wxVersion: 3.1.7

wxLocale::IsAvailable(wxLANGUAGE_DEFAULT) not succeeds -> results into a fall back-handling that enables the build-in (EN) instead of expected DE

Same thing is working fine with Windows (at least 'wine') and is working with wx 3.1.5.

**Comment by vadz** [comment]
I can confirm that this fails even with C locale, thanks for reporting. Looking...

**Comment by vadz** [comment]
@utelle All the code for detecting the current language under Unix is now in `GetPreferredUILanguages()`, but this function is not called at all -- and apparently intentionally -- from `GetSystemLocale()`, so the latter basically always returns `wxLANGUAGE_UNKNOWN`. This can't be right, of course, but if I start calling `GetPreferredUILanguages()` from this function, it's going to be the same as `GetSystemLanguage()` while your intention was clearly to keep them different. So I'm very confused here and would be grateful for any explanations of how was this supposed to work. TIA!

**Comment by utelle** [comment]
> All the code for detecting the current language under Unix is now in `GetPreferredUILanguages()`, but this function is not called at all -- and apparently intentionally -- from `GetSystemLocale()`, so the latter basically always returns `wxLANGUAGE_UNKNOWN`. This can't be right, of course, but if I start calling `GetPreferredUILanguages()` from this function, it's going to be the same as `GetSystemLanguage()` while your intention was clearly to keep them different. So I'm very confused here and would be grateful for any explanations of how was this supposed to work. TIA!

There is a fundamental difference between the classes `wxLocale` and `wxUILocale`. Actually, the class `wxLocale` only deals with the system _**locale**_, while the class `wxUILocale` differentiates between the _**locale**_ and the _**UI language**_. Despite its name the method `wxLocale::GetSystemLanguage` refers to the system _**locale**_ and **not** the system _**UI language**_. Therefore this method calls `wxUILocale::GetSystemLocale`. Up to this point the implementation is correct.

Method `wxUILocale::GetSystemLocale` instantiates the system default locale and then queries its locale name. IMHO this approach is in principle correct - and AFAICT it works properly under Windows and macOS. The culprit is the implementation for Unix.

Method `wxUILocaleImpl::CreateUserDefault()` creates a default locale based on an _empty_ (**!**) `wxLocaleIdent` instance. Maybe you can remember our discussion about supporting an empty `wxLocaleIdent` for representing the default locale. In the end we decided against this option. That is, an empty `wxLocaleIdent` should be considered _invalid_. Nevertheless, under Unix the empty `wxLocaleIdent` works in this context, because the default locale is represented by an empty string. However, I don't think we need to change anything here.

In fact, the problem results from the behaviour of method `wxUILocaleImplUnix::GetLocaleId()`, because it returns simply the `wxLocaleIdent` which was passed in on creating the default locale instance. And in this case it is the _empty_ `wxLocaleIdent` which in turn results in `wxLANGUAGE_UNKNOWN`.

The implementations of `wxUILocaleImpl::GetLocaleId()` for Windows and macOS actually **query** the locale for the locale name. And IMHO the Unix implementation should do that, too. 

That is, changing the implementation of method `wxUILocaleImplUnix::GetLocaleId` in `src/unix/uilocale.cpp` from
```C++
wxLocaleIdent
wxUILocaleImplUnix::GetLocaleId() const
{
    return m_locId;
}
```

to

```C++
wxLocaleIdent
wxUILocaleImplUnix::GetLocaleId() const
{
    return wxLocaleIdent::FromTag(GetName());
}
```

should solve the issue.
