### ISSUE TITLE
SONAME incorrect on Haiku?

### ISSUE THREAD

**Issue by Begasus** [wxWidgets/wxWidgets#22658]
**Describe the problem**
Describe how exactly do you build wxWidgets, including the full `configure`
command line and/or `make` command line if relevant.

Our work for Haiku can be found here: https://github.com/haikuports/haikuports/pull/7062
Trying to update to 3.2.0 can be found here: https://github.com/haikuports/haikuports/pull/7063

Build is OK and seems to be fine (checked with a build for scummvm-tools).

As you can see in the new PR libVersion changes from 5.0.0 to 0.0.0
```diff
-libVersion="5.0.0"
+libVersion="0.0.0"
```
Asking if this intentional or if something is wrong here.

**Platform and version information**
 - wxWidgets version you use: [e.g. 3.2.0]
 - wxWidgets port you use: [e.g. wxGTK]
 - OS and its version: [e.g. Haiku 32bit nightly hrev56253]
 - Compiler being used: [e.g.  gcc 11.2.0]

[config.log.txt](https://github.com/wxWidgets/wxWidgets/files/9157564/config.log.txt)

**Comment by vadz** [comment]
I think this is fine because the name of the library itself has changed, it used to have "3.1" in it but now has "3.2" -- and, as it's a "new" library, it's normal for the soname to be reset. Or am I missing some problem here?

It would arguably be better to stop using the version as part of the library name and just use soname instead on Unix systems, so that we'd have just `libwx_gtk3u_core.so.N` instead of `libwx_gtk3u_core-3.2.so.0`, but this would require many changes and probably break something, so I don't think we're going to do it.

**Comment by Begasus** [comment]
For the 3.1 vs 3.2 I have been thinking of using a variable in the recipe so it takes that from the portVersion, eg:
`portVersionCompat="${libVersion%%.*}`
That should solve it for manually editing this in the recipe, so no worries there.
Point is, 3.1 had `libwx_gtk3u_core.so.5.0.0`, 3.2 has `libwx_gtk3u_core.so.0.0.0`
One would expect an increment version, something like `libwx_gtk3u_core.so.5.1.0` or the like?

**Comment by vadz** [comment]
This is weird because our libraries shouldn't be named like this, they should have names like `libwx_gtk3u_core-3.1.so` (in 3.1) and `libwx_gtk3u_core-3.2.so` (in 3.2).

Are you using unmodified wx sources?

**Comment by Begasus** [comment]
No patching has been done on the source for wxwidgets (the recipes have been mentioned above in the first comment).
Looking at the package contents from Arch I don't see a libversion as is shown with our port? (Indeed strange)

**Comment by vadz** [comment]
Alpine does `-3.0` in the name as expected and the soname is `0` (as in `0.5.0`), also is expected.

I really, really don't see how could this happen with unmodified sources. Please check `WXDLLVERSIONTAG` value in the `Makefile` generated by configure. It should have the value `-3.2` and be used as part of the library name.

**Comment by Begasus** [comment]
From what I can find:
```
WXDLLVERSIONTAG = -$(WX_RELEASE)
#WXDLLVERSIONTAG = 
```

**Comment by vadz** [comment]
Just to be totally clear, there are 2 _different_ things here:

1. The library base name being `libwx_gtk3u_core` instead of the expected `libwx_gtk3u_core-3.2` for you.
2. The soversion being `0` and not `5` or `6` as you expect.

The second point is, of course, due to 2a2308d5ed77c971b668629c866a691c7e4433ab, but it is normal and intentional *because* of the first one, i.e. the soversion was reset to 0 because the base name has changed. There is nothing surprising or unexpected about this.

The first point remains unexplained and it's the one I'm interested in. Unfortunately I simply have no idea how can it happen: `WXDLLVERSIONTAG` is part of the library names and so your libraries should contain it -- but somehow don't. Please try debugging this yourself, i.e. looking at makefile or just running `make -n` to see what's going on here. I can't reproduce this under Linux.

**Comment by vadz** [comment]
> For the 3.1 vs 3.2 I have been thinking of using a variable in the recipe so it takes that from the portVersion, eg: `portVersionCompat="${portVersion%%.*}` That should solve it for manually editing this in the recipe, so no worries there. Point is, 3.1 had `libwx_gtk3u_core.so.5.0.0`, 3.2 has `libwx_gtk3u_core.so.0.0.0`

Are you actually **sure** about these names? Because your comment is the only place where I see them, i.e. the names without `-3.x` in the basename. Could it be that you just made a typo here and the whole thing is a red herring?

**Comment by Begasus** [comment]
> > For the 3.1 vs 3.2 I have been thinking of using a variable in the recipe so it takes that from the portVersion, eg: `portVersionCompat="${portVersion%%.*}` That should solve it for manually editing this in the recipe, so no worries there. Point is, 3.1 had `libwx_gtk3u_core.so.5.0.0`, 3.2 has `libwx_gtk3u_core.so.0.0.0`
> 
> Are you actually **sure** about these names? Because your comment is the only place where I see them, i.e. the names without `-3.x` in the basename. Could it be that you just made a typo here and the whole thing is a red herring?

I probably made an typo there, library is called: `lib:libwx_gtk3u_core_3.2.so.0.0.0`

![wxgtk](https://user-images.githubusercontent.com/16057090/180650559-815290a8-81c3-4ad7-b330-db9379cb557c.png)

**Comment by Begasus** [comment]
> The second point is, of course, due to [2a2308d](https://github.com/wxWidgets/wxWidgets/commit/2a2308d5ed77c971b668629c866a691c7e4433ab), but it is normal and intentional _because_ of the first one, i.e. the soversion was reset to 0 because the base name has changed. There is nothing surprising or unexpected about this.

OK, didn't know about the reset, think this can be closed as invalid then. Thanks for taking the time to look into this, and sorry for taking your time.

**Comment by vadz** [comment]
Then everything is fine here and there is no problem at all, please see my very first comment in this issue.
