### ISSUE TITLE
wxConfigFile and HasGroup() char size

### ISSUE THREAD

**Issue by 0xtrzy** [wxWidgets/wxWidgets#22661]
I have trouble, how read group dependences Char size?

not i read "/test" and all version "/TesT" etc. return true

**Comment by vadz** [comment]
If I understand you correctly, this is about entry and group names being case-insensitive. If so, this is intentional, as `wxConfig` uses `.ini`-like format in which this was usually the case.

You can rebuild your own version of the library with `wxCONFIG_CASE_SENSITIVE=1`, but by default it's set to 0, meaning that the names are case-insensitive.
