### ISSUE TITLE
mac plist in 3.2.0

### ISSUE THREAD

**Issue by rppass** [wxWidgets/wxWidgets#22676]
I just upgraded to 3.2.0. After building my programs and trying to run them (clicking on the .app) I get a message that I cannot run the application because it is damaged or incomplete.

I have traced this to the Info.plist.in file distributed with 3.2.0.  If I revert that file back to one from 3.1.4 everything works as expected.

Not being a plist expert, I wonder if someone else can solve this problem (other than my sledge hammer approach)

**Comment by rppass** [comment]
Should have mentioned this is true on both Monterey and Catalina versions of OSX and on Intel cores.

**Comment by vadz** [comment]
How exactly do you use `src/osx/carbon/Info.plist.in`? The names of the variables used in it have changed since 81c4fa449b (Use CMake-compatible variable names in configure Info.plist files, 2021-08-15), so you may need to update your replacements.

As an aside, I never had any idea that people used this file in their projects, AFAIK it's supposed to only be used for wx itself.

**Comment by rppass** [comment]
I use Dialogblocks to build my apps.  In making the .app folder, it copies Info.plist.in to the Contents folder of the .app folder as Info.plist.  As far as I know, Dialogblocks has never modified the contents of Info.plist.in.

**Comment by rppass** [comment]
Okay, I see what you are saying now.  I will contact Dialogblocks.

Thank you

**Comment by vadz** [comment]
@JulianSmart please see the commit above for the changes you probably need to propagate to D::B. Sorry for breaking this but I really didn't think this file could be used outside of wx (and, to be honest, still don't know if it's a good idea to do it).

In any case, I don't think we can do anything about it in wx itself, so closing.
