### ISSUE TITLE
wx3.2.0: Documentation issue on web pages; missing leading "_" underscores in constants.

### ISSUE THREAD

**Issue by stahta01** [wxWidgets/wxWidgets#22671]
Compare webpages [3.0](https://docs.wxwidgets.org/3.0/page_cppconst.html) and
[3.2](https://docs.wxwidgets.org/3.2.0/page_cppconst.html).
The correct 3.0 shows `__WINDOWS__` ; but, the incorrect shows `WINDOWS`.
I am guessing an doxygen issue is the cause of the missing underlines.

Tim S.

**Comment by vadz** [comment]
Thanks for noticing this!

Looks like we need to escape all the underscores now and probably not just here, but in all the other places as well... Or does it only affect stuff inside `itemdef`?

**Comment by tierra** [comment]
Hah, new Doxygen seems to have added Markdown support, since it's clearly turning `__THING__` into __THING__

**Comment by tierra** [comment]
That probably has some implications all over the docs :/

**Comment by vadz** [comment]
According to [the docs](https://doxygen.nl/manual/markdown.html) Markdown support was already there in 1.8 that we used before, but apparently it didn't handle `__` before (due to a bug?).

Anyhow, it looks like there is no other choice but to escape all of them -- which is what I did now, see the commit above. If no problems are found with this, we'll need to backport it to 3.2 too later.
