### ISSUE TITLE
Bug in building 3.2.0

### ISSUE THREAD

**Issue by raananb** [wxWidgets/wxWidgets#22690]
When building 3.2.0 using Visual Studio 2022 Community using wx_vc17.sln, the libraries are created at D:\wxWidgets-3.2.0\lib\vc_64_lib\ while in previous versions (e.g. 3.1.6) the path was D:\wxWidgets-3.2.0\lib\vc_lib\
Visual studio projects would not build (missing stdio.h) until the library is renamed manually to vc_lib.
I have no idea what created the specific 64bits nale, but a word about this isuue would save a lot of time.

**Comment by vadz** [comment]
Sorry, this is totally unclear: have you built 32-bit or 64-bit version? The former uses `vc_lib`, the latter -- `vc_x64_lib`, same as it always did (note that you have a typo in your path).

In any case, "missing stdio.h" has nothing to do with wx.

Please explain what _exactly_ are you doing, what you expect to obtain and what happens if you still think there is a problem in wx, but to me this looks like just some confusion between your builds.
