### ISSUE TITLE
wxListCtrl menu not working Ctrl-M

### ISSUE THREAD

**Issue by sp00ck** [wxWidgets/wxWidgets#22700]
when I select a wxListCtrl menu not working ctrl-M
when i change to other combination all working ok

**Comment by oneeyeman1** [comment]
Hi,
What kind of menu is it?
Can this be seen in a listctrl sample?
Thank you.

**Comment by vadz** [comment]
Please always mention your platform and wxWidgets version when reporting issues.

In this particular case, I suspect you're using wxGTK where `Ctrl-M` is handled as `Enter` and activates the item in the control, i.e. it's another instance of the problem discussed in #22630 (which also provides some workarounds).

If it's something else, please provide more details.

**Comment by sp00ck** [comment]
yes linux wxgtk
i can use Ctrl-M before selected. Normaly all works, but when selected listCtrl i can use menu ctrl-M

**Comment by vadz** [comment]
Assuming you meant "can't use" at the end, yes, this makes sense, this is what the other bug is about -- in wxGTK the control gets the key first. If there is a selected item, it's activated by this key, otherwise it's passed on to the other windows and can be used as an accelerator.

I gave an example of working around this problem in #22625, you should be able to do something similar.

As there is nothing new/specific here, I'm closing this one, please subscribe to #22630 if you want to know when it is fixed.
