### ISSUE TITLE
error

### ISSUE THREAD

**Issue by aldoeri** [wxWidgets/wxWidgets#22742]
**Describe the problem**
Describe how exactly do you build wxWidgets, including the full `configure`
command line and/or `make` command line if relevant.

Please attach the full build log, but feel free to quote the relevant parts of
it here.

When using `configure`, please also attach `config.log` file.

**Platform and version information**
 - wxWidgets version you use: [e.g. 3.1.6]wxMSW-3.2.0
 - wxWidgets port you use: [e.g. wxMSW, wxGTK, wxOSX] wxMSW
 - OS and its version: [e.g. Windows 10.0.19042.867, Ubuntu 22.10, macOS 15]Microsoft Windows [Versión 10.0.19044.1889]
![error](https://user-images.githubusercontent.com/25265688/186803890-d2f7567e-abed-4f4a-a828-901039460e2b.jpg)

 - Compiler being used: [e.g. MSVS 2022, gcc 12.1]msys2-x86_64-20220603

**Comment by PBfordev** [comment]
What exactly is the issue here? Seems it is not wxWidgets issue but you are not using MSYS properly?

For starters: Did you actually set environment variable `wxwin`? Please notice the lowercase, this variable is usually named `WXWIN` and the variables are case-sensitive. You can check your environment variables with `printenv` command.

BTW, when you want to build wxWidgets, should you not use a shortcut set for the compiler toolchain (e.g., _MSYS2 MinGW x64_) instead of MSYS2 MSYS?

**Comment by vadz** [comment]
`$` in the instructions represents the shell prompt, you're not supposed to enter it directly.

Also, please copy and paste text, inside triple backticks to prevent it from being mangled (use "Preview" to check for how it's going to appear), instead of attaching images for textual information.
