### ISSUE TITLE
Incorrect purchase link on books page

### ISSUE THREAD

**Issue by eastman-bechamo** [wxWidgets/wxWidgets#22741]
Hi,

I was browsing [this](https://wxwidgets.org/docs/book/) page, and it seems like link to  "Safari Books Online"  might not be relevant anymore. It's under the "Where to Buy" header, and it appears in this paragraph:
> The wxWidgets book is available to be read online by subscribing to [Safari Books Online](https://www.safaribooksonline.com/).

Hope that helps!

**Comment by Randalphwa** [comment]
I clicked the link on the page which took me to the O'Reilly web site, where I then searched for wxWidgets and the first link was to the wxWidgets book. So it's not a direct link, but you can definitely get to the book from that link.

That said, it's no longer Safari Books Online, but it does take you to a subscription service where you can get the book the page is referring to.

**Comment by vadz** [comment]
@JulianSmart I wonder if you know of a better link to put there by chance?

**Comment by JulianSmart** [comment]
Perhaps:

https://www.oreilly.com/library/view/cross-platform-gui-programming/0131473816/

but that costs money whereas you can get it for free here:

https://ptgmedia.pearsoncmg.com/images/0131473816/downloads/0131473816_book.pdf

so maybe it would be better as a Google search e.g.

https://www.google.com/search?q=Cross-Platform+GUI+Programming+with+wxWidgets

which also finds the PDF, Amazon item, etc.

**Comment by vadz** [comment]
Is the PDF actually legally free/available? If so, could we just put it on the web site directly?

**Comment by JulianSmart** [comment]
Good question. It probably is freely redistributable, but it will be worth checking the licence.

**Comment by tierra** [comment]
As far as I can tell, it's actually been permitted to redistribute the PDF freely ever since it was initially available. I still think it was appropriate that the site has put in a good faith effort to link to commercial copies all these years. But it seems like it's a good idea to just host the PDF directly now though, available freely, especially since it's pretty difficult to find hard copies available for purchase now.

As part of the Bruce Perens' Open Source Series, all books in the series were released under the [Open Publication License v1.0](https://spdx.org/licenses/OPUBL-1.0.html). I see this referenced in the book.

The original author(s) or publisher had the option to elect a couple of specific restrictions with this license, though it doesn't look like the book ever did elect either of them, and even if it did, those restrictions only applied to:
1. "substantively modified versions", with the option to require explicit permission (which we'd have with @JulianSmart here anyway), but this wouldn't be modified anyway.
2. "publication of this work or derivative works in whole or in part in standard (paper) book form for commercial purposes", which wouldn't be the case here either, and again, can still be done with explicit permission.

There was an article published in 2003, with Bruce Perens talking about the series:
> "These are print books," Perens said. "Everything is treated exactly like any other print book at Prentice Hall. We pay people the same, we wholesale them the same, all the way through."
> 
> A few months after publication, however, the books go online in an open-source manner. "We don't think that most people read their books on the screen, so we don't see that as a tremendous revenue drain," Perens noted.

**Comment by tierra** [comment]
I went ahead and added the PDF copy to the website directly now:
https://github.com/wxWidgets/website/commit/fe76fdfd9665e77bf1c8ef5de8181cdf44793093
