### ISSUE TITLE
DrawEllipse and DrawCircle no longer protected against radius zero

### ISSUE THREAD

**Issue by rocrail** [wxWidgets/wxWidgets#22775]
Using wxWidgets 3.2 the DrawEllipse and DrawCircle will cause rendering problems in some other wxWindow parts of the GUI.
This is only a problem under Linux GTK3.
My program, www.rocrail.net, accepts user defined SVG's which could have malformed circle radius of zero.
A radius of zero cannot be renderred, but should not lead to invalidating the DC.
In wxWidgets 3.0 it seems to be catched in the underlying library, but with wxWidgets 3.2 it leads to very strange behaviour of other wxWidgets components.
Now I catch this zero radius circles in my application, and will reject them before bothering wxWidgets.

I do not know if this is a bug, but it is definitely a change in behaviour.

The macOS seems to reject radius zero by it self.

**Comment by vadz** [comment]
I think this was already fixed by Paul in 52eedc171c (Restore check for radius <= 0 when drawing ellipse with Cairo, 2022-09-05). I am not sure if negative radius should be allowed here in the first place, so we might want to assert that it isn't, but this change should be enough to fix the regression.
