### ISSUE TITLE
Why is My GUI look so old and with no colors

### ISSUE THREAD

**Issue by MacQuant** [wxWidgets/wxWidgets#22773]
Hello,

This is my first time using wxWidgets, I am running the [auidemo.cpp](https://github.com/wxWidgets/wxWidgets/blob/master/samples/aui/auidemo.cpp) but the result looks very old like if it's from the 90s, is there a way to make the gui a bit modern and colorful?

Thanks!!

**Comment by vadz** [comment]
AUI supports custom themes that can be used to customize its appearance to an extent, but otherwise it is what it is and I don't think it's worth keeping open an issue like this.

Please consider posting to the forum or mailing lists if you have things you'd like to discuss, this issue tracker is really supposed to be used for concrete problems.

**Comment by MacQuant** [comment]
@vadz sure, sorry!
