### ISSUE TITLE
wrong character set when wxWebView IE backend renders an HTML page

### ISSUE THREAD

**Issue by Rezakarimi66** [wxWidgets/wxWidgets#22786]
I am using wxWebView to show my webpage. I am using the IE backend and after setting the page content I see that IE cannot correctly render the characters although I have set the `meta` tag. However if I load the same page with `LoadURL`, it works fine.

![image](https://user-images.githubusercontent.com/5058070/189428424-763163d2-4791-4990-9b78-a06371fc0a6f.png)

To Reproduce:
```
// ----------------------------------------------------------------------------
// headers
// ----------------------------------------------------------------------------

// For compilers that support precompilation, includes "wx/wx.h".
#include "wx/wxprec.h"

// for all others, include the necessary headers (this file is usually all you
// need because it includes almost all "standard" wxWidgets headers)
#ifndef WX_PRECOMP
    #include "wx/wx.h"
#endif

// ----------------------------------------------------------------------------
// resources
// ----------------------------------------------------------------------------
#if wxUSE_WEBVIEW_IE
    #include <wx/msw/webview_ie.h>
#endif
#include <wx/webview.h>

// Define a new application type, each program should derive a class from wxApp
class MyApp : public wxApp
{
public:
    // override base class virtuals
    // ----------------------------

    // this one is called on application startup and is a good place for the app
    // initialization (doing it here and not in the ctor allows to have an error
    // return: if OnInit() returns false, the application terminates)
    virtual bool OnInit() wxOVERRIDE;
};

// Define a new frame type: this is going to be our main frame
class MyFrame : public wxFrame, public wxBitmap
{
public:
    // ctor(s)
    MyFrame(const wxString& title);
    wxWebView* myWeb = nullptr;
};

// Create a new application object: this macro will allow wxWidgets to create
// the application object during program execution (it's better than using a
// static object for many reasons) and also implements the accessor function
// wxGetApp() which will return the reference of the right type (i.e. MyApp and
// not wxApp)
wxIMPLEMENT_APP(MyApp);

// ============================================================================
// implementation
// ============================================================================

// ----------------------------------------------------------------------------
// the application class
// ----------------------------------------------------------------------------

// 'Main program' equivalent: the program execution "starts" here
bool MyApp::OnInit()
{
    // call the base class initialization method, currently it only parses a
    // few common command-line options but it could be do more in the future
    if ( !wxApp::OnInit() )
        return false;

    // create the main application window
    MyFrame *frame = new MyFrame("Minimal wxWidgets App");
    
    // and show it (the frames, unlike simple controls, are not shown when
    // created initially)
    frame->Show(true);

    // success: wxApp::OnRun() will be called which will enter the main message
    // loop and the application will run. If we returned false here, the
    // application would exit immediately.
    return true;
}

// ----------------------------------------------------------------------------
// main frame
// ----------------------------------------------------------------------------

// frame constructor
MyFrame::MyFrame(const wxString& title)
       : wxFrame(NULL, wxID_ANY, title)
{
    myWeb = wxWebView::New( this, wxID_ANY, wxWebViewDefaultURLStr );
    std::string html = "<!DOCTYPE html><html><head><meta http-equiv='content-type' content='text/html;"
        "charset=UTF-8'>\n<meta name='viewport' content='width=device-width,initial-scale=1.0'>"
        "</head><body>"
        "<h1>This is a test. Böäüßthke </h1>";
    if( myWeb && !myWeb->IsBusy() )
        myWeb->SetPage( html, "" );
}
```

 - wxWidgets version you use: 3.1.5
 - OS and its version: Windows 10

**Comment by PBfordev** [comment]
Reza, I believe you are aware this GitHub Issues are for wxWidgets development only (see the issue templates) and not for helping users with problems in their code: Use wx-user mailing list, wxForum, Stack Overflow etc. 

My educated guess is you once again have a bug in your code, probably messing up character encoding when converting from `std::string` to `wxString`. `wxString` has no idea that the character array your are passing to it is in UTF-8 (it expects the current locale encoding), you should use its `FromUTF8()` method instead here. It is also possible that you have incorrectly set source/execution charset in MSVC and the `std::string` (why even use it here?) is already mangled. IMO, using anything but 7-bit ASCII directly in the source is not the best idea and can be rather unportable and a source of bugs.

**Comment by Rezakarimi66** [comment]
@PBfordev, Thank you a lot for your answer. I don't have so much experience with character encodings but I am wondering why the same code works when using `LoadURL` instead of `SetPage`. Also what's the use of `meta` tag in the header of html file in this case?
I also know that the issue section is not for questions and bugs of users. I thought that this is a bug in wxWebview. I always ask my questions in SO and indeed I don't really get any correct answer except "What version are you using?" or "Please upgrade to the latest version" or "why do you want to do this" and so on. The community support for C++ is not good and for the libraries written in C++ is worse. I know that this is not a commercial library but that would be good to spend some time to answer users' question on SO.

**Comment by vadz** [comment]
You could at least check the bytes contained in your string before reporting this bug.

Anyhow, there is indeed no bug here and the real answer has already been provided by @PBfordev (thanks!), so closing.

**Comment by PBfordev** [comment]
> I am wondering why the same code works when using `LoadURL` instead of `SetPage`. 

There is no character conversion between `wxString` and the html source involved, so no space for character encoding bug (as long as the url itself is encoded correctly).

> Also what's the use of `meta` tag in the header of html file in this case? 

The tag was correct, the bug was that you did not pass UTF-8 encoded html.

> I also know that the issue section is not for questions and bugs of users.

So stop abusing it as such, I will not answer any questions like that anymore and TBH, I hope any such issues will be closed immediately as invalid and repeated offenders prohibited from creating them and needlessly adding noise.

> I thought that this is a bug in wxWebview. 

No idea what made you think so, while no code is bugless, such an obvious bug would be found and hopefully fixed fast. Moreover, if you spent few minutes debugging the issue, I believe you would have found the bug yourself, just inspecting the content of the strings in the Watch would tell you. MSVS even warns about the source character representation when building.

> I always ask my questions in SO and indeed I don't really get any correct answer except "What version are you using?" or "Please upgrade to the latest version" or "why do you want to do this" and so on. The community support for C++ is not good and for the libraries written in C++ is worse. I know that this is not a commercial library but that would be good to spend some time to answer users' question on SO.

Even if you do not like the questions, they are very relevant and important, people do not ask them just to annoy you. Moreover, trying with the latest wxWidgets version is easy and simple, particularly on Windows. If you do not like SO (I am not a fan of the interface myself), I still gave you two other alternatives for user issues.

**Comment by Rezakarimi66** [comment]
@PBfordev I really appreciate your nice helps and the valuable time that you spend answering other peoples questions. However I do not like the attitude that some pro developers have towards junior developers. Junior developers does not create noises! They are trying to understand and learn more. The question that may seem silly to you, has a lot of learning stuff for developers like me. If you don't have time for answering those, just ignore it and close the issue like a lot of pro devs.
Anyway I don't ask any question or any bug reports here. Have a nice day.

**Comment by PBfordev** [comment]
> @PBfordev I really appreciate your nice helps and the valuable time that you spend answering other people questions. However I do not like the attitude that some pro developers have towards junior developers. 

I have no idea what are you talking about: I am not a pro developer nor am I even a programmer (nor am I part of the wxWidgets developer team)? I am just a user like you except I have lower-intermediate understanding of C++, MS Windows, and wxWidgets and I am also dumb enough to spend time and effort on a stranger, expecting nothing in return except the basic human courtesy. If you do not like something, you are entitled to your feelings, but please realize that having your feelings hurt does not make you entitled to break the basic community rules.

>Junior developers do not create noises! 

I do not care if you are a junior or senior developer. Just abide the rules, be polite and aware of your lack of ability (which generally makes you much more likely to create a bug than discover a bug in others code). When your mistakes are pointed out, be thankful for the help, and do not act as if you were actually owed something. GitHub Issues are very obviously not a place for learning. Polluting GitHub Issues with reporting bugs in the user code (if you thought it was an actual issue, you would have used a template), even after being politely asked not to, cannot be described as anything but selfish and rude. Can you imagine how useless the Issues would become if everyone did that and made the noise/signal ratio unbearably high?

I myself have unfortunately created non-negligible amount of noise in wxWidgets due to my lack of ability and sloppiness, not only embarrassing myself but more importantly wasting the precious time of the very (perhaps overly) patient developers. However, I am humble enough to realize that, apologize, and hope that the net sum of my actions here is positive.

**Comment by Rezakarimi66** [comment]
Hi @PBfordev. As I said previously, I always appreciate your nice helps and other developers here and I know that you spend your valuable time to help others. That's a great attitude. If I said something that annoys you I sincerely apologize. 
The main point that I wanted to say is that I didn't want to create noise here. I really thought that this is a bug of wxWidgets. That's it. I think now I am creating noises 😄
