### ISSUE TITLE
protocol\ftp.h doesn't compile (and needs object.h)

### ISSUE THREAD

**Issue by 98SMMB** [wxWidgets/wxWidgets#22791]
When building an application using Visual Studio I get errors like these where I've used protocol\ftp.h:

...\wx\sckaddr.h(30,1): error C2504: 'wxObject': base class undefined
...\wx\sckaddr.h(67,44): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
...\wx\sckaddr.h(67,44): warning C4183: 'wxDECLARE_ABSTRACT_CLASS': missing return type; assumed to be a member function returning 'int'

However, if I inlcude wx\object.h before wx\protocol\ftp.h it compiles fine.

**Platform and version information**
 - wxWidgets 3.2.0
 - Windows Version	10.0.19044 Build 19044

**Comment by PBfordev** [comment]
The first wxWidgets header included (the precompiled header aside) should always be `<wx/wx.h>`. Are you properly including it?

**Comment by imciner2** [comment]
> The first wxWidgets header included (the precompiled header aside) should always be `<wx/wx.h>`.

In my opinion, this should not have to be the case. Forcing the inclusion of the main wx header will then force all the other headers into the compilation unit, and can drastically increase the compile times. This is especially problematic if the types have to be used in header files and can't be forward declared, meaning the header has to also be included.

**Comment by PBfordev** [comment]
> > The first wxWidgets header included (the precompiled header aside) should always be `<wx/wx.h>`.
> 
> In my opinion, this should not have to be the case. Forcing the inclusion of the main wx header will then force all the other headers into the compilation unit, and can drastically increase the compile times. 

While I agree that the situation may not be ideal: Did you really observe "drastically increased compile times" due to unnecessarily including `<wx/wx.h>`?

I have not, but my experience is limited and only to Windows and (mostly) MSVC. I think in the era where on one hand we have precompiled headers and very fast computers and on the other heavily templatized code and humongous header-only "libraries" really increasing compilation times, the real-world cost of including `<wx/wx.h>` may be negligible.

Nevertheless, in this very case the situation could perhaps be fixed simply be removing `#include "wx/sckaddr.h"` from _protocol/ftp.h_. _protocol/ftp.h_ first include would then be _protocol.h_ which includes _object.h_ and also _socket.h_ which then includes _sckaddr.h_. But I may be missing something here, would not be the first time.

**Comment by vadz** [comment]
I'd just like to say that there is no requirement to always include `wx/wx.h` and that personally I consider it an anti-pattern. I do think each public header should be self-contained and shouldn't result in an error if it's included on its own directly, so Paul's fix is the right thing to do, thanks.

In fact, I think it would be nice to have a separate CI check verifying that compiling all the public headers works and I'm going to see if I can add something like this quickly.
