### ISSUE TITLE
makefile.gcc is possibly corrupt

### ISSUE THREAD

**Issue by FDMuir** [wxWidgets/wxWidgets#22802]
On a Windows 10  64-bit platform, I attempt to build a 64-bit widgets library, using GCC 8.1, using  the following command:
mingw32-make.exe -f makefile.gcc -j3 CFG=x64 BUILD=Release >out10 2>err10.  Both SHARED and MONOLITHIC are set to 1 in config.gcc

The build ends with a library containing 7 A-Format subroutines and a RSP file named wxmsw32u_gcc_custom.dll.rsp.  There should be two DLL files named wxmsw32u_gcc_custom.dll and wxmsw32u_gl_custom.dll.

This behavior occurs for any number of mingw32-make.exe executables. wxWidgets-3.2.0 and wxWidgets-3.2.1 are both exhibiting this behavior. Never had this problem with previous releases of wxWidgets.

**Comment by vadz** [comment]
Did you see

> NOTE: For parallel builds, i.e. using -jN make option, please run mingw32-make -jN ... setup_h first and then rerun the full make command without setup_h at the end to work around a bug in the current makefiles.

in [the manual](https://docs.wxwidgets.org/3.2.1/plat_msw_install.html)?

I suspect your build fails due to a race condition in this makefile with `-j`, but it's really difficult to be sure because you don't show the contents of your `out10` and `err10` files, which would be rather useful for diagnosing the problem.

**Comment by PBfordev** [comment]
> ... Both SHARED and MONOLITHIC are set to 1 in config.gcc

This is a IMO a bad choice, as both these settings can be easily altered from a build command line. Did you try building without modifying any wxWidgets files (and also with default build settings) and if so, with what results?

The official binaries available for download were built with MinGW using GCC 8.1 in both 32- and 64-bits with the makefile, apparently with no problems. wxWidgets AppVeyor CI builds the library with makefile using MinGW with ancient GCC 5.3. I build wxWidgets with makefile and MinGW all the time (although using recent 64-bit MinGW/GCC versions), never observed any such issue.

I have also just tried to make a clean build of unmodified wxWidgets 3.2.1 source with mingw-64 `i686-8.1.0-posix-sjlj-rt_v6-rev0` installation using the standard procedure, i.e.:
```
PATH=C:\Program Files (x86)\mingw-w64\i686-8.1.0-posix-sjlj-rt_v6-rev0\mingw32\bin;%PATH%

mingw32-make -f makefile.gcc setup_h SHARED=1 MONOLITHIC=1 BUILD=release SHELL=cmd.exe
mingw32-make -j2 -f makefile.gcc SHARED=1 MONOLITHIC=1 BUILD=release SHELL=cmd.exe
```
with no problems whatsoever.


To conclude, the issue is very likely with your setup. Did you not also [write on C::B forums](https://forums.codeblocks.org/index.php/topic,25107.msg171154.html#msg171154) "I am unable to build **any GNU/GCC libraries** on a 64-bit Windows 10 platform."?

**Comment by FDMuir** [comment]
I used ‘setup_h’ in my commands using parallel processes.  I also had to issue the command twice before any processes started. Made me doubt id ‘setup_h’ was still in effect.

Yes, I created that topic on C::B forums. I’ll close it.               

It looks like all my failures to build wxWidgets where caused by my setup. I replaced Mingw64 with Mingw64 x86_x64-8.1.0-release-win32-seh-rt_v6-rev0. The online installer at Sourceforge still isn’t working correctly

I ran the command “mingw32-make.exe -f makefile.gcc CFG=x64 BUILD=Release >out10 2>err10”, after removing -j3, in a developer’s command prompt window.  I got the library I expected. I am currently running that command again after removing BUILD=Release. I expect to get the normal library.  I’ll try parallel processes later.

My apologies for submitting an erroneous complaint.
