### ISSUE TITLE
Compiler error with wxString::ToLongLong()

### ISSUE THREAD

**Issue by beENABLED** [wxWidgets/wxWidgets#22808]
wx 3.2.1, 32bit build with VS 2017

```
wxString size_s = "1000202273280";
wxLongLong size_ll;
size_s.ToLongLong( &size_ll );
```

Error E0167	argument of type "wxLongLong *" is incompatible with parameter of type "long long *"
Error	C2664	'bool wxString::ToLongLong(__int64 *,int) const': cannot convert argument 1 from 'wxLongLong *' to '__int64 *'

Analysis:
Looking into longlong.h :

wxLongLong_t is defined as __int64
wxUSE_LONGLONG_WX is not set

Therefore the following #if is false:
`#if (defined(wxUSE_LONGLONG_WX) && wxUSE_LONGLONG_WX) || !defined(wxLongLong_t)`

and this is used instead:
```
// if nothing is defined, use native implementation by default, of course
#ifndef wxUSE_LONGLONG_NATIVE
    #define wxUSE_LONGLONG_NATIVE 1
#endif
```

I think there are two issues here:
1) Why is wxString::ToLongLong() declared with wxLongLong_t as parameter (insted of wxLongLong)
2) Why is the native wxLongLong implementation used in my setup?

**Comment by vadz** [comment]
First of all, there is really no point in using `wxLongLong` nowadays (and I mean, like since 10 or 15 years), you should just use `long long` or `std::int64_t` directly.

And I don't see any bug here, but to answer your questions:

1. This is the way it is, always was and it's not going to be changed, and what's the problem with it? I.e. you get a compiler error because you pass the wrong type, the solution is to pass the correct one.
2. Because it's the default and the only thing which makes sense, `wxLongLongWX` was last useful back in 16-bit Windows days or something like this.
