### ISSUE TITLE
wxWidgets 3.2.1 (Ubuntu 20.04) too strict asserts in wxGenericImageList.

### ISSUE THREAD

**Issue by alysogorov** [wxWidgets/wxWidgets#22945]
Hi all!
Here is ubuntu 20.04. I've built wxWidgets 3.2.1 from sources(GTK3), with default build options. and I 've got dozens of assert messages at application start, kinda this - 
```
ASSERT INFO:
../src/generic/imaglist.cpp(231): assert ""m_size != wxSize(0, 0)"" failed in GetSize(): Invalid image list

BACKTRACE:
[1] wxGenericImageList::GetSize(int, int&, int&) const
[2] wxGenericTreeItem::DoCalculateSize(wxGenericTreeCtrl*, wxDC&, bool)
[3] wxGenericTreeItem::CalculateSize(wxGenericTreeCtrl*)
[4] wxGenericTreeCtrl::SetItemImage(wxTreeItemId const&, int, wxTreeItemIcon)
[5] wxEntry(int&, wchar_t**)
[6] __libc_start_main
```

i look at sources and 've found this check - 
file .../src/generic/imagelist.cpp
```
bool wxGenericImageList::GetSize( int WXUNUSED(index), int &width, int &height ) const
{
    width = m_size.x;
    height = m_size.y;
    wxCHECK_MSG( m_size != wxSize(0, 0), false, "Invalid image list" );
    return true;
}

```
also there are reported asserts 
```
ASSERT INFO:
../src/generic/imaglist.cpp(56): assert "m_size != wxSize(0, 0)" failed in GetImageCount(): Invalid image list

BACKTRACE:
[1] wxGenericImageList::GetImageCount() const
[2] wxGenericTreeCtrl::CalculateLineHeight()
[3] wxGenericTreeCtrl::SetImageList(wxImageList*)
[4] wxEntry(int&, wchar_t**)
[5] __libc_start_main
```

from function
```
int wxGenericImageList::GetImageCount() const
{
    wxASSERT_MSG( m_size != wxSize(0, 0), "Invalid image list" );
    return static_cast<int>(m_images.size());
}
```

looks like it asserts getting size and image count of empty list.
and this asserts look as too strict precondition, imho. 
i'll comment assertion to get rid of that, but seem it should be corrected by developers.
Thanks.

**Comment by oneeyeman1** [comment]
@alysogorov is there a reason why you are creating empty image list?

**Comment by alysogorov** [comment]
> 
1. an empty list is a legal object, imageCount of an empty list is 0.
2. It's not me. It looks like some initialisations(kinda default constructors) inside wxWIdgets. and seem is somehow connected with  current Gtk3 theme.

**Comment by alysogorov** [comment]
uups. I have a correction. GetCount does not break the assert. It was my fault.
In my case only GetSize is reporting an issue!!!
Thanks.

**Comment by PBfordev** [comment]
> an empty list is a legal object, imageCount of an empty list is 0.

IMO, the assert is entirely correct.

The issue is not that the list is empty, the issue is that the list somehow got created with an image width and height of 0. The image list does not have any method to change the image size and therefore creating such a list must be a bug the programmer should be notified about. 

The check to the generic version was [added](https://github.com/wxWidgets/wxWidgets/commit/4b7ca0b33d40eb4ee509a4220c42f15cfa849ab3) to match the already used check in the native MSW version.

My guess would be that you somewhere (backtrace should tell you where) create a list with 0 image size, ignore the assert from the `Add()` method and relied on the undocumented behaviour of the generic version of the image list, which allowed adding a image to the invalid list (setting the list image size from the firstly added image).

**Comment by alysogorov** [comment]
> The issue is not that the list is empty, the issue is that the list somehow got created with an image width and height of 0.

Yes. I've found my code place, bringing the assert in this version of wxWidgets.

```
/// wxImageList _images; /// <- gives assert because has not sizes
wxImageList _images{16,16}; /// <- all is correct if sizes given
...
_images.Add(*Icons::getFolderIcon16()); ///added some icon
this->SetImageList(&_images); ///assigned to wxTreeControl 
```
Problem solved, the issue can be closed

**Comment by alysogorov** [comment]
issue closed
