### ISSUE TITLE
wxListCtrl can grow extremely wide when moving between displays

### ISSUE THREAD

**Issue by PBfordev** [wxWidgets/wxWidgets#23091]
When I have a `wxListCtrl` in report mode with a long text in columns and columns width set to ` wxLIST_AUTOSIZE`, it is initially displayed in reasonable size, having scrollbars. However when I try to move the window from primary screen to the secondary one (primary screen has the higher resolution and DPI), once the window moves over half to the secondary screen, the control and the whole frame grow extremely wide so that the content can fit columns, covering almost both screens.

It happens also when `wxListCtrl` is not the sole child of a `wxFrame` but is several levels deep in the sizer hierarchy.

This does not happen with 3.2.1 but I noticed that the frame always grows a bit there when moving to the secondary screen and therefore after moving it between the screens a couple of times, the window size ends being MUCH bigger too.

To Reproduce:
1. Run the patched minimal sample.
2. Attempt to move the frame from primary to secondary screen.
3. Once the frame is over half on the secondary screen, observe the size change.

Minimal sample patch
```diff
diff --git a/samples/minimal/minimal.cpp b/samples/minimal/minimal.cpp
index 501caf9096..d950ce629f 100644
--- a/samples/minimal/minimal.cpp
+++ b/samples/minimal/minimal.cpp
@@ -26,6 +26,8 @@
     #include "wx/wx.h"
 #endif
 
+#include "wx/listctrl.h"
+
 // ----------------------------------------------------------------------------
 // resources
 // ----------------------------------------------------------------------------
@@ -175,6 +177,17 @@ MyFrame::MyFrame(const wxString& title)
     CreateStatusBar(2);
     SetStatusText("Welcome to wxWidgets!");
 #endif // wxUSE_STATUSBAR
+
+    auto longText = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque nec magna at nulla tempor pellentesque. Cras felis lorem, sodales vel sagittis et, vulputate nec sem";
+
+    wxListCtrl* listCtrl = new wxListCtrl(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxLC_REPORT);
+
+    listCtrl->AppendColumn("Item");
+    listCtrl->AppendColumn("SubItem");
+    listCtrl->InsertItem(0, longText);
+    listCtrl->SetItem(0, 1, longText);
+    listCtrl->SetColumnWidth(0, wxLIST_AUTOSIZE);
+    listCtrl->SetColumnWidth(1, wxLIST_AUTOSIZE);
 }

```

### Platform and version information

- wxWidgets version: GIT master
- wxWidgets port you use: wxMSW
- OS and its version: Windows 10 21H2, OS build 19045.2364, Windows Feature Experience Pack 120.2212.4190.0
- Other: [displays:](https://raw.githubusercontent.com/PBfordev/wxsysinfoframe/master/screenshots/displays.png) DPI scaling 125% on the primary (2560x1440) and 100% on the secondary (1680x1050) display.

**Comment by vadz** [comment]
Thanks, I do see this, but this is "just" due to the wrong implementation of `wxListCtrlBase::DoGetBestClientSize()` which simply adds up the column widths together, resulting in too big size if we allocate as much as it wants to it.

The trouble is that there is really no "best" size for `wxListCtrl` (or `wxTextCtrl` and many other controls) but there clearly is "best", and also "minimal" size, for many other controls, such as `wxButton`. And b66e63e217 (Fix windows becoming smaller than best size on DPI change, 2022-06-24) is correct for the latter ones, but not for the former. And in principle we already have `GetMinSize()`, but we use `GetBestSize()` in many places where we really need the min size. 

I guess we should use `GetMinSize()` in `wxNonOwnedWindow::HandleDPIChange()` and also in `wxTopLevelWindowBase` (see the recent bcb9c19358 (Improve GetBestSize() for TLWs containing a single child, 2022-12-14)) as I don't see any other solution for this problem.

@MaartenBent would you have any comments, as I think you've also looked into this in the past?

**Comment by vadz** [comment]
Unfortunately doing
```diff
diff --git a/src/msw/nonownedwnd.cpp b/src/msw/nonownedwnd.cpp
index bc2d121ff2..a923a996a1 100644
--- a/src/msw/nonownedwnd.cpp
+++ b/src/msw/nonownedwnd.cpp
@@ -290,7 +290,7 @@ bool wxNonOwnedWindow::HandleDPIChange(const wxSize& newDPI, const wxRect& newRe
         // size is usually a decent guess, it's typically not exactly correct.
         // We can't always do much better, but at least ensure that the window
         // is still big enough to show its contents.
-        wxSize diff = GetBestSize() - newRect.GetSize();
+        wxSize diff = GetMinSize() - newRect.GetSize();
         diff.IncTo(wxSize(0, 0));
 
         // Use wxRect::Inflate() to ensure that the center of the (possibly)
```
re-breaks #18649 because this just makes `diff` always 0 as the min size is updated by scaling it by DPI in `wxWindow::MSWUpdateOnDPIChange()`.

So I've had to restrict this min size update to the windows using sizers only in #23134. This is not universal but seems to be the best we can do and I think that in practice most windows will either use sizers or should be fine with just rescaling their size, i.e. the latter only creates problems for the windows with non-trivial layouts that should be using sizers.

**Comment by PBfordev** [comment]
@vadz, I am afraid that this may not be fixed when the control is in a sizer and set to expand as much as it wants. The example before did not use sizers (for simplicity sake). ` wxGrid` seems to be affected as well (even worse, the frame just disappears when moving between screens, it is only in the taskbar). I did not try other "greedy" controls.

To reproduce with the minimal sample:
```diff
diff --git a/samples/minimal/minimal.cpp b/samples/minimal/minimal.cpp
index 5f32257c6b..d00f1fe730 100644
--- a/samples/minimal/minimal.cpp
+++ b/samples/minimal/minimal.cpp
@@ -26,6 +26,9 @@
     #include "wx/wx.h"
 #endif
 
+#include "wx/listctrl.h"
+#include "wx/grid.h"
+
 // ----------------------------------------------------------------------------
 // resources
 // ----------------------------------------------------------------------------
@@ -175,6 +178,28 @@ MyFrame::MyFrame(const wxString& title)
     CreateStatusBar(2);
     SetStatusText("Welcome to wxWidgets!");
 #endif // wxUSE_STATUSBAR
+
+    wxBoxSizer* mainSizer = new wxBoxSizer(wxVERTICAL);
+
+#if 1
+    auto longText = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque nec magna at nulla tempor pellentesque. Cras felis lorem, sodales vel sagittis et, vulputate nec sem";
+
+    wxListCtrl* listCtrl = new wxListCtrl(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxLC_REPORT);
+
+    listCtrl->AppendColumn("Item");
+    listCtrl->AppendColumn("SubItem");
+    listCtrl->InsertItem(0, longText);
+    listCtrl->SetItem(0, 1, longText);
+    listCtrl->SetColumnWidth(0, wxLIST_AUTOSIZE);
+    listCtrl->SetColumnWidth(1, wxLIST_AUTOSIZE);
+    mainSizer->Add(listCtrl, wxSizerFlags(1).Expand());
+#else
+    wxGrid* grid = new wxGrid(this, wxID_ANY);
+
+    grid->CreateGrid(100, 100);
+    mainSizer->Add(grid, wxSizerFlags(1).Expand());
+#endif
+    SetSizer(mainSizer);
 }
```

**Comment by MaartenBent** [comment]
Similar cause as #23404. It uses `GetBestSize()` as minimum size.
