### ISSUE TITLE
[wxMSW] Dark-Mode: fix wxStaticBox border drawing

### ISSUE THREAD

**Issue by eranif** [wxWidgets/wxWidgets#23107]
When using dark mode enabled under MSW, the static box is drawn with high contrast colour (white over very dark background)
other controls are using grey-ish border.

I tried various approaches and eventually, I ended up using custom drawing the border when dark mode is enabeld.
Attached is the patch and screenshots of differences (before/after)

**NOTE**:
The PNG format reduces the colour quality a bit (I am not sure why). on my monitor, with high DPI the "shiny" version is a bit more noticeable than what is reflected in the images

Before:
![static-box-shiny](https://user-images.githubusercontent.com/3677711/210184504-47b03cda-0be2-4b82-bc73-133c0df49516.png)

After:
![static-box-grey](https://user-images.githubusercontent.com/3677711/210184506-b78d7083-731d-4e3e-b2a9-8f88585e286e.png)

Patch:
[statbox.patch](https://github.com/wxWidgets/wxWidgets/files/10329454/statbox.patch)

Hopefully you will accept this change
Thanks for your hard work!

**Comment by vadz** [comment]
I'd really like a second (or maybe third) opinion here because it doesn't seem obvious to me that the current appearance is that bad. I agree that `wxStaticLine` was too bright, but it used plain white (#ffffff), whereas here #dcdcdc is used which doesn't look as bright.

My concern is not just adding more and more of custom drawing code, but also that our hardcoded colour may look bad with custom themes and we wouldn't be even able to defend it by saying that we just use the platform default as it would be our choice. In fact, even with the default theme the chosen colour (#808080) doesn't seem right to me as other controls on your screenshots use #9b9b9b for their borders while Explorer uses #535353 for the borders around its controls (I can't find any real boxes in it).

Frankly, personally I'd just leave it as is. If people think this is really unacceptable, we probably ought to define some new `wxSYS_COLOUR_BOX` as either #dcdcdc (because this is what is used in the light mode and we don't have any existing `wxSYS_COLOUR_XXX` corresponding to it AFAICS) or #9b9b9b.

**Comment by k-serg** [comment]
Total Commander uses #7E7E7E for StaticBox ((button outline uses #7E7E7E)

Notepad++ uses #646464 for StaticBox (button outline uses #9B9B9B)

eranif's implementation of wxStaticBox uses #9B9B9B (vadz implementation of button outline #9B9B9B)

MS Explorer uses #898989 for checkbox outline (at this time vadz implementation not uses dark mode for checkboxes, as well as Total Commander or Notepad++), i don't see any StaticBox in Exlorer.

So, in different apps we have slightly different behaviour.

But i beleave that any of this approach is **much better**, than current wxStaticBox color (#DCDCDC).

BTW, wxSplitterWindow or wxSearchCtrl uses (#FFFFFF) which is mostly annoying for me:
![wxSplitterWindow_wxSearchCtrl](https://user-images.githubusercontent.com/76852271/210767488-c0b2d0c4-cdeb-4b07-a0af-12ece27d2d8e.png)

**Comment by vadz** [comment]
> Total Commander uses #7E7E7E for StaticBox ((button outline uses #7E7E7E)
> 
> Notepad++ uses #646464 for StaticBox (button outline uses #9B9B9B)
> 
> eranif's implementation of wxStaticBox uses #9B9B9B

Err, the code uses `wxLIGHT_GREY` which is #808080 and the screenshot above shows #808080 too.

> MS Explorer uses #898989 for checkbox outline (at this time vadz implementation not uses dark mode for checkboxes, as well as Total Commander or Notepad++),

It does use dark mode for native check boxes (you can try disabling dark mode support for them to see that otherwise they don't work at all in dark mode), but Explorer probably uses a different control entirely.

> But i beleave that any of this approach is **much better**, than current wxStaticBox color (#DCDCDC).
> 
> BTW, `wxSplitterWindow` or `wxSearchCtrl` uses (#FFFFFF) which is mostly annoying for me: 

`wxSplitterWindow` could (and should) be changed as it's generic. But `wxSearchCtrl` and `wxTextCtrl` are native controls that draw their borders themselves and we'd have to overdraw them or something like that to change it and I'd be really reluctant to do this. More such custom drawing we have, more likely it is that something will break in the next Windows update and/or won't look correctly with some custom theme even today.

**Comment by k-serg** [comment]
>Err, the code uses wxLIGHT_GREY which is #808080 and the screenshot above shows #808080 too.

My bad :(

>It does use dark mode for native check boxes (you can try disabling dark mode support for them to see that otherwise they don't work at all in dark mode)

I mean checkbox not uses inverted colors, as Explorer does.

>But wxSearchCtrl and wxTextCtrl are native controls that draw their borders themselves and we'd have to overdraw them or something like that to change it and I'd be really reluctant to do this. 

Well... there is also wxDir{File}PickerCtrl and so on.

>More such custom drawing we have, more likely it is that something will break in the next Windows update and/or won't look correctly with some custom theme even today.

Windows UX already broken since Windows 8: a "Zoo" with controls from 90-x to (non-native at all) modern. "What is dead, may never die".

**Comment by vadz** [comment]
I've finally applied your changes, thanks @eranif, but I've also made it possible to customize the colour, as it still seems quite arbitrary to me, and, importantly, to disable custom drawing of the border completely via the new `wxDarkModeSettings` class, see #23275.

Please let me know if you see anything wrong with this, otherwise I'll merge it soon.

**Comment by eranif** [comment]
Thanks. I saw the commit, having the ability to customise the colours, is just an extra bonus. I will test this today
