### ISSUE TITLE
Crash in wxAppConsoleBase::CleanUp() since 3.2.xx

### ISSUE THREAD

**Issue by tester0077** [wxWidgets/wxWidgets#23105]
Porting an existing app to 3.2.x causes a crash in wxAppConsoleBase::CleanUp() because the app itself cleaned up the config object on exit.
This change was not mentioned in the 3.2 changelog
The new code
#if wxUSE_CONFIG
    // Delete the global wxConfig object, if any, and reset it.
    delete wxConfigBase::Set(NULL);
#endif // wxUSE_CONFIG

crashes if I execute:
  m_pConfig->Flush();// needed to ensure data is written
  // avoid memory leaks
  delete m_pConfig;
  m_pConfig = NULL;
before exiting my app

IMO, the NEW code in cleanup() should verify that the config object has not already been cleaned up
In my case, this shows under Win 10, MSVC 2029 & wxWidgets 3.2.0

**Comment by vadz** [comment]
This seems to be a side effect of 7de27d30ac (Destroy global wxConfig even if main loop didn't run, 2022-06-15) which moved the destruction later during the process shutdown.

It is unfortunate, but what you did was **always** invalid, the global `wxConfig` pointer is managed by `wxConfig`, so you need to let it know if you delete it by doing the same `delete wxConfig::Set(NULL)` in your own code. We have no way to "verify that [...] has not already been cleaned up" if you don't do this, because you simply leave `wxConfig` with a dangling pointer.

We probably could detect this in `wxConfig` dtor but it would be an assert failure that you'd still have to fix.

**Comment by tester0077** [comment]
Thank you for the explanation.
I will fix it in my code.
