### ISSUE TITLE
wxFontList::FindOrCreateFont() does not work with pixel or fractional sizes

### ISSUE THREAD

**Issue by PBfordev** [wxWidgets/wxWidgets#23139]
### Description
When calling `wxFontList::FindOrCreateFont(wxFontInfo&)`, only font size in points is considered:
https://github.com/wxWidgets/wxWidgets/blob/78a041f2ed63505d1a563da2885728f4af282b66/include/wx/font.h#L653-L657

However, in `wxFontInfo`, the point size is always `-1` when using the pixel size, so using any pixel size with `wxFontList::FindOrCreateFont(wxFontInfo&)` behaves as if a font with the point size of `-1` was requested.

I am not sure this can be easily fixed as the pixel size may not be available for fonts in the list created using a point size?

I did not test how the method works with  `wxFontInfo` using a fraction point size but I suspect it may also have a (small) problem, i.e., using a rounded integer instead of actual fractional point size.

While this is a low priority issue perhaps not worth spending time to fix it, I think it should be documented as a method's limitation. as the current behaviour is quite unexpected.

**Comment by vadz** [comment]
This is indeed broken and in more than one way because not only pixel size is ignored, but fractional point size is also not handled correctly.

This shouldn't be difficult to fix, but it's not completely trivial neither. I'd do at least the following because it could be done in 3.2 too:

1. Make `FindOrCreateFont()` overload taking `wxFontInfo` the primary one, i.e. implement the other ones in terms of it rather than implementing it in terms of the one taking `int pointSize`.
2. Change comparison using `font->GetPointSize () == pointSize` to something like `info.IsUsingSizeInPixels() ? (font->GetPixelSize() == info.GetPixelSize()) : (font->GetFractionalPointSize() == info.GetFractionalPointSize())`.
3. Add a couple of tests checking that this indeed works.

Of course, in master it would make sense to make more extensive changes and use `std::unordered_map<wxFontInfo, wxFont> m_list;` in `wxFontList` instead of deriving it from `wxGDIObjListBase` as this should make the code much simpler and also much more efficient (`O(1)` rather than `O(N)`).

And it would probably also make sense to add overloads taking `double size` and `wxSize size` too for consistency.

**Comment by PBfordev** [comment]
Thanks for the quick reply.

Before creating this Issue, I actually started writing a PR which was basically along the lines of your suggestion.

However, I have no idea if a pixel size is actually available for any `wxFont`, regardless of which size it was created with. I am not even sure how pixel size works: Is it DPI-based, i.e., can the same font point size result in a different pixel size?

Since I am very confused by all the physical, logical, and DI pixels stuff and I can test only on Windows, I quickly abandoned the PR idea...

**Comment by vadz** [comment]
Yes, `wxFont::GetPixelSize()` will always return something even if the font was created using the size in points. And, as everything else in wx API except for the special exceptions (yeah, so it's a bit tautological), it's in logical pixels, not DIPs. So I think it's not that difficult, although it's certainly not trivial neither.
