### ISSUE TITLE
wxPropertyGrid use of global state causes problems when using wxPython

### ISSUE THREAD

**Issue by craftyjon** [wxWidgets/wxWidgets#23165]
### Description

`wxPropertyGrid` makes use of module-level global state (`wxPGGlobalVars`) that can be mutated by the user, for example to register custom editors.

wxPython has several modules (`wx.adv`, `wx.html`, etc) that call `wxPyReinitializeModules` when they are imported.

This call wipes out changes made to the global state, and programs using wxPython alongside wxWidgets therefore can have their custom editors broken just by importing some wxPython modules.  See https://gitlab.com/kicad/code/kicad/-/issues/13280 for details.

There are various workarounds that could be done, but in my opinion the right fix for this is to get rid of global state so that it is safe to call `wxPyReinitializeModules` at any point in time.  It does not seem clear to me that there is any reason that the `wxPropertyGrid` state must be global, rather than local to an instance.  It would be fine for me if I had to register editor classes once per `wxPropertyGrid` instance.

### Platform and version information

- wxWidgets version  you use: 3.2.1
- wxWidgets port  you use: wxMSW, wxGTK, wxOSX
- OS  and its version: Windows 10; Ubuntu (various); macOS 11/12/13

**Comment by vadz** [comment]
I don't really understand the purpose of `wxPGGlobalVars` at all, but it also seems very wrong to me to reinitialize the modules multiple times. If the definition of `wxPyReinitializeModules()` at

https://github.com/wxWidgets/Phoenix/blob/cae89a5df8247c91196571f0b696c9cbb064f8a6/src/wxpy_api.sip#L550

is correct, it must break *all* modules with non-trivial `OnInit()`. We could work around this here by not reallocating `wxPGGlobalVars` if it's already non-null but wxPython just can't do this, at the very least this results in tons of memory leaks. There has to be a better way!

cc @RobinD42

**Comment by craftyjon** [comment]
> I don't really understand the purpose of `wxPGGlobalVars` at all

It is not really clear to me either, for what it's worth.  It seems like an overzealous optimization to have a system for registering custom editor classes (etc) globally rather than per each instance of `wxPropertyGrid`, and it leads to this kind of problem as well as requiring that all property grids used throughout an application share this global state, which is not really that desirable to me.

> it also seems very wrong to me to reinitialize the modules multiple times

As you point out, wxPython is currently assuming otherwise.  I guess wxWidgets maybe could take a stronger stance one way or the other as to whether or not it is valid to initialize modules more than once.

**Comment by vadz** [comment]
> > I don't really understand the purpose of `wxPGGlobalVars` at all
> 
> It is not really clear to me either, for what it's worth. It seems like an overzealous optimization to have a system for registering custom editor classes (etc) globally rather than per each instance of `wxPropertyGrid`, and it leads to this kind of problem as well as requiring that all property grids used throughout an application share this global state, which is not really that desirable to me.

In fact the custom editor classes is about the only thing I do understand here: it's similar to how we have global lists of handlers for the image formats etc. It's not really an optimization and I agree that it might not be the best idea to do it, but we can't really change it any more because `wxPropertyGrid::RegisterEditorClass()` is static and changing this would break any code using it.

It's rather all the rest in `wxPGGlobalVarsClass` that I find baffling, e.g. stuff like `m_offline`...
 
> > it also seems very wrong to me to reinitialize the modules multiple times
> 
> As you point out, wxPython is currently assuming otherwise. I guess wxWidgets maybe could take a stronger stance one way or the other as to whether or not it is valid to initialize modules more than once.

I never realized there could have been any ambiguity here. It is valid to initialize modules more than once, but only after cleaning them up. And this loses all state, of course.

If we need to support wxPython use, we need to remember the state of initialization of each module and avoid re-initializing those that had been already initialized before. This is possible, I guess, but it has never been done nor even discussed so far. And what `wxPyReinitializeModules()` does now is absolutely and definitely wrong.

**Comment by RobinD42** [comment]
It's been a loooong time but if I remember correctly, the `wxPyReinitializeModules` function was needed when some wx DLL or shared library with a `wxModule` was not imported until after the main `wxModule` initialization functionality was done. In wxPython this can happen when the DLL is only linked to a non-core wxPython module, so the DLL is not loaded until the Python module is imported, possibly a long time after the core modules have been imported. So the easiest way to ensure that those late-loaded wxModule classes are initialized is to run it again when the Python module is imported.

**Comment by imciner2** [comment]
> It's not really an optimization and I agree that it might not be the best idea to do it, but we can't really change it any more because wxPropertyGrid::RegisterEditorClass() is static and changing this would break any code using it.

I thought functionality could usually be removed if deprecated for a release or two? So in 3.4 a local version of all these values can be included in the property grid object with a flag to use local instead of global (off by default to preserve compatibility), and those global vars/static functions are then deprecated. Then usecases that want local-only to avoid the module reload issue will work while preserving the current users. In 3.6 (or later) the global state can then be removed.

**Comment by vadz** [comment]
This is easy but unfortunately wrong and I don't understand how this hadn't resulted in any problems until now. In addition to the fact that wxPython should end up with multiple copies of animation, bitmap, image etc handlers because of this due to calling `InitializeModules()` more than once, you also call `wxModule::RegisterModule()` which means that you have multiple copies of the same module in `ms_modules` and this just can't be good... And we don't keep information about the already registered modules, so avoid this would require some changes.

But either wxPython must stop doing this, or we have to support it properly.

**Comment by vadz** [comment]
I've created #23187 which makes sense to me in any case and which should fix this problem in master. Unfortunately it's ABI-incompatible and so can't be backported to 3.2. There the only thing I can do to fix this quickly is this hack:
```diff
diff --git a/src/propgrid/propgrid.cpp b/src/propgrid/propgrid.cpp
index bb00ecce98..bf31c60ded 100644
--- a/src/propgrid/propgrid.cpp
+++ b/src/propgrid/propgrid.cpp
@@ -145,7 +145,15 @@ class wxPGGlobalVarsClassManager : public wxModule
     wxDECLARE_DYNAMIC_CLASS(wxPGGlobalVarsClassManager);
 public:
     wxPGGlobalVarsClassManager() {}
-    virtual bool OnInit() wxOVERRIDE { wxPGGlobalVars = new wxPGGlobalVarsClass(); return true; }
+    virtual bool OnInit() wxOVERRIDE
+    {
+        // This shouldn't happen, but we can actually be more called more than
+        // once, e.g. wxPython does it, see #23165, and in this case we
+        // shouldn't lose the current state.
+        if ( !wxPGGlobalVars )
+            wxPGGlobalVars = new wxPGGlobalVarsClass();
+        return true;
+    }
     virtual void OnExit() wxOVERRIDE { wxDELETE(wxPGGlobalVars); }
 };

```
which I can include in 3.2.2 if you confirm that this actually fixes the problem.

This being said, I'm pretty sure it's not going to be (and probably already not is) the last problem that happens due to re-initializing the modules in wxPython and so we really must do one of the following:

1. Initialize only the newly loaded modules when a new DLL is loaded.
2. Skip the already the registered/initialized modules when redoing it again.

Also, after a quick code search, I think a lot of people use this `wxPGGlobalVars` thing (including KiCad itself, apparently), so I don't think we're going to be able to deprecate it, the cost/benefit ratio would be just too high.
