### ISSUE TITLE
wxSearchCtrl not rendered correctly in wxQt

### ISSUE THREAD

**Issue by AliKet** [wxWidgets/wxWidgets#23170]
### Description

Due to this commit f2106dcc3c8f1afe349f325850b9fae85850b0b1 (which can be safely reverted since `wxGTK` has its own implementation now anyway) the text control colour is black as can be seen in the image below:
![searchctrl_bad](https://user-images.githubusercontent.com/7704771/214049005-191cf0a1-3cec-429b-b1ac-363f3f1bfc15.png)

**Expected:**
![searchctrl](https://user-images.githubusercontent.com/7704771/214049984-3f9e1670-a903-4f3b-a8b8-ed9875e0dd08.png)

### Platform and version information

- wxWidgets version  you use: latest
- wxWidgets port  you use: wxQt (Qt 5.5)
- OS  and its version: Ubuntu 18.04

**Comment by dsa-t** [comment]
Looks like this currently:

![Screenshot_2024-02-13_21-09-28](https://github.com/wxWidgets/wxWidgets/assets/37658952/d9c8220e-3793-4b5e-a743-054e90b71c6b)

A check for invalid color can be added in `wxQtDCImpl::SetBackground`.
Or in `wxWindowQt::SetBackgroundColour`

But in order to get white color on the full area


But also the order in `wxSearchCtrl::Create` has to be reversed: 

```
m_text->SetBackgroundColour(wxColour());
SetBackgroundColour( m_text->GetBackgroundColour() );
```
