### ISSUE TITLE
Value of π is rounded wrong in the internat sample

### ISSUE THREAD

**Issue by lanurmi** [wxWidgets/wxWidgets#23192]
### Description
The value π in the code of the `internat` sample is `3.14159265`. This value is entered in a `wxGrid`, which shows it as `3,141590`. The rounding is wrong; the last digit should be `3`, not `0`.

![Bildschirmfoto 2023-01-29 um 23 39 37](https://user-images.githubusercontent.com/5632407/215359372-79a2277e-8800-4347-8453-22f5122a1016.png)

The reason is that the internat sample calls `wxNumberFormatter` which formats the value using `%g`, and later `wxGrid` reads the stringified value and re-formats it using `%f`.

Whether or not this is expected behaviour with `wxGrid` is unknown to me.

### Platform and version information

- wxWidgets version  you use: current master
- wxWidgets port  you use: wxOSX
- OS  and its version: macOS 12.6.3

**Comment by vadz** [comment]
I don't think it's a bug per se, everything works as intended, but we just use insufficient precision when formatting the number to show it with 6 digit precision which is the default, so we need to either increase the precision when formatting or decrease it when displaying. I'll do the latter because there is no need to show many digits here.
