### ISSUE TITLE
macOS: wxCalendarCtrl does not obey wxUILocale

### ISSUE THREAD

**Issue by lanurmi** [wxWidgets/wxWidgets#23191]
### Description

There is a `wxCalendarCtrl` in the `internat` sample for the purpose of showing that weekdays and months are localized. Yet they are not on macOS – the calendar is in English.

Steps to reproduce:
1. Set system language/country to German/Germany.
2. Start the `internat` sample.
3. Observe that everything else within the frame is in German, but not the calendar.

![Bildschirmfoto 2023-01-29 um 23 39 37](https://user-images.githubusercontent.com/5632407/215358645-9ae92e82-211d-4d12-89a5-00724b14fbd3.png)

### Platform and version information

- wxWidgets version  you use: current master
- wxWidgets port  you use: wxOSX
- OS  and its version: macOS 12.6.3

**Comment by utelle** [comment]
On macOSX the class `wxGenericCalendarCtrl` is used to display a calendar control. On initialization the control uses a system function (`wxCRT_StrftimeW`) to determine month and day names. The calendar control uses these names as retrieved from the system function, without calling `wxGetTranslation`. That is, the calendar control seems to assume that the locale used by the system functions (C library) is set to the locale corresponding to the preferred UI langauge.

However, the class `wxUILocale` does **not** call `setlocale` internally (as did `wxLocale`). That is, the locale used by the system functions is the default C locale (which corresponds to **en_US**).

@vadz Can you confirm this analysis? If yes, we need to discuss how to handle the translation for the calendar control, so that it works as expected independent of whether `wxLocale` or `wxUILocale` is used in the application to set the UI locale.

**Comment by lanurmi** [comment]
> On initialization the control uses a system function (`wxCRT_StrftimeW`) to determine month and day names.

Yes, and this is the underlying issue here, I think. The solution probably would be to implement `wxDateTime::GetWeekDay/MonthName` without `strftime`, through some Cocoa API.

> The calendar control uses these names as retrieved from the system function, without calling `wxGetTranslation`.

Obtaining day and months names through `wxGetTranslation` feels wrong, though it could work in most cases per se.

**Comment by vadz** [comment]
I agree that the solution is to add `wxLOCALE_MONTH_1`, ..., `wxLOCALE_MONTH_12` and `wxLOCALE_WEEKDAY_1`, `wxLOCALE_WEEKDAY_7` constants and return the translated values from `wxUILocale::GetInfo()` for them and then use this in `wxGenericCalendarCtrl`.

For Cocoa the implementation would use `NSDateFormatter`, which has [shortMonthSymbols](https://developer.apple.com/documentation/foundation/nsdateformatter/1409209-shortmonthsymbols?language=objc), and whose `locale` attribute could be set to the locale being used.

**Comment by lanurmi** [comment]
As a side note, `wxDateTime::Format()` does not obey wxUILocale either (due to the same reason), and should be implemented with `NSDateFormatter` too.
