### ISSUE TITLE
setlocal for Ukrainian language

### ISSUE THREAD

**Issue by YuSanka** [wxWidgets/wxWidgets#23210]
### Description

From version 3.1.6 wxWidgets calls `setlocation(0, wxInfoLanguage->LocaleTag)`, see (https://github.com/prusa3d/wxWidgets/commit/deef116a09748796711d1e3509965ee208dcdf0b#diff-7de25e9a71c4dce61bbf76492c589623d5b93fd1bb105ceaf0662075d15f4472),
where LocaleTag is a Tag of locale in BCP 47 - like notation.
For Ukrainian Language LocaleTag is "uk".
But setlocale(0, "uk") returns "English_United Kingdom.1252" instead of "uk",
and, as a result, locales are set to English_United Kingdom        
    
We use such workaround in PS now. After initialization of the wxLocale, for Ukrainian we call `setlocal `one more time with **GetCanonicalWithRegion()** data.

 ```
if (language_info->CanonicalName == "uk")
          setlocale(0, language_info->GetCanonicalWithRegion().data());
```

But I suppose, that this issue have be resolved in wxWidgets internally

### Platform and version information

- wxWidgets version  you use: 3.2.0
- wxWidgets port  you use: any
- OS  and its version: any

**Comment by vadz** [comment]
It would be really great if you could please provide an example of reproducing the problem because while I understand that the issue has something to do with the confusion between the language and country codes, I have no idea how to actually trigger it.

Please show some minimal code or, again, ideally a patch to the internat sample.

**Comment by vadz** [comment]
I can't reproduce the problem in the internat sample, e.g. here is what it shows under MSW:
```
[Window Title]
Internat Information

[Content]
Locale "uk_UA" is available.
Identifier: uk-UA; Layout: LTR
English name: Ukrainian (Ukraine)
Localized name: українська (Україна)

[OK]
```

Please explain what doesn't work exactly for you and, also whether the changes of #23226 change anything for you. TIA!

**Comment by YuSanka** [comment]
I'm sorry to be late with the reply.

For the repro you can just use your "calendar" sample, but make a small change
```
MyApp::MyApp() :
    // Locale affects on the language used in the calendar, and may affect
    // on the first day of the week.
    m_locale(wxLANGUAGE_UKRAINIAN) //m_locale(wxLANGUAGE_DEFAULT)
{
} 
```
1. Start "Calendar wxWidgets sample" application 
2. Select menu "Calendar" > "Use generic version"
3. You coudn's see any effect, calendar is in English 
![image](https://user-images.githubusercontent.com/19184891/219359708-ad5511ae-fc10-461c-81fe-c0fb5b7cc2e1.png)


But if I set any other language, for example **wxLANGUAGE_CZECH**, than everything works as expected.
![image](https://user-images.githubusercontent.com/19184891/219359350-48c1f917-4f31-4d91-81ce-543a7daeebf5.png)


To see where is a problem, add next code: 
```
diff --git a/src/common/intl.cpp b/src/common/intl.cpp
--- a/src/common/intl.cpp
+++ b/src/common/intl.cpp
@@ -128,6 +128,12 @@ const char* wxLanguageInfo::TrySetLocale() const
     {
         locale = LocaleTag;
         const char* const retloc = wxSetlocale(LC_ALL, locale);
+#if 1 // output to check the issue
+        wxString msg = wxString::Format("\nUnexpected locale is set in wxLocale::Init()\n"
+            "wxSetlocale(LC_ALL, %s) returns %s\n", LocaleTag, retloc);
+        if (retloc != locale)
+            wxLogLastError(msg);
+#endif
         if ( retloc )
             return retloc;
```

See: 
![image](https://user-images.githubusercontent.com/19184891/219357692-4b873bf3-76f0-40a7-a848-6bc538ed3025.png)

But if use **CanonicalRef** instead of **LocaleTag**, then issue is gone.
```
diff --git a/src/common/intl.cpp b/src/common/intl.cpp
--- a/src/common/intl.cpp
+++ b/src/common/intl.cpp
@@ -126,8 +126,19 @@ const char* wxLanguageInfo::TrySetLocale() const
     // CRT (check by calling setlocale()).
     if ( wxGetWinVersion() >= wxWinVersion_Vista )
     {
+#if 1 // fix for the setLocal issue
+        locale = CanonicalRef;
+#else
         locale = LocaleTag;
+#endif
+
         const char* const retloc = wxSetlocale(LC_ALL, locale);
+#if 1 // output to check the issue
+        wxString msg = wxString::Format("\nUnexpected locale is set in wxLocale::Init()\n"
+            "wxSetlocale(LC_ALL, %s) returns %s\n", LocaleTag, retloc);
+        if (retloc != locale)
+            wxLogLastError(msg);
+#endif
         if ( retloc )
             return retloc;

```
See 
![image](https://user-images.githubusercontent.com/19184891/219359032-e2e752f3-78da-4bb8-86ae-80015d853ea9.png)

**Comment by utelle** [comment]
> From version 3.1.6 wxWidgets calls `setlocation(0, wxInfoLanguage->LocaleTag)`, where LocaleTag is a Tag of locale in BCP 47 - like notation.

Right. And usually this works as expected.

> For Ukrainian Language LocaleTag is "uk".

This is correct. And in principle, it is not necessary to specify a region tag in addition to the language tag.

> But setlocale(0, "uk") returns "English_United Kingdom.1252" instead of "uk", and, as a result, locales are set to English_United Kingdom

Unfortunately, this is a flaw in the function `setlocale` (at least under Windows - I didn't check other platforms yet). The Microsoft Visual C++ documentation describes, which languages are supported by `setlocale` under the heading [Language strings](https://learn.microsoft.com/en-us/cpp/c-runtime-library/language-strings?view=msvc-170). The first paragraph references [[Appendix A: Product Behavior](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/a9eac961-e77d-41a6-90a5-ce1a8b0cdb9c) in [MS-LCID]: Windows Language Code Identifier (LCID) Reference](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/a9eac961-e77d-41a6-90a5-ce1a8b0cdb9c), where all defined languages are listed in a long table. In that table you find 2 entries for Ukrainian:

- **uk** for Ukrainian
- **uk-UA** for Ukrainian in Ukraine

However, the first reference [Language strings](https://learn.microsoft.com/en-us/cpp/c-runtime-library/language-strings?view=msvc-170) also contains a second paragraph, _Supported language strings_. This paragraph describes in a table which language strings the Microsoft C run-time library implementation also supports. Near the end of this table you find the language string **uk** and the equivalent locale name **en-GB**.

Obviously `setlocale` prefers the latter mapping from language string to locale name. And that explains the misbehaviour. Actually, only Ukrainian is affected by this flaw.

Interestingly, method `wxLocale::Init(int lang, int flags)` uses `info->GetCanonicalWithRegion()` to determine the short name of the locale (for **uk** this corresponds to **uk-UA**), but the Windows implementation of method `wxLanguageInfo::TrySetLocale()` uses `locale = LocaleTag` (instead of `locale = GetCanonicalWithRegion()`).

BTW, the implementation of method `wxLanguageInfo::TrySetLocale()` for non-Windows platforms **does** use `GetCanonicalWithRegion()`).

**Conclusion**: The Windows implementation of method `wxLanguageInfo::TrySetLocale()` should be changed to use `GetCanonicalWithRegion()`) as well.

For the time being, you may use the language identifier `wxLANGUAGE_UKRAINIAN_UKRAINE` instead of `wxLANGUAGE_UKRAINIAN` as a workaround to get the expected results.
