### ISSUE TITLE
problem with underlined links in wxOSX 3.2.2

### ISSUE THREAD

**Issue by andykt** [wxWidgets/wxWidgets#23264]
Insert the following line immediately after the \<body\> tag in
samples/html/about/data/about.htm:

\<p\>\<a href="#xxx"\>\<b\>this should be underlined\</b\>\</a\>

Build the about.app sample, run it and open the About dialog.
The link is not underlined for some reason.  Close the dialog
and open it again -- now the link is underlined.

This only seems to happen on macOS (no problem on Windows
using wxMSW 3.2.2), and only if the text is enclosed in \<b\>...\</b\>.

Note that it's easy to avoid the bug by inserting \<b\>\</b\>
anywhere before the 1st link.

The bug is a regression -- no missing underlines using wxOSX 3.1.5.

I'm using wxOSX 3.2.2 on a MacBook Pro running macOS 10.15.7.

**Comment by vadz** [comment]
Thanks, I can see this in master too and it's indeed something related to copying fonts in wxOSX because wxHTML correctly sets underlined bold font for "this" and we create `wxMacCoreGraphicsFontData` with `m_underlined == true`, but when it's time to actually draw it, we somehow end up with using a non-underlined font in `wxMacCoreGraphicsContext::DoDrawText()`.

I couldn't understand how does it happen however. If you (or anybody else) can bisect the code between 3.1.5 and 3.2.0 to understand which commit broke this, it could be helpful. Otherwise more time would be needed to debug this.

**Comment by andykt** [comment]
The bug was introduced between 3.1.6 and 3.1.7.  I'm pretty sure the following commit is the culprit but I don't understand the code well enough to suggest the correct fix:

https://github.com/wxWidgets/wxWidgets/commit/74c0fe6dccdf66d3bd766861749fc7262db585ae
