### ISSUE TITLE
Date widget fails with short date format in Norwegian locale

### ISSUE THREAD

**Issue by sethhillbrand** [wxWidgets/wxWidgets#23310]
### Description

The date widget expects numerical short dates only.  This is not the case for all locales and the validation will fail.

Run the calendar sample as shown below, specifying the locale.  This will set the short date to DD. mmm YYYY.  The calendar widget will show the correct date format but pressing "OK" on the shown date will raise a validation error.

![image](https://user-images.githubusercontent.com/914826/222780895-8b8f78f5-12d5-49c6-9bc6-b37853218fc0.png)

### Platform and version information

- wxWidgets version  you use: 3.2 git commit 393b57511c5d045bb8246f6ef6be7cdcab180c2b
- wxWidgets port  you use: wxGTK, wxOSX
- OS  and its version: Debian 12, macOS 13.1

+ GTK version:  3.24.36
+ Which GDK  backend is used: X11
+ Current theme:  Aidwata

**Comment by vadz** [comment]
Thanks for reporting this, this code in the generic date picker

https://github.com/wxWidgets/wxWidgets/blob/5f486a0806c471d2fe205d206be2dcfcd4d2d595/src/generic/datectlg.cpp#L263-L278

is just plain wrong as it never allows any letters for locales using `%b` (or `%B`, or any other non-numeric month/day representation).

I can (and will, soon) work around this, but I can't help wondering if using this validator is really that useful in the first place, knowing that we parse the date later anyhow and so won't accept any invalid input. Maybe we should just remove it?

**Comment by sethhillbrand** [comment]
I think as long as there is _a_ way to validate the user input that meets our need (@jey5nd6 thoughts?)

**Comment by vadz** [comment]
After looking at this a bit more, I realize that:

1. We can't "work around" this easily because we can have any arbitrary Unicode letters in the dates, so `wxFILTER_INCLUDE_CHAR_LIST` is never going to work. We could _exclude_ non-alnum characters not present in the format, i.e. forbid using `-` in a locale using `/` as date separator and vice versa, but I'm still not sure if it's really even worth it.
2. The behaviour of `wxDatePickerCtrlGeneric` is suboptimal even right now, as if you enter "12345" in the date field and press "Enter" in the dialog in the sample, you still get the "Happy birthday!" message because the picker silently reverts to the last good value if something invalid is entered -- which does make some sense, but means that there is no real validation.

So currently it's both too restrictive (this issue) and not restrictive enough (doesn't give any error for invalid entry provided it consists of valid characters).

I've tried fixing both of these problems in 725c9a0bc6b5b31860fdc53ce7a0cd8e541236e5 which is part of PR #23312. Please let me know what do you think of it. If there are no objections I'll merge it to master and make a 3.2-appropriate version too.

**Comment by jey5nd6** [comment]
LGTM.  Thanks!

**Comment by FarshadN** [comment]
Hello @vadz , Have you found a fix for this issue? I'm also stuck with invalid date format error on my first schematic design. Would temporarily changing the locale this issue?

**Comment by vadz** [comment]
This was supposed to be fixed, are you really using the latest version from git (either of master or 3.2)?
