### ISSUE TITLE
wxStaticText not wrapping text on Mac (Windows and Linux work OK)

### ISSUE THREAD

**Issue by lszl84** [wxWidgets/wxWidgets#23341]
### Description

The code below does not wrap the lines on Mac OS. Works correctly on Windows and Linux (see screenshots).

```cpp
#include <wx/wx.h>

class MyApp : public wxApp
{
public:
    virtual bool OnInit();
};

wxIMPLEMENT_APP(MyApp);

class MyFrame : public wxFrame
{
public:
    MyFrame(const wxString &title, const wxPoint &pos, const wxSize &size);
};

bool MyApp::OnInit()
{
    MyFrame *frame = new MyFrame("Hello World", wxDefaultPosition, wxDefaultSize);
    frame->Show(true);
    return true;
}

const auto paraText = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nisl vitae ultricies lacinia, nisl nisl aliquam nisl, vitae aliquam";

MyFrame::MyFrame(const wxString &title, const wxPoint &pos, const wxSize &size)
    : wxFrame(nullptr, wxID_ANY, title, pos, size)
{
    auto paragraph = new wxStaticText(this, wxID_ANY, paraText);
    paragraph->SetFont(wxFont(20, wxFONTFAMILY_DEFAULT, wxFONTSTYLE_NORMAL, wxFONTWEIGHT_NORMAL));
    paragraph->SetBackgroundColour(wxColour(200, 100, 100));
}

```
<img width="529" alt="Screenshot 2023-03-12 at 20 11 03" src="https://user-images.githubusercontent.com/42072702/224567737-9ce3dfbb-49c5-4441-a360-39b528b52d27.png">
<img width="1712" alt="Screenshot 2023-03-12 at 20 09 51" src="https://user-images.githubusercontent.com/42072702/224567743-418aae58-2214-4056-b396-4c3693edcc9f.png">
<img width="1712" alt="Screenshot 2023-03-12 at 20 09 43" src="https://user-images.githubusercontent.com/42072702/224567749-a39251bc-305b-48d8-b2e0-07ebc321e98d.png">

### Platform and version information

- wxWidgets version  you use: 3.2.2
- wxWidgets port  you use: wxOSX
- OS  and its version: Ventura 13.2.1 (22D68)

**Comment by vadz** [comment]
Apparently we need to use `setPreferredMaxLayoutWidth:` for this to work, but I'm really not sure. Maybe @csomor would have some idea?

It would be definitely nice if this worked, but for now you could probably use `wxGenericStaticText` as a workaround.

**Comment by csomor** [comment]
@vadz as far as I remember wxStaticText didn't have the guarantee to automatically wrap lines earlier, did it ?

**Comment by csomor** [comment]
`wxGenericStaticText` does need a call to Wrap, as does `wxStaticText` on macOS.

**Comment by lszl84** [comment]
From the user perspective, it is pretty confusing that the behavior is different on Mac than on the other platforms. If that is to be left as is, then it would be a good idea to mention this in the documentation.

**Comment by csomor** [comment]
@lszl84 since we are usually using native controls, these kind of things may always happen. And I thought we had discussed and even documented this somewhen in the last 25 years, but I forgot when and where. And the fact that `wxGenericStaticText` behaves exactly that way, could be proof .. But we can always adapt, we just need a clear concept on when exactly for which flags this should happen on macOS as well.

**Comment by vadz** [comment]
`Wrap()` was a rather ugly (because it modifies the actual label!) workaround for `wxStaticText` not doing this automatically in all ports added a long time ago (see 5d1b49193b (added wxStaticText::Wrap(), 2005-08-16)), but I think it would be nice if it were not needed.

So if Mac could implement the same behaviour as the other ports, it would be best.

BTW, I have no idea how could we have an automatic test for something like this. Making background white and checking that we have some non-white pixels below the first line of text?

**Comment by csomor** [comment]
ok, so I'll change the linebreak mode from Clip to WordWrap and let's see what happens ...

**Comment by csomor** [comment]
opened #23345 for this

**Comment by vadz** [comment]
@lszl84 Could you please test the PR above and check if it fixes the problem without introducing any new ones?

**Comment by lszl84** [comment]
@vadz looks good to me

<img width="444" alt="Screenshot 2023-03-15 at 18 21 58" src="https://user-images.githubusercontent.com/42072702/225392490-4c11b21e-bf5c-4051-852f-469a82461e91.png">

**Comment by vadz** [comment]
If we don't get any complaints about the change in behaviour under macOS, we probably should backport the commit above to 3.2 too.
