### ISSUE TITLE
wxFTP::GetFilesList freezes aplication

### ISSUE THREAD

**Issue by michallukowski** [wxWidgets/wxWidgets#23519]
### Description

All my projects after update from 3.0.4 to 3.2.2 freezes during wxFTP::GetFilesList function execution.

### Platform and version information

- wxWidgets version  you use: 3.2.2.1 (installed from MSYS2)
- wxWidgets port  you use: wxMSW
- OS  and its version: Windows 10 and 11

**Comment by vadz** [comment]
Thanks for reporting this, I can indeed reproduce the problem using this [test FTP server](https://dlptest.com/ftp-test/) with the following command:
```
$ WX_FTP_TEST_HOST=ftp.dlptest.com WX_FTP_TEST_USER=dlpuser WX_FTP_TEST_PASS=rNrKYTX9g7z3RgJRmxWuGHbeu WX_FTP_TEST_DIR=/ WX_FTP_TEST_FILE=foo ./tests/test -c List FTP
```

I've fixed it in #23521 (only the last commit there matters), although it's still a mystery why/when exactly did this get broken as I don't see any changes in this code since 3.0 days.
