### ISSUE TITLE
wxDateTime::Format() et al fail to properly format localized dates on macOS

### ISSUE THREAD

**Issue by lanurmi** [wxWidgets/wxWidgets#23557]
There is an issue with how `wxLocale` operates when using the system default language in wx 3.2 and newer. This issue manifests in such a way that day and month names are represented in English in e.g. the output of `wxDateTime::Format()`, `wxStrftime()`, and consequently the generic calendar control.

To Reproduce:
1. Overwrite `samples/internat/internat.cpp` by copying `internat.cpp` *from the 3.0 branch*.
2. Add e.g. `SetTitle(wxDateTime::Now().Format("%A %B %x %X %c"));` to the beginning of `MyFrame::MyFrame()` body.
3. Build the sample and run it *via Finder* (not via command line).
4. Choose "System default" as the language. (On my system, language/country is German/Germany during this test.)
5. Observe that the date in the title contains day and month names in English.
6. Observe that numerical parts of the output are in the expected localized format.

The key here is to select the system default language; when explicitly selecting something else from the list (even if it is the same as the actual system language), formatting does work.

### Platform and version information

- wxWidgets version  you use: 3.2 branch
- wxWidgets port  you use: wxOSX
- OS  and its version: macOS 12.6.5

**Comment by lanurmi** [comment]
I did some early morning debugging, and added some logging into `wxSetLocale`, after the actual `setlocale` calls: `wxLogMessage("wxSetlocale(%d, %s) = %s", category, locale, rv);`

During the startup and language selection of the internat sample, in both 3.0 branch and 3.2 branch `wxSetLocale()` is called twice, with the following arguments, and the following return values:

3.0:
```
wxSetlocale(0, de_DE) = de_DE
wxSetlocale(0, de_DE) = de_DE
```

3.2:
```
wxSetlocale(0, (null)) = C/UTF-8/C/C/C/C
wxSetlocale(0, ) = C
```

Looks quite different, and looks like 3.0 knows in advance what the desired locale is. And it apparently knows it due to this piece of code that is not present in 3.2: https://github.com/wxWidgets/wxWidgets/blob/87ad6fad8a6f453d7f1d35302a9dc31e2289d753/src/common/intl.cpp#L365-L369

If I copy-paste those lines here at line 434 in 3.2 branch https://github.com/wxWidgets/wxWidgets/blob/89dc204bb608c9177ac60ee8e657c9efdeb470ab/src/common/intl.cpp#L433-L436 then the issue seems to get fixed and `wxSetLocale` calls are now:
```
wxSetlocale(0, (null)) = C/UTF-8/C/C/C/C
wxSetlocale(0, de_DE) = de_DE
```

Still I don't know if this fix has some undesired side effects.

**Comment by vadz** [comment]
Thanks, so the fix is indeed to set the locale explicitly instead of relying on inheriting it from the environment, where it's not set in macOS case.

The reason the code from 3.0 was removed was that we wanted to be able to use the default locale even if we don't know about it, notably this took care of unusual country/language combinations such as `en_DE`, which are handled correctly now but were not in 3.0. However it looks like we still need to set the locale explicitly, at least under macOS, if we do recognize the locale.

So would something like this:
```diff
diff --git a/src/common/intl.cpp b/src/common/intl.cpp
index 057e6478e3..9ac872175b 100644
--- a/src/common/intl.cpp
+++ b/src/common/intl.cpp
@@ -447,10 +447,16 @@ bool wxLocale::Init(int lang, int flags)
         m_oldUILocale = oldUILocale;
     }

-    // Under (non-Darwn) Unix wxUILocale already set the C locale, but under
-    // the other platforms we still have to do it here.
-#if defined(__WIN32__) || defined(__WXOSX__)
-
+    // Under (non-Darwin) Unix wxUILocale already set the C locale, but under
+    // the other platforms we still have to do it.
+#if defined(__WXOSX__)
+    // Locale-related environment variables are not typically set under macOS,
+    // so don't rely on them unless we really have no other choice.
+    if ( !(info ? info->TrySetLocale() : wxSetlocale(LC_ALL, "")) )
+    {
+        ok = false;
+    }
+#elif defined(__WIN32__)
     // We prefer letting the CRT to set its locale on its own when using
     // default locale, as it does a better job of it than we do. We also have
     // to do this when we didn't recognize the default language at all.
```
be enough to fix the problem?

**Comment by utelle** [comment]
> 3.2:
> 
> ```
> wxSetlocale(0, (null)) = C/UTF-8/C/C/C/C
> wxSetlocale(0, ) = C
> ```
> 
> Looks quite different, and looks like 3.0 knows in advance what the desired locale is. And it apparently knows it due to this piece of code that is not present in 3.2:
> 
> https://github.com/wxWidgets/wxWidgets/blob/87ad6fad8a6f453d7f1d35302a9dc31e2289d753/src/common/intl.cpp#L365-L369

This code was removed in commit 18bf718f607ad0f11a5e4c5e48916d73c50a16a0. Actually, the method `GetLanguageInfo()` calls `GetSystemLanguage()` internally, too. Maybe that was the reason to remove these lines, but the commit message is quiet about that.

However, these lines have a side effect, namely the variable `lang` is set to the id of the detected system language, while the current code keeps the value `wxLANGUAGE_DEFAULT`.

When `lang` is **not** `wxLANGUAGE_DEFAULT`, then `wxUILocale::UseLocaleName()` is called instead of `wxUILocale::UseDefault()`. However, that is not so important, because the method `wxUILocale::Use()` does nothing under macOS.

The main difference is that later on in the 3.0 code for macOS `wxSetlocale(LC_ALL, "id of detectedLocale")` is called instead of `wxSetlocale(LC_ALL, "")`.

In the current code `wxSetlocale(LC_ALL, "")` is called, because `lang == wxLANGUAGE_DEFAULT`.

When an application starts the default locale is "C". What irritates me is that calling `wxSetlocale(LC_ALL, "")` does not change that to the system locale (as it should).

I remember discussions with @vadz that under macOS `setlocale` should not be called at all due to various system bugs. And that is what is done when using `wxUILocale` alone. However, `wxLocale` always called `setlocale` and keeps doing so.

The problem I see is that calling `setlocale` with the detected sytem language may set a locale that is not identical to the actual system locale. For example, if the system language is `en_DE` for whatever reason, the "detected system language" will be `en_GB`, because `en_DE` is not in the wxWidgets language database.

**Comment by vadz** [comment]
> The problem I see is that calling `setlocale` with the detected sytem language may set a locale that is not identical to the actual system locale. For example, if the system language is `en_DE` for whatever reason, the "detected system language" will be `en_GB`, because `en_DE` is not in the wxWidgets language database.

I _think_ (but I haven't tested this) that in this case `info` would remain null under macOS and we still would call `setlocale(LC_ALL, "")`, which would do nothing, but at least the behaviour would be the same as before.

I.e. I still think we should fix the major problem with not using the correct C locale for `wxLocale` with known languages/locales before thinking about the more minor problem of unknown ones.

Please let me know if you see anything wrong with the change proposed above.

**Comment by utelle** [comment]
> I _think_ (but I haven't tested this) that in this case `info` would remain null under macOS and we still would call `setlocale(LC_ALL, "")`, which would do nothing, but at least the behaviour would be the same as before.

No, not necessarily. For example, `en_DE` would probably return the entry for `en_GB`. Only if no entry with an equal language part can be found, `info` would remain null.

However, my point was that I expected the call `setlocale(LC_ALL, "")` to set the user-preferred locale (that is, the default system locale). However, this doesn't seem to be the case.

> I.e. I still think we should fix the major problem with not using the correct C locale for `wxLocale` with known languages/locales before thinking about the more minor problem of unknown ones.

Yes, of course.

> Please let me know if you see anything wrong with the change proposed above.

Yes, your change will restore the old behaviour.

**Comment by Captain-Pumpkinhead** [comment]
I'm having this same issue with the [Linux Server container image of KiCAD](https://hub.docker.com/r/linuxserver/kicad).  Every time I try to create a new page in Schematic Editor, it gives me this error:

> ### An assertion failed!
> /home/buildozer/aports/community/wxwidgets/src/wxWidgets-3.2.5/src/common/datetimefmt.cpp(318): assert ""!formatp.empty()"" failed in Format(): NULL format in wxDateTime::Format

![image](https://github.com/user-attachments/assets/fd7c2786-b28c-4675-b7bd-f15b529d3248)

I'm trying to find a way to fix this, and so far, this thread is the best lead I've gotten.  Weirdly, it worked _once_.  I've tried detaching all volumes and changing environmental the Docker Compose stuff to see if there was an interference there and tried older images.  Nothing has worked so far.  I'm thinking maybe the auto-update means that the older versions of KiCAD I'm trying are updating before I even get to them.

Here's the section of my Docker Compose script that's running KiCAD:

``` docker-compose.yaml
  kicad:
    image: lscr.io/linuxserver/kicad:latest
    devices:
      - /dev/dxg:/dev/kfd
      - /dev/dri:/dev/dri
    #security_opt:
      #- seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      #- DRINODE=AMD
    volumes:
      - kicad:/config
      - kasm-local:/config/.local
      - cad-common:/config/common
      - usr-share-freecad:/usr/share/freecad
      - usr-share-kicad:/usr/share/kicad
      - usr-share-orca:/usr/share/orca
    ports:
      - 3019:3000
      - 3020:3001
    restart: unless-stopped
```

I'm not sure if this is a KiCAD problem or a problem with the Linux Server image.  If you guys think I should take this over there, let me know.

Any advice or clues would be appreciated, thank you!
