### ISSUE TITLE
Build with libwebkit2gtk-4.1 and libsoup-3.0

### ISSUE THREAD

**Issue by Jenyay** [wxWidgets/wxWidgets#23630]
### Description
Applications using wxWidgets and WebKit2GTK do not work with the latest runtime flatpak on Linux because the libwebkit2gtk-4.0 and libsoup-2.4 libraries have been removed. Only libwebkit2gtk-4.1 and libsoup-3.0 libraries are present. 

I really need the ability to build wxWidgets using libwebkit2gtk-4.1 and libsoup-3.0.

**Comment by swt2c** [comment]
Yes, I'm working on this.

**Comment by joshua-stone** [comment]
Fixing this would drastically simplify supporting wxWidgets apps on Linux. A flatpak I maintain has to spend a lot of time building webkitgtk and libsoup because the versions that ship in the Gnome SDK aren't compatible with wxWidgets:

https://github.com/flathub/org.moneymanagerex.MMEX/blob/e1f3b4f4f61a5360ed5d50f4b043a4b7a6683a13/org.moneymanagerex.MMEX.yml#L25
