### ISSUE TITLE
Linking failure with latest wxWidgets development code on Linux

### ISSUE THREAD

**Issue by joshua-stone** [wxWidgets/wxWidgets#23643]
# Describe the bug:

The latest code that allows for [building wxWidgets on a newer libwebkit2gtk](https://github.com/wxWidgets/wxWidgets/issues/23630) appears to have introduced a regression when trying to build a project that uses wxWidgets:

```
[100%] Linking CXX executable mmex
/usr/lib/gcc/x86_64-unknown-linux-gnu/12.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: /app/lib/libwx_gtk3u_stc-3.3.a(stclib_ScintillaWX.o): in function `ScintillaWX::WndProc(unsigned int, unsigned long, long)':
/run/build/wxWidgets/./src/stc/ScintillaWX.cpp:821: undefined reference to `Lexilla::Load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/lib/gcc/x86_64-unknown-linux-gnu/12.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: /run/build/wxWidgets/./src/stc/ScintillaWX.cpp:805: undefined reference to `LexerNameFromID'
/usr/lib/gcc/x86_64-unknown-linux-gnu/12.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: /run/build/wxWidgets/./src/stc/ScintillaWX.cpp:806: undefined reference to `CreateLexer'
/usr/lib/gcc/x86_64-unknown-linux-gnu/12.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: /run/build/wxWidgets/./src/stc/ScintillaWX.cpp:814: undefined reference to `CreateLexer'
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/mmex.dir/build.make:1919: src/mmex] Error 1
make[1]: *** [CMakeFiles/Makefile2:371: src/CMakeFiles/mmex.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```

# To Reproduce:

Use the latest wxWidgets development code to build the latest stable release of [moneymanagerex](https://github.com/moneymanagerex/moneymanagerex). One way to test this is with flatpak-builder, which I use for maintaining the [moneymanagerex flatpak](https://github.com/flathub/org.moneymanagerex.MMEX). Here's a test build manifest using a recent commit:

```
$ cat org.moneymanagerex.MMEX-test.yml 
app-id: org.moneymanagerex.MMEX
runtime: org.gnome.Platform
runtime-version: '44'
sdk: org.gnome.Sdk
command: mmex
cleanup:
  - /bin/wx-config
  - /bin/wxrc
  - /bin/wxrc-3.2
  - /include
  - /lib/*.a
  - /lib/pkgconfig
  - /lib/wx/include
  - /share/aclocal
  - /share/bakefile
finish-args:
  - --socket=fallback-x11
  - --socket=wayland
  - --device=dri
  - --filesystem=home
  - --share=ipc
  - --share=network
modules:
  - name: wxWidgets
    config-opts:
      - --disable-shared
      - --enable-cxx11
      - --with-cxx=11
      - --enable-webview
      - --with-gtk=3
      - --enable-intl
    sources:
      - type: git
        url: https://github.com/wxWidgets/wxWidgets
        commit: f50fb719e8f3f2ded9f8ca247055edc388e8631c
  - name: moneymanagerex
    buildsystem: cmake
    config-opts:
      - -DCMAKE_BUILD_TYPE=Release
    post-install:
      - install -Dm644 "${FLATPAK_ID}.metainfo.xml" "${FLATPAK_DEST}/share/metainfo/${FLATPAK_ID}.metainfo.xml"
    sources:
      - type: git
        url: https://github.com/moneymanagerex/moneymanagerex
        tag: v1.6.3
      - type: patch
        path: cmakelists-mmex.patch
      - type: patch
        path: cmakelists-3rd.patch
```

To build with the manifest:

```
$ flatpak run org.flatpak.Builder --verbose --force-clean --ccache _build org.moneymanagerex.MMEX-test.yml
```

### Platform and version information

- wxWidgets version  you use: latest code on github
- OS  and its version: Linux, flatpak

+ GTK version:  3.24.38
+ Which GDK  backend is used: Wayland

**Comment by MaartenBent** [comment]
From what version did you update? This looks like it could be related to scintilla and lexilla becoming submodules. Did you try running `git submodule update --init`?

**Comment by imciner2** [comment]
It's not submodule related, it checks out the submodule fine. It looks like the static build isn't passing `libwxlexilla` on the link line to the final application. This appears to be a problem with the upstream CMake `FindwxWidgets` script though, since wx is built using configure and then it is being searched for from the CMake build system in moneymanagerex. The returned scintilla library should have a target link to the lexilla library there.

Alternately, is there a reason to have lexilla and scintilla in two different static libraries in the system, or can they be merged into one?

**Comment by MaartenBent** [comment]
Upstream has split scintilla into two separate libraries, lexilla and scintilla, so we follow that.

On Linux, CMake's `FindwxWidgets` is just a front for `wx-config`. And when building static with configure, `wx-config --libs` seems indeed to be missing `lexilla`.

I suspect because it is missing lexilla here:
https://github.com/wxWidgets/wxWidgets/blob/f50fb719e8f3f2ded9f8ca247055edc388e8631c/configure.in#L7635-L7637

I'll try to regenerate configure and test this later today/tomorrow.

**Comment by pedro-vicente** [comment]
Also have this error on the latest from GitHub



```
/usr/bin/ld: /home/pvn/github/nostr_client_relay/build/ext/wxWidgets-3.2.2.1/lib/libwx_gtk3u_stc-3.3.a(ScintillaWX.cpp.o): in function `ScintillaWX::WndProc(unsigned int, unsigned long, long)':
/home/pvn/github/nostr_client_relay/ext/wxWidgets-3.2.2.1/src/stc/ScintillaWX.cpp:805: undefined reference to `LexerNameFromID'
/usr/bin/ld: /home/pvn/github/nostr_client_relay/ext/wxWidgets-3.2.2.1/src/stc/ScintillaWX.cpp:806: undefined reference to `CreateLexer'

```

**Comment by vadz** [comment]
@pedro-vicente This seems completely unrelated because this is about 3.2.2 where there is no Lexilla library. Please open another issue explaining how do you configure and build wxWidgets in details.

**Comment by pedro-vicente** [comment]
@vadz I fixed by adding the library to the CMake list (shown here as 'wxlexillad' for Windows)

https://github.com/pedro-vicente/nostr_client_relay/commit/deed97761b7e7a747d48f8962089cf68ed5a6475

This only happened when I used the git version with

git clone --recurse-submodules https://github.com/wxWidgets/wxWidgets.git

I am using other code base without git, using the sources from a .zip file of wxWidgets-3.2.2.1 (last release)
where this error does not happen

**Comment by pedro-vicente** [comment]
> /usr/bin/ld: wxWidgets-3.2.2.1

this line is misleading, just a name I used to have the same name, ignore that

**Comment by vadz** [comment]
> > /usr/bin/ld: wxWidgets-3.2.2.1
> 
> this line is misleading, just a name I used to have the same name, ignore that

Well, yes, this was very misleading.

Anyhow, even if this is related to the original problem, you still need to explain what exactly you do, i.e. how do you build and use wxWidgets.

**Comment by pedro-vicente** [comment]
I use this CMake script to build

https://github.com/pedro-vicente/nostr_client_relay/blob/main/desktop/CMakeLists.txt

**Comment by MaartenBent** [comment]
Lexilla needs to be before stc here? https://github.com/pedro-vicente/nostr_client_relay/blob/main/desktop/CMakeLists.txt#L64

But I suggest using `find_library(wxWidgets CONFIG)` instead of manually specifying all library names.

**Comment by pedro-vicente** [comment]
>>> Lexilla needs to be before stc here?

I don't know if it needs to be before, like this it happens to work :-)

>>> But I suggest using find_library(wxWidgets CONFIG)

I don't like 'find_library', I like do specify the paths / files in the Cmake
