### ISSUE TITLE
Tree item is not refreshed when first child is added

### ISSUE THREAD

**Issue by taler21** [wxWidgets/wxWidgets#23718]
### Description

On Windows, an item in a `wxTreeCtrl` is not refreshed when its first child item is added, i.e. the [+] does not appear.

The issue can be reproduced in the tree sample.
1. Start the tree sample.
2. Select the root item.
3. In 'Tree' menu, click on 'Delete children'.
4. In 'Tree' menu, click on 'Append a new item'.

I have tested it on Windows 7 and Windows 10 where it behaves the same.

### Possible fix

There is already a special handling for this refresh issue in 3.2 branch for older Windows versions (before Vista), which would fix the issue on newer Windows versions as well.

https://github.com/wxWidgets/wxWidgets/blob/be772c284f20969e7c2a5b62d3d43db56cdc5a6b/src/msw/treectrl.cpp#L1550-L1574

In master branch this special handling was removed by 43ff845e771adf1f761e956c50c38476d956ebda (Remove Windows XP and Vista support, 2022-11-10).

### Platform and version information

- wxWidgets version  you use: 3.2.2.1
- wxWidgets port  you use: wxMSW
- OS  and its version: Windows 10

**Comment by vadz** [comment]
Thanks for reporting this, I can confirm that I see it too under Windows 10.

Actually, I see the problem even earlier, as the "+" button doesn't disappear after deleting the children neither. This is less critical, probably, as it will disappear if you try to expand it, but still wrong...

I've created the PR above fixing the problem reported here and partially fixing the problem I see. It would be better to refresh the item when deleting its last child instead of only doing it in `DeleteChildren()`, but I don't have time for this right now and this is better than nothing. And, as mentioned in the commit message, I suspect the best would be to handle `TVN_GETDISPINFO` to provide this information on demand.

Please let me know if you see any problems with my PR and if not I'll merge it and backport to 3.2 too.

TIA!

**Comment by taler21** [comment]
I tested the PR and can confirm that it fixes this refresh issue.

> Actually, I see the problem even earlier, as the "+" button doesn't disappear after deleting the children neither.

Indeed, but this problem only exists with the master branch.
And notice also #23719, which is a more serious problem (regression) in master branch when deleting the children.

**Comment by taler21** [comment]
Would it be possible for commit vadz/wxWidgets@3ed273ce98083e2e9c81bfb550a68ed4b322ae88 to be merged into master and backported to 3.2 to be part of 3.2.3?
This would fix the issue of this ticket and the other issue you noticed exists only in master branch and probably has the same cause as #23719.

Thanks in advance!

**Comment by vadz** [comment]
Yes, I hoped to find more time/energy to look into this before merging it but it's probably not going to happen this week neither, so I'll merge the existing PR and backport it so that we have at least this in 3.2.3.

Thanks for the reminder.
