### ISSUE TITLE
Request for wxGrid to add set row text color

### ISSUE THREAD

**Issue by guzmanpaco** [wxWidgets/wxWidgets#23753]
### Description
We would like to request for wxGrid to have a new function:
void SetRowTextColour( int row, const wxColour& );

Currently, you can only change 1 cell's text color at a time.
On older wxWidgets 3.1.0 and 3.1.5, we are encountering issues when trying to change each row's cell color. 

We encounter segfault when the following occurs very fast:

1. wxMutex lock
2. Row added
3. Row text is modified
4. Set each cell color to a specific color
5. wxMutex unlock

We encounter segfault at 4 due to GetOrCreateCellAttrPtr(row, col) of SetTextColour(colour) sometimes returning invalid pointer. If we comment out #4 sequence, issue does not encounter segfault.

We think that maybe adding SetRowTextColour to grid could prevent the issue.

I have created a sample program using a modified grid sample, but the issue cannot be reproduced with wxWidgets 3.2.2.1.

Could you investigate the cause of GetOrCreateCellAttrPtr(row, col) returning an invalid pointer?
If this was fixed in Ver.3.2.2.1, could you please provide the correction details? It is not mentioned in the current change log.

Thank you

**Comment by vadz** [comment]
Sorry, if the issue can't be reproduced in 3.2.2, then there is really no point in adding a new function which could only be added in versions later than 3.2.2 where it wouldn't be needed, so this is a rather strange request.

I'm not aware of any specific bugs related to this fixed in 3.2, but then there are many, many details missing here (such as where/why does it crash and what does the mutex have to do with it). You could try bisecting the history between 3.1.5 and 3.2.2 to find the commit which fixes the problem for you, but we really can't help you with this.
