### ISSUE TITLE
`wxZipInputStream::LastRead()` returns 0 after `Peek()`

### ISSUE THREAD

**Issue by vadz** [wxWidgets/wxWidgets#23820]
But I have also tried `wxZipInputStream` where `LastRead()` after `Peek()` returns `0`.  Not sure why, since `wxZipInputStream` is derived from `wxArchiveInputStream` whose `Peek()` just [returns `wxInputStream::Peek()`](https://github.com/wxWidgets/wxWidgets/blob/cc5f5f90b08b72c7cf21fd4238c6d3bc2e156394/include/wx/archive.h#L102). But maybe I am doing something wrong or `Peek()` does not really make sense for a zipped stream. The test code was basically
```cpp
        wxFileSystem::AddHandler(new wxZipFSHandler);

        const wxString            zipFileName("test.zip#zip:\\test.txt");
        wxFileSystem              zipArchive;
        std::unique_ptr<wxFSFile> zipFile(zipArchive.OpenFile(zipFileName, wxFS_READ));

        if ( zipFile )
        {
            std::unique_ptr<wxInputStream> insz(zipFile->DetachStream());

            if ( insz )
                DoPeek(insm, "wxZipInputStream");
        }
```

_Originally posted by @PBfordev in https://github.com/wxWidgets/wxWidgets/issues/23758#issuecomment-1694221912_

**Comment by PBfordev** [comment]
@vadz, I am very embarrassed that I have to apologize for my sloppiness for the second time in one week. There is no such problem with `wxZipInputStream`.

The above is a non-issue stemming from a copy-and-paste mistake: The test code above calls `DoPeek()` with the memory input stream instead of the zip input stream (`insm` instead of `insz`).

Once again: Sorry for wasting your time.

**Comment by vadz** [comment]
No problem, thanks for rechecking this.
