### ISSUE TITLE
wxInputStream::SeekI does unnecessary Tell/Seek calls in common cases.

### ISSUE THREAD

**Issue by dsa-t** [wxWidgets/wxWidgets#23895]
### Description
See this code in `wxInputStream::SeekI`:
https://github.com/wxWidgets/wxWidgets/blob/3b7d81b7f28353ed3b932fbcce958cdc81cc1992/src/common/stream.cpp#L963-L970

In most usage cases, `mode` is not `wxFromEnd`.

`size` value is only used if `mode == wxFromEnd`, but `size = GetLength()` is executed in all modes.

For file streams (a common use case), `GetLength` performs multiple Tell/Seek calls, reducing the performance.

**Comment by vadz** [comment]
Thanks for noticing this!

This code is indeed amazingly broken because not only it calls `GetLength()` unnecessarily, but it also doesn't even use it correctly: the test should be `currentPos == size+pos` and not `size-pos` as it is right now.

I've just removed this check completely now as it's not clear if it's worth doing it at all. In the two other cases it's not obvious whether it's worth having the extra checks neither, but at least they do no harm, so keep them for now.
