### ISSUE TITLE
wxLogInterposerTemp does not what is described it should do (is effectively useless)

### ISSUE THREAD

**Issue by mcorino** [wxWidgets/wxWidgets#23945]
### Description
The documentation describes wxLogInterposerTemp as:

> It forwards log messages to the previously installed one in addition to processing them itself. Unlike wxLogInterposer, it doesn't delete the old target which means it can be used to temporarily redirect log output.

However:

1. Neither wxLogChain (it's direct parent) or wxLogInterposer ever delete the old target. What they do is **restore** the old target when deleted.
2. wxLogInterposerTemp calls in fact DetachOldLog with the result that logging is **NOT** forwarded to the previous (old) target anymore, unlike the docs tell us, **and** the old target is not restored anymore when deleted.

So in actuality installing a wxLogInterposerTemp derived log instance **prevents** log forwarding to the old target and does not delete the old target when deleted (or restore it) causing a memory leak.

I actually do not see a real use case for this class and it also lacks samples and/or tests.

### Platform and version information

- wxWidgets version  you use: master
- wxWidgets port  you use: all ports
- OS  and its version: any

**Comment by vadz** [comment]
Yes, it looks like these classes don't make any since since the changes of a16e51b56a (Restore the old logger in wxLogChain dtor instead of deleting it., 2010-10-30)...

`wxLogInterposer` itself (a.k.a. `wxLogPassThrough`, which was its name until 47fe7ff382 (Added DetachOldLog to avoid destruction of old log target Renamed wxLogPassThrough to wxLogInterposer Added wxLogInterposerTemp, 2007-06-21)) is just the same as `wxLogChain` while `wxLogInterposerTemp` is, as you say, pretty useless.

We should at least clearly mention explain this in the documentation and maybe deprecate these classes entirely...

**Comment by mcorino** [comment]
wxLogInterposer is not the same a wxLogChain  as this last class in intended to route to specifically specified log instance (and not to the wxLogChain instance itself) whereas wxLogInterposer (whoever came up with that name?) is intended to route to an instance of a derivative of this class itself (so no log instance to route to is specified).
Granted you could do (more or less) the same with wxLogChain by having a derivative of that class setting itself up as wxLogInterposer does but still this class provides something I could imagine a use case for without causing problems.
wxLogInterposerTemp creates memory leaks and it's implementation does not match the docs which would require to update the docs and the implementation for a class whose use is questionable to say the least.

So, I am strongly in favor of deprecating wxLogInterposerTemp asap (and update docs with advise in strong terms no to use this class).
As far as wxLogInterposer is concerned I do not see much harm in keeping it although deprecating it is also not a big thing.

**Comment by vadz** [comment]
> wxLogInterposer is not the same a wxLogChain as this last class in intended to route to specifically specified log instance (and not to the wxLogChain instance itself)

Well, it can do both.

> whereas wxLogInterposer (whoever came up with that name?)

For once it's not my fault, it was Julian in the commit linked above. My original name was `wxLogPassThrough` which I still think is better.

> wxLogInterposerTemp creates memory leaks and it's implementation does not match the docs which would require to update the docs and the implementation for a class whose use is questionable to say the least.
> 
> So, I am strongly in favor of deprecating wxLogInterposerTemp asap (and update docs with advise in strong terms no to use this class).

The problem is that there seems to be some existing code using it (I have no idea why nor what for), and I'm not sure if it's worth breaking this code by removing this class (which is supposed to happen in the next release after deprecating it). But I do agree that we should state in the documentation that it shouldn't be used.

**Comment by mcorino** [comment]
Ok, I'll leave that up to you.
I've excluded wxLogInterposerTemp from wxRuby to prevent future problems.
