### ISSUE TITLE
[wxGTK] Clipboard broken in wxSTC

### ISSUE THREAD

**Issue by eranif** [wxWidgets/wxWidgets#23988]
I pulled latest wxWidgets today (after I have been using 3.2 for a while now)
and noticed that the clipboard copy/paste is broken.

To reproduce:

- Open stctest
- select a text and hit `Ctrl-C`
- Paste it using `Ctrl-V` somewhere -> it works
- Now, select some other text in the editor
- De-select the newly selected text
- Hit `Ctrl-V` Expected: it should paste what you copied earlier. Actual: clipboard is empty

I suspect that this might be related to the secondary clipboard on Linux (copy selected text and paste it using mouse middle button)

This bug is seen using latest wxWidgets 3.3. (pulled today)
Note that this bug was reported on CodeLite issue tracker here: https://github.com/eranif/codelite/issues/3272 by two other users

Thanks

**Comment by yunkot** [comment]
I can reproduce this with wxWidgets 3.2.3 but not with wxWidgets 3.2.2.1, running on Arch / Xorg.

**Comment by uffejakobsen** [comment]
I can confirm that `stctest` exhibits the above described behavior with wxWidgets-3.2.3 on Arch Linux running under Xorg

**Comment by vadz** [comment]
Excellent, now we have not-Wayland-only bugs too :-( Because at least here I can only reproduce this when using Xwayland, not when running natively under Wayland (GNOME/mutter if it matters), which explains why I hadn't noticed when testing before.

Anyhow, the culprit is e972d01287 (Fix memory leak of wxClipboard data on exit, 2023-06-21) and reverting it fixes the problem. It would be nice to understand why does this happen, i.e. why does `gdk_selection_owner_get()` return null window in this case and also why does it still work under Wayland, but in the worst case we should just revert it as it's better to have a leak than non-working clipboard.

**Comment by vadz** [comment]
This should be fixed now in master and will be in 3.2 branch too soon.

**Comment by eranif** [comment]
great, thanks for the quick fix!
