### ISSUE TITLE
wxBitmapBundle from SVG renders incorrectly on wxGTK

### ISSUE THREAD

**Issue by teliseo** [wxWidgets/wxWidgets#24064]
### Description
If I set an icon in an generic About box on wxGTK from a wxBitmapBundle that was created from SVG, using any theme with a light-colored background, the anti-aliased edges have dark fringes, as if the objects were rendered on a dark background. This problem doesn't happen on wxOSX/Cocoa or wsMSW. See example below and screenshot attached.

This doesn't appear to be a problem with SVG rendering in general, since the object renders correctly with a background-matching object behind it (see commented out rectangle in example). Also, if I create the wxBitmapBundle from a PNG with alpha-channel transparency, rendering is also correct.

This appears to be a wxGTK bug. A bug fix would be great, but I’m also looking for a workaround that still allows me to use SVG art in the provided About box.

```
#include <wx/wx.h>
#include <wx/bmpbndl.h>
#include <wx/aboutdlg.h>
#include <wx/generic/aboutdlgg.h>

class MyApp: public wxApp
{
public:
    virtual bool OnInit();
};

wxIMPLEMENT_APP(MyApp);

class MyFrame : public wxFrame
{
public:
    MyFrame();
};

bool MyApp::OnInit()
{
    MyFrame *frame = new MyFrame();
    frame->Show();

    static char sample_icon[] = "<svg viewBox=\"0 0 1000 1000\">"
//      "<rect width=\"100%\" height=\"100%\" fill=\"#d4d4d4\"/>"
      "<circle cx=\"50%\" cy=\"50%\" r=\"45%\" fill=\"#B0E0E6\"/>"
      "</svg>";
    wxBitmapBundle bb = wxBitmapBundle::FromSVG(sample_icon, wxSize(256, 256));

    wxAboutDialogInfo aboutInfo;
    aboutInfo.SetName(" ");
    aboutInfo.SetIcon(bb.GetIcon(wxDefaultSize));

    wxGenericAboutDialog *about_dlg = new wxGenericAboutDialog(aboutInfo, frame);
    about_dlg->Show();

    return true;
}

MyFrame::MyFrame() : wxFrame(nullptr, wxID_ANY, "About test")
{
}
```
![About_SVG_bug_ss](https://github.com/wxWidgets/wxWidgets/assets/667606/31f8dabd-3696-40f9-9fe5-6f17a3d25bba)

### Platform and version information

- wxWidgets version you use: 3.2.2.1 (stock Fedora 39 package)
- wxWidgets port you use: wxGTK
- OS and its version: Fedora 39 Linux

+ GTK version: 3.24.38
+ Which GDK backend is used: X11
+ Current theme: MATE BlueMenta (but I've tried many others, and also with GNOME)

**Comment by teliseo** [comment]
Update: Upon further investigation, this problem isn’t restricted to GenericAboutDialog. Even this produces an incorrect image, but only with wxGTK:
```
    wxBitmapBundle bb = wxBitmapBundle::FromSVG(sample_icon, wxSize(256, 256));
    bb.GetBitmap(wxDefaultSize).SaveFile("bug_sample.png", wxBITMAP_TYPE_PNG);
```
I haven’t yet looked at the raw output of ``nsvgRasterize()``, which should be the same on all platforms. Could something be incorrect in the conversion to the wxGTK-specific wxBitmap?

**Comment by vadz** [comment]
Thanks, the code in `DoRasterize()` should almost certainly be changed for wxGTK (and other platforms not using premultiplied alpha). It would be nice to have some abstraction for this at `wxAlphaPixelData` level instead of just using platform checks in the code, however... We also need to add some unit tests to ensure that this works as expected.

**Comment by teliseo** [comment]
Attached is the patch I’ve been using for testing. I was ready to submit a pull request until I noticed there are _no_ unit tests for ``wxBitmapBundle::FromSVG()``, which might explain how this bug slipped by. I have one almost written to cover this case, but it seems like there should be more.

Maybe a setter could be added to ``wxAlphaPixelData::Iterator`` which takes all four components as parameters, and sets a pixel with platform-dependent premultiplication? It could also be used for ``wxCairoBitmapData`` and ``Scintilla``, which currently have platform-dependent switches. I don’t feel like this can be abstracted further, since there’s no round trip back to straight alpha that preserves the original pixel values.

Since ``FromSVG()`` is basically broken on wxGTK without this patch, maybe it’s better to get this in now and think about how to properly abstract things a little later?

[wx_nsvg_alpha.patch](https://github.com/wxWidgets/wxWidgets/files/13446346/wx_nsvg_alpha.patch)

**Comment by vadz** [comment]
Yes, sure, we need to fix this a.s.a.p., but OTOH if we don't provide a clean fix for it now, it risks to never happen at all, witness this hack:

https://github.com/wxWidgets/wxWidgets/blob/4e679c464982c9d197b54604bd32c1d16116aa09/src/stc/PlatWX.cpp#L395-L399

which is there since 6a93571daf (Provide an implementation for SurfaceImpl::AlphaRectangle, and rename [G|S]etCaretLineBack, 2006-08-31) and never got replaced by something cleaner :-(

Unfortunately I'm unavailable right now, but if you could please make a PR doing the following:

1. Define (and document) `wxHAS_PREMULTIPLIED_ALPHA` in `wx/rawbmp.h` for wxMSW, wxOSX and wxQt.
2. Use it in your patch.
3. Update `src/stc/PlatWX.cpp` to use `#ifdef wxHAS_PREMULTIPLIED_ALPHA`.
4. Update the code here to use it too: https://github.com/wxWidgets/wxWidgets/blob/4e679c464982c9d197b54604bd32c1d16116aa09/src/generic/graphicc.cpp#L1662

It would be very much appreciated, TIA!

**Comment by teliseo** [comment]
Yes, I can do that.
