### ISSUE TITLE
Why wxEVT_AUINOTEBOOK_BEGIN_DRAG event can only be caught by the dynamic binding, but not static macro event table binding

### ISSUE THREAD

**Issue by asmwarrior** [wxWidgets/wxWidgets#24118]
Hi, I just want to catch the wxEVT_AUINOTEBOOK_BEGIN_DRAG and wxEVT_AUINOTEBOOK_END_DRAG event. I'm using the aui sample code, this code does not work:

~~~~
    EVT_AUINOTEBOOK_BEGIN_DRAG(wxID_ANY, MyFrame::OnNotebookBeginDrag)
    EVT_AUINOTEBOOK_END_DRAG(wxID_ANY, MyFrame::OnNotebookEndDrag)
~~~~

I can't catch those two events by the old macro based table binding.

But the below code works:

~~~~
   // bind the event handler to the ctrl
    ctrl->Bind(wxEVT_AUINOTEBOOK_BEGIN_DRAG, &MyFrame::OnNotebookBeginDrag, this);
~~~~

Note the `ctrl` is the wxAuiNotebook pointer, which is just created inside the `wxAuiNotebook* MyFrame::CreateNotebook()` function.

So, here comes the question: why?

My guess is that 

~~~~
    EVT_AUI_RANGE(wxAuiBaseTabCtrlId, wxAuiBaseTabCtrlId+500,
                      wxEVT_AUINOTEBOOK_BEGIN_DRAG,
                      wxAuiNotebook::OnTabBeginDrag)
    EVT_AUI_RANGE(wxAuiBaseTabCtrlId, wxAuiBaseTabCtrlId+500,
                      wxEVT_AUINOTEBOOK_END_DRAG,
                      wxAuiNotebook::OnTabEndDrag)
~~~~
In the source code of the auibook.cpp, it just handle this event it self, but, I don't see the `event.Skip()` function call inside the `wxAuiNotebook::OnTabBeginDrag`, so the static macro based event map can't propagate the event to its parent (the wxFrame).

**Is this by design?**

Here are some reference links:

1, I try to catch those events because I would like to extent the code::blocks' wxAuiNotebook function to another monitor, I mean I need to create a new wxAuiNotebook, so I can drag the panels from on wxAuiNotebook to another. see: [Does Code::Blocks support multiple monitor editing?](https://forums.codeblocks.org/index.php/topic,25125.msg171323.html#msg171323)

2, it looks like I can' drag an editor to an empty wxAuiNotebook, see: [I can not drag a panel to an empty wxAuiNotebook from another wxAuiNotebook](https://github.com/wxWidgets/wxWidgets/issues/24111)

3, wxForum's discussion: [Why some of the wxAuiNotebook events only be caught by the derived class](https://forums.wxwidgets.org/viewtopic.php?f=1&t=50895)

Thanks.

**Comment by vadz** [comment]
These events are sent to `wxAuiNotebook` which always handles them, so they don't bubble up to the parent frame. It could skip them, e.g. this patch:

```diff
diff --git a/src/aui/auibook.cpp b/src/aui/auibook.cpp
index 5931186b1b..354fe699b8 100644
--- a/src/aui/auibook.cpp
+++ b/src/aui/auibook.cpp
@@ -2573,8 +2573,9 @@ void wxAuiNotebook::OnTabBgDClick(wxAuiNotebookEvent& evt)
     ProcessWindowEvent(e);
 }
 
-void wxAuiNotebook::OnTabBeginDrag(wxAuiNotebookEvent&)
+void wxAuiNotebook::OnTabBeginDrag(wxAuiNotebookEvent& evt)
 {
+    evt.Skip();
     m_lastDragX = 0;
 }
 
```

solves the problem for the first event, but it's not really obvious if it should do it, especially for the `END_DRAG` event which it does actually handle.

So I think the current situation is more or less by design: like with any control processing its own events, you can `Bind()` to them on the control itself, but you only get the events not processed by the control in its parent window.

The surprising thing here is that `wxAuiNotebook` handles (i.e. processes without skipping) all its events, but I don't think it's a great idea to change it, so let's just document this and recommend that people use `Bind()`.
