### ISSUE TITLE
fatal error: d2d1.h: No such file or directory

### ISSUE THREAD

**Issue by laomaolaile** [wxWidgets/wxWidgets#24205]
https://wiki.codeblocks.org/index.php/Installing_Code::Blocks_from_source_on_Windows
I compiled wxWidgets based on this document, but kept compiling with errors.
![image](https://github.com/wxWidgets/wxWidgets/assets/19726057/a109ab5f-ea00-427b-8b85-ab7bebdacaf9)

What should I do? Do I need to install any tools? Or is there a problem with some of my configuration files?

I hope somebody can give me the right advice, thank you!

**Comment by laomaolaile** [comment]
My computer is Windows 10 and I have installed winGW 0.6.2
![image](https://github.com/wxWidgets/wxWidgets/assets/19726057/9d73ec13-cce2-4999-952b-eddb2a9249fe)

**Comment by PBfordev** [comment]
Firstly, I would recommend reading the official docs on building wxWidgets instead of the Code::Blocks one (unless you really want to compile C::B on your own).

Secondly, your MinGW distribution does not support Direct2D (i.e., does not ship with the headers and libraries for the API). Either use a better MinGW distribution (based on mingw-64, such as WinLibs or MSYS2) or do not attempt to build wxWidgets with `wxUSE_GRAPHICS_DIRECT2D=1`.

FWIW, I wrote [a guide](https://github.com/PBfordev/wxpbguide) on building wxWidgets with MinGW and setting-up a C::B project using wxWidgets.

**Comment by vadz** [comment]
The comment above answers the question, so closing.
