### ISSUE TITLE
Deriving from wxQtSignalHandler (decision needed)

### ISSUE THREAD

**Issue by AliKet** [wxWidgets/wxWidgets#24207]
None of the following classes need or benefit from deriving from `wxQtSignalHandler` :

`class wxQtActionGroup` : https://github.com/wxWidgets/wxWidgets/blob/5dac42edc07f6e504ecc9b5a9cbb1c559ca9319c/src/qt/menu.cpp#L28

`class wxQtAction` : https://github.com/wxWidgets/wxWidgets/blob/5dac42edc07f6e504ecc9b5a9cbb1c559ca9319c/src/qt/menuitem.cpp#L21

`class wxQtShortcutHandler` : https://github.com/wxWidgets/wxWidgets/blob/5dac42edc07f6e504ecc9b5a9cbb1c559ca9319c/src/qt/window.cpp#L221

I propose to drop the `wxQtSignalHandler` from the derivation list and simplify the classes implementations.

### Motivation:

We don't have to change `EmitEvent()` implementation
https://github.com/wxWidgets/wxWidgets/blob/5dac42edc07f6e504ecc9b5a9cbb1c559ca9319c/include/wx/qt/private/winevent.h#L38-L45
and continue to assume that the handler is a `wxWindow`.

------------------------------------------------------------------------

**Edit:**

The handlers of the following classes are `wxWindow`s derivatives, so no changes are done for them:

`class wxQtButtonGroup` : https://github.com/wxWidgets/wxWidgets/blob/5dac42edc07f6e504ecc9b5a9cbb1c559ca9319c/src/qt/radiobox.cpp#L29

`class wxQtToolButton` : https://github.com/wxWidgets/wxWidgets/blob/5dac42edc07f6e504ecc9b5a9cbb1c559ca9319c/src/qt/toolbar.cpp#L56

**Comment by vadz** [comment]
`wxQtSignalHandler` is clearly intended to work only with `wxWindow`, so it should be restricted to them only. What I don't understand is why does it take a `wxEvtHandler` and not a `wxWindow` in the first place, IMO this should be changed too.

I'd also recommend changing `static_cast` to `wxStaticCast` to get asserts instead of (or at least before) the crash, but this is less important, of course.
