### ISSUE TITLE
wxDataViewCustomRenderer size not applied on wxGTK in some cases.

### ISSUE THREAD

**Issue by dsa-t** [wxWidgets/wxWidgets#24227]
See a minimal example:

[minimal.cpp.txt](https://github.com/wxWidgets/wxWidgets/files/13991527/minimal.cpp.txt)

`LIB_TREE_RENDERER` returns height 30 in `GetSize()`, but cells are not sized to height 30 in `Render()`.
Instead, they seem to use height 16 (font: Ubuntu 10).

If DPI is changed in system settings (**Appearance - Fonts - DPI - Custom DPI setting** in Mint), then cells are updated to height 30, but only the ones that are visible.

If you scroll down, you can see other cells still with height 16.

wx is built with `DEBUG_RENDER_EXTENTS` on screenshots.

Expected is for all cells to have height 30.

Initial state:
![image](https://github.com/wxWidgets/wxWidgets/assets/37658952/3c10c54e-5be2-4135-8ef7-6b0e770f5c79)

After changing DPI:
![image](https://github.com/wxWidgets/wxWidgets/assets/37658952/ae5a46cd-9fbf-4bef-9298-bcf56514b3ae)

Scroll down:
![image](https://github.com/wxWidgets/wxWidgets/assets/37658952/413f0641-0c60-4ddb-8dcc-d64bf494d3c2)

### Platform and version information

- wxWidgets version  you use: 3.2; master
- wxWidgets port  you use: wxGTK
- OS  and its version: Linux Mint 21.1
  
  + GTK version: 3.24.33-1ubuntu2
  + Which GDK  backend is used: X11
  + Desktop environment : XFCE
  + Current theme:  Mint-Y-Aqua

**Comment by vadz** [comment]
Thanks, I can indeed see this, will check.

**Comment by vadz** [comment]
First observations are that neither using `wxDV_VARIABLE_LINE_HEIGHT` nor calling `SetRowHeight(30)` help.

And looking at GTK code here

https://github.com/GNOME/gtk/blob/3e6fd55ee00d4209ce2f2af292829e4d6f674adc/gtk/gtkcellrenderer.c#L1419-L1423

it seems that it always uses the minimum of the height we return and its pre-computed height. I don't see how can we avoid this...

**Comment by dsa-t** [comment]
Maybe it's possible to override `get_aligned_area` similar to `gtk_cell_renderer_text_get_aligned_area` (gtkcellrenderertext.c)?

**Comment by dsa-t** [comment]
btw, the effect can be seen in KiCad sometimes (https://forum.kicad.info/t/symbol-chooser-text-is-only-shown-half-line-height/49677)

Even if we call `SetRowHeight` (https://gitlab.com/kicad/code/kicad/-/commit/c3af434741b9e7ca1bca440b466f1a8328d8283e)

**Comment by vadz** [comment]
Sorry, I still have no idea what to do about it. I'm starting to seriously consider stopping using the native control under GTK and using the generic version by default instead, notably because there is still no way to use the native one with many items and apparently never going to be.

It's still possible that I'm missing something because it seems incredible for such an important control to be so broken, but I have no idea what.

@paulcor What do you think of using the generic control in wxGTK by default?

**Comment by paulcor** [comment]
For our own application, we went to using the generic `wxDataViewCtrl` for all platforms. I don't remember all the issues, but for wxGTK, #17909 is a deal killer, and I believe there were several problems with the native wxOSX control as well.

> this means that we can only increase the row height by changing the expander size

I don't know much about `wxDataViewCtrl`, but it seems like the renderer size does affect the row height, as can be seen with this change to the `dataview` sample:
```diff
diff --git a/samples/dataview/dataview.cpp b/samples/dataview/dataview.cpp
index c15f2b3ad4..0683fdb209 100644
--- a/samples/dataview/dataview.cpp
+++ b/samples/dataview/dataview.cpp
@@ -271,7 +271,7 @@ public:
 
     virtual wxSize GetSize() const override
     {
-        return GetView()->FromDIP(wxSize(60, 20));
+        return GetView()->FromDIP(wxSize(60, 60));
     }
 
     virtual bool SetValue( const wxVariant &value ) override
```

**Comment by vadz** [comment]
For me the deal breaker is #16680, this control simply can't be used with mailboxes containing 100,000 messages — when `wxListCtrl` or the generic version have no trouble whatsoever with it. I still have no idea how do other programs using GTK deal with showing big/"infinite" number of items in this control and I think that if we can't make this work, we should stop using it.

But, to return to this issue, you're right, changing the height does work. And now I'm extremely confused because I remember it not working for me, but not only it does in the sample now, but it also does in the provided example.

I'm testing with the latest master but there haven't been any changes affecting this since a very long time and yet I don't see the problem any more, neither with Wayland nor X11.

@dsa-t Do you still see it?

**Comment by dsa-t** [comment]
In 3.2.5, the provided `minimal.cpp.txt` still behaves the same for me.

With this in `MyCustomRenderer` in `dataview`, row heights are inconsistent:
```cpp
    virtual wxSize GetSize() const wxOVERRIDE
    {
        return GetView()->FromDIP(wxSize(60, 30));
    }
```

Initial state:

![image](https://github.com/wxWidgets/wxWidgets/assets/37658952/2bdd541f-24a0-4e73-a49c-0185e837b7f4)

After DPI change:

![image](https://github.com/wxWidgets/wxWidgets/assets/37658952/7c428425-b30b-497a-accc-15077fc414f9)

**Comment by dsa-t** [comment]
`master` branch behaves the same for me.

**Comment by vadz** [comment]
Sorry, maybe I'm blind, but I don't understand what do these screenshots show: don't they show that the height _does_ change? Is the problem just that the expander row (which doesn't use the custom renderer...) size doesn't change?

Also, what's the difference between the 2 screenshots (in different DPIs)?

**Comment by dsa-t** [comment]
> expander row (which doesn't use the custom renderer...)

`MyCustomRenderer` in the `dataview` sample is passed to `wxDataViewColumn` ctor, not to rows.
So it looks like even expander rows should have the height of 30.

On the first screenshot you can see that expander rows have height 22, not 30.

After very slight DPI change, on the second screenshot, heights of expander rows were updated to 30, as expected.

**Comment by dsa-t** [comment]
On MSW, the renderer's size doesn't matter, unless `wxDV_VARIABLE_LINE_HEIGHT` flag is set. Then it looks like this:

![image](https://github.com/wxWidgets/wxWidgets/assets/37658952/8fb23a2f-9e0d-4cef-b3af-3333202fac2b)

**Comment by vadz** [comment]
After returning to this, I've quickly discovered that the reason the reproducer here is broken but the sample is not (or at least not as much) is that returning 0 width, even if only _once_, from `GetSize()` somehow prevents the height from being _ever_ taken into account — and the example here returns 0 the first couple of times when it's called.

I've created the PR linked above with the proposed (ugly) workaround which makes things work for me. Please let me know if you see any problems with it, otherwise I'll merge it soon (and backport to 3.2, as you probably need it there, right?).

**Comment by dsa-t** [comment]
The fix works on my system. Please backport to 3.2 if possible.
