### ISSUE TITLE
Non-unique values in wxKeyCode enum

### ISSUE THREAD

**Issue by imciner2** [wxWidgets/wxWidgets#24254]
### Description

Inside the wxKeyCode enum, there are two names assigned to the same numerical values of 8, 9, 13 and 27, specifically the `WXK_BACK`, `WXK_TAB`, `WXK_RETURN` and `WXK_ESCAPE` values overlap with various `WXK_CONTROL_*` enum entries.

We noticed this because `WXK_CONTROL_I` is overlapping with `WXK_TAB`, so we see an overlap between the two: https://gitlab.com/kicad/code/kicad/-/issues/12992. Specifically, when we process a key event we call `GetKeyCode()` and `IsKeyInCategory( WXK_CATEGORY_TAB )`. For the case of a user pressing `Ctrl + I`, the key code returned is the numerical value `9`, which maps to both `WXK_TAB` and `WXK_CONTROL_I`, and the second function returns `true` because it checks if the value of `GetKeyCode()` is `WXK_TAB` to match the category. This means the key was identified as a tab key press instead of a letter key press.

This can be seen by examing the defs header file: https://github.com/wxWidgets/wxWidgets/blob/ac3cea5bcd5a3fc3d52648efb4dceacbcc9d0698/include/wx/defs.h#L2168-L2202

Unfortunately, I don't know if this can be fixed in any meaningful way :(
Because changing the enum values is probably going to be breaking (and is probably silently breaking).

### Platform and version information

- wxWidgets version  you use: Master (and 3.2)
- wxWidgets port  you use: wxGTK
- OS  and its version:
  
  + GTK version: 
  + Which GDK  backend is used:
  + Desktop environment :
  + Current theme:

**Comment by oneeyeman1** [comment]
@imciner2 ,
Those 2 are interchangeable.
If you press Ctrl+I and check whether the Ctrl key is pressed - what do you get?

Thank you.

**Comment by vadz** [comment]
This is indeed intentional because `Ctrl-I` is the same thing as TAB, traditionally.

I think this should be easy to fix at KiCad level by just performing this check in `KEY_DOWN` event instead of the `CHAR` one, as no translation is done for the former.

But we can also fix this in `IsKeyInCategory()` itself, albeit in a rather ugly, because it has to be platform-specific, way, see #24258. AFAICS this should fix your problem and is arguably the more correct thing to do, but I'd still recommend not using `wxEVT_CHAR` if you don't want these translations to happen.

**Comment by imciner2** [comment]
> This is indeed intentional because Ctrl-I is the same thing as TAB, traditionally.

What is the history behind this? I hadn't heard of this convention, and it seems odd to me for the producer to define two things as equivalent instead of the consumer doing the mapping.

> But we can also fix this in IsKeyInCategory() itself, albeit in a rather ugly, because it has to be platform-specific, way, see https://github.com/wxWidgets/wxWidgets/pull/24258. AFAICS this should fix your problem and is arguably the more correct thing to do, but I'd still recommend not using wxEVT_CHAR if you don't want these translations to happen.

I've built KiCad (with the operator overload changes reverted) against this branch, and now we differentiate between Ctrl+I and Ctrl+Tab properly in our hotkey system, so we no longer see the error referenced in the issue, and we can use Ctrl+I as a hotkey in our system.

As for why we use `EVT_CHAR`, that is legacy, and I am not completely sure. I recall some discussions on old issues of ours that there were some problems in the past where the translation/mapping performed before the `EVT_KEY_DOWN` was actually a problem, and as it stands, we have problems handling some shift-based symbol keys on international keyboards. Eventually we will probably have to revisit all of this and see what is/isn't a problem on newer OS versions/wx library versions.

**Comment by vadz** [comment]
> What is the history behind this?

Well, TAB _is_ `Ctrl-I` in ASCII: all control codes in ASCII are `Ctrl` plus the corresponding letter, from `A` to `[` (which is `Esc`). So all Unix terminal emulators have always sent the same code for both `TAB` and `Ctrl-I`, for example, and so on -- which is why even Windows does this translation and you get `WM_CHAR` with `TAB` key code from it when pressing `Ctrl-I`.

Anyhow, thanks for testing and I'll merge my hack soon then.
