### ISSUE TITLE
wxprec.h not working when using wxWidgets 3.2 from vcpkg with Visual Studio 2022 

### ISSUE THREAD

**Issue by hajokirchhoff** [wxWidgets/wxWidgets#24353]
### Build System Used
I build wxWidgets and/or my application using:

- [X] vcpkg / CMake
- [ ] configure
- [ ] mingw32-make with makefile.gcc
- [X] MSBuild (Microsoft Visual Studio solution file)
- [ ] nmake with makefile.vc
- [ ] Xcode

### Description
My application compiles fine with a custom buildscript for wxWidgets 3.0.5 using plain "nmake" under Windows.
I am in the process of updating my application to use wxWidgets 3.2.4 from the vcpkg port.
My application uses precompiled header files and includes `wxprec.h` to include the most common wxWidgets headers.

My problem is that now I get thousands (literally) of undefined symbols, because standard headerfiles such as `wx/stattext.h` or `wx/menu.h`, which used to be included automatically in `wx/wxprec.h` are not longer included. `#include "wx/wxprec.h` doesn't really do anything anymore.

The problem is that WX_PRECOMP will no longer get defined. My guess is that thats because the vcpkg port builds wxWidgets with vcpkg_cmake_configure.

The wxprec.h contains a somewhat cryptic comment: https://github.com/wxWidgets/wxWidgets/blob/f24b3d54833a1c15ae3bba87dead83bf9a90c41d/include/wx/wxprec.h#L16

Blame (https://github.com/wxWidgets/wxWidgets/commit/248eaddf7a14cefa161d514763e8fefb8d6f2f79) shows that this was added in 2005
// If user did not request NOCPH and we're **not building using configure**
    // then assume user wants precompiled headers.
    #if !defined(NOPCH) && !defined(\_\_WX_SETUP_H__)
        #define WX_PRECOMP
    #endif

In other words, if \_\_WX_SETUP_H__ is defined (which is supposedly the case when building with configure), WX_PRECOMP will not be defined and subsequently all the usual wx header files will also not be included.

I couldn't find any comments or infos on why this has been added to `wxprec.h`. I really have no idea why the original author wanted to prevent precompiled headers when building with configure.

My Question: 
- Why is this necessary? 
- And how should the vcpkg port be modified so that wxprec.h will work again when using it from vcpkg with Visual Studio?

As a workaround I can define the WX_PRECOMP symbol in a Directory.build.props for all projects using wxWidgets, but I think vcpkg builds should work like "normal" builds.

### Platform and version information

- wxWidgets version 3.2.4
- wxWidgets port wxMSW
- OS Windows 11
- Compiler MSVS 2022
- vcpkg January 2024

**Comment by vadz** [comment]
I'm not sure what the motivation was for adding check for configure inside `#if defined(__VISUALC__)` (which didn't look quite like this back then but was still present) neither and I guess we probably could remove it, but for me the real question is why/where is `__WX_SETUP_H__` predefined when using vcpkg? Because it almost certainly shouldn't be and defining it might result in other problems too...

So my preferred solution would be to stop defining `__WX_SETUP_H__`. If this is impossible or undesirable for some reason, we could consider removing `&& !defined(__WX_SETUP_H__)` part of the check -- AFAICS this shouldn't break anything, and if it somehow does, defining `NOPCH` would be enough to fix it.

And, finally, for now, predefining `WX_PRECOMP` would work too, of course.

**Comment by hajokirchhoff** [comment]
I did some digging and there are several different versions of setup.h installed. 

   _include/wx/setup.h_ simply redirects to _**lib/mswu**/wx/setup.h_ (and its debug variant). This is the one that defines \_\_WX_SETUP_H__ (note two underlines) and disables WX_PRECOMP

But another one is installed at _**include**/wx/**msw**/setup.h_ and that one is different. It defines \_WX_SETUP_H_ (note one underline). It also has different #defines than the one in _lib/mswu_.

The include paths tell the compiler to use the one from _lib/mswu_ (or _debug/lib/mswu_).

vcpkg uses pkgconfig to build wxwidgets and I am guessing that setup.h is produced by pckconfig.

BTW, where is the repository for the vcpkg port files for wxWidgets?

**Comment by hajokirchhoff** [comment]
So basically there are two conflicting setup.h installed on the system.  _lib/mswu/wx/setup.h_ gets used and disables WX_PRECOMP and is different from _include/wx/msw/setup.h_.

**Comment by vadz** [comment]
The file under `lib` is the normal/correct file and is the one included by `include/wx/setup.h`, there should be no `include/wx/msw/setup.h` at all and it would be really great if vcpkg could avoid installing it because this makes things even more confusing. The relevant files are in vcpkg repository at https://github.com/microsoft/vcpkg/commits/master/ports/wxwidgets and if you can fix this, it would be great, of course.

However this still doesn't answer the question of why is `__WX_SETUP_H_` getting defined. I don't know what do you mean by "uses pkgconfig to build wx" because for me [pkg-config](https://www.freedesktop.org/wiki/Software/pkg-config/) is just a helper used when building and can't be used to build anything, and while it's often used with autoconf, I'd be very surprised if vcpkg used configure to build (but then I really have no idea). And if it doesn't, defining this symbol is definitely wrong and should be avoided.

**Comment by hajokirchhoff** [comment]
I'll open a ticket on the vcpkg repository then. 

What I mean by "uses pkgconfig to build" is that pkgconfig is involved and I thought the comment in wxprec.h meant: "If wxWidgets is built with something that uses "configure" then don't use wxprec". Which I think would be wrong.

Here is the relevant portion of the portfile.cmake from the vcpkg port that calls pkgconfig:

```
vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS
        ${FEATURE_OPTIONS}
        -DwxUSE_REGEX=sys
        -DwxUSE_ZLIB=sys
...
        -DwxUSE_SECRETSTORE=OFF
        -DwxUSE_STL=${WXWIDGETS_USE_STL}
        -DwxUSE_STD_CONTAINERS=${WXWIDGETS_USE_STD_CONTAINERS}
        -DwxUSE_UIACTIONSIMULATOR=OFF
        -DCMAKE_DISABLE_FIND_PACKAGE_GSPELL=ON
        -DCMAKE_DISABLE_FIND_PACKAGE_MSPACK=ON
        ${OPTIONS}
        "-DPKG_CONFIG_EXECUTABLE=${PKGCONFIG}"
        # The minimum cmake version requirement for Cotire is 2.8.12.
        # however, we need to declare that the minimum cmake version requirement is at least 3.1 to use CMAKE_PREFIX_PATH as the path to find .pc.
        -DPKG_CONFIG_USE_CMAKE_PREFIX_PATH=ON
    OPTIONS_RELEASE
        ${OPTIONS_RELEASE}
    MAYBE_UNUSED_VARIABLES
        CMAKE_DISABLE_FIND_PACKAGE_GSPELL
        CMAKE_DISABLE_FIND_PACKAGE_MSPACK
)
```

So the vcpkg port is using cmake_configure then cmake_install to build and install everything.

My guess is that calling pkgconfig is somehow responsible for a setup.h that defines `\_\_WX_SETUP_H__` with two underlines instead of one.

I've since found two more problems with the port file. It seems that WXWIDGETS_USE_STL and WXWIDGETS_USE_STD_CONTAINERS is not being honored. Even if I define them in the way the portfile suggests I do, wxWidgets will not be built with them.

Like I said, I'll open a ticket there then and hope that the maintainers @dg0yt and @monicaliu0311 can shed more light on this.

**Comment by dg0yt** [comment]
There is https://github.com/wxWidgets/wxWidgets/blob/bf971fb0a8d4b461641bae529189a3c75fb168ea/build/cmake/setup.h.in#L4

The installed files are mostly chosen by wxwidget's cmake build system. The vcpkg port may do some fixup for vcpkg particularities (like sharing one set of includes for release and debug, or hardcoding DLL linkage for VS users).

I suggest providing minimal reproducible examples. The guessing around pkgconfig isn't helpful.

**Comment by vadz** [comment]
> There is [wxWidgets/build/cmake/setup.h.in](https://github.com/wxWidgets/wxWidgets/blob/bf971fb0a8d4b461641bae529189a3c75fb168ea/build/cmake/setup.h.in#L4)

Oops, thanks, I didn't know about this one.

@MaartenBent It looks wrong to define this here and it also seems like all CMake users should be affected by this problem (not using PCH out of the box), i.e. that it's not vcpkg-specific at all. Can we just remove this definition or does CMake build system rely on it anywhere (I can't find anything with a simple grep, but this is not really conclusive)?

> I suggest providing minimal reproducible examples.

I think a minimal example would be just

```cpp
#include <wx/wxprec.h>

wxWindow* window = nullptr; // Will fail to compile without PCH support.
```

BTW, this is why all our samples actually use this instead:

```cpp
// For compilers that support precompilation, includes "wx/wx.h".
#include "wx/wxprec.h"

// for all others, include the necessary headers (this file is usually all you
// need because it includes almost all "standard" wxWidgets headers)
#ifndef WX_PRECOMP
    #include "wx/wx.h"
#endif
```

as then everything gets included whether PCH are used or not.

----

Finally, I'm sorry for saying that `include/wx/msw/setup.h` shouldn't be included, this was just my mistake, I've somehow missed the "msw" in the path. This file *is* needed and used, it's `include/wx/setup.h` which shouldn't exist. I don't want to edit my comment above to avoid creating even more confusion but please forget that I wrote this.

**Comment by MaartenBent** [comment]
I think it is there because the file was a copy of the main `setup.h.in`. The CMake build system itself doesn't use it.
Do you want to replace it with `_WX_SETUP_H_` like the other `setup.h` files?

Maybe make sure that running `update-setup-h` does not undo the change.

**Comment by MaartenBent** [comment]
`setup.h.in` is used by configure to generate `setup.h`.
`build/cmake/setup.h.in` is used by CMake to generate `setup.h`.
When installing, this `setup.h` is put in `lib/<compiler>/mswu<d>/wx/setup.h`.

The msvc solutions (and makefile.gcc/vc) don't generate a `setup.h`, but use the existing `include/wx/msw/setup.h` and copy this to `lib/<compiler>/mswu<d>/wx/setup.h`.

These files are a bit different, but should both have all the required defines.
Because the `setup.h.in` used by CMake is based on a copy of the one used for configure, it contains `#define __WX_SETUP_H__`.  Which we now discovered is wrong.
