### ISSUE TITLE
Resource compilation on msw

### ISSUE THREAD

**Issue by MapleLeaf-X** [wxWidgets/wxWidgets#24504]
### Build System Used

I build wxWidgets and/or my application using:

- [ ] CMake
- [ ] configure
- [ ] mingw32-make with makefile.gcc
- [ ] MSBuild (Microsoft Visual Studio solution file)
- [x] nmake with makefile.vc
- [ ] Xcode

### Description

rc.exe is missing /nologo flag. it might affect cmake as well but I haven't tested it.

### Platform and version information

- wxWidgets version  you are building: 3.3.0 (latest)
- wxWidgets port  you are building: wxMSW
- OS  and its version: Windows 10
- Compiler  being used: MSVS 2022
- Non-default compiler options, if any : None

**Comment by PBfordev** [comment]
> rc.exe is missing /nologo flag. it might affect cmake as well but I haven't tested it.

Could you please explain what exactly is the issue here, i.e., what errors/warnings/undesired behavior are you seeing?

Unlike the compiler and linker (cl.exe and link.exe), the resource compiler (rc.exe) [does not support](https://learn.microsoft.com/en-us/windows/win32/menurc/using-rc-the-rc-command-line-) /nologo argument.

**Comment by MapleLeaf-X** [comment]
Yeah it isn't technically an issue but I do consider it somewhat of a bug.

**Comment by vadz** [comment]
It seems too difficult to use the option only for `rc` versions that support it, so I don't think we're ever going to do it, especially considering that it's not really a problem in the first place, sorry.
