### ISSUE TITLE
Very thick wxSearchCtrl border in the dark mode

### ISSUE THREAD

**Issue by DueTo250** [wxWidgets/wxWidgets#24625]
wxSearchCtrl  have a very thick border in the dark mode. Also, the magnifier icon looks so fat
![search-box-dark](https://github.com/wxWidgets/wxWidgets/assets/173275846/5234e6b4-cfe8-4146-ac97-9257559ad044)

OS: Windows 11 23H2

**Comment by vadz** [comment]
The first issue is addressed by the PR above. The second one is more difficult because the current icon drawing code is pretty impenetrable and can't be easily adjusted to high DPI. I think the best would be to get rid of it entirely and use fixed icons for this control instead, e.g. here is a [nice zoom icon](https://uxwing.com/search-line-icon/) and here is a [cancel icon](https://uxwing.com/close-round-line-icon/) similar to what we have now.

**Comment by vadz** [comment]
As we have a separate issue (referenced above) for the second problem, I've finally closed this after merging the PR fixing the first one.
