### ISSUE TITLE
Clipboard problem under KDE neon

### ISSUE THREAD

**Issue by unxed** [wxWidgets/wxWidgets#24701]
Steps to reproduce:

1. Download latest KDE neon ISO:
https://neon.kde.org/download
(I used neon-user-20240530-0715.iso for testing)

2. Install system in virtual machine (I used virt-manager & qemu) with default settings

3. Build wxWidgets with default settings

4. Build and run `text` sample

5. Select `Next 10 characters should be in blue` string in `text` sample window

6. Menu, Clipboard, Copy

7. Run Kate text editor

8. Try to paste

Additionally, you can run Konsole terminal emulator and type
`sudo apt install wl-clipboard`
and
`wl-paste -l`
to see the source of a problem:
```
$ wl-paste -l
UTF8_STRING
```

`UTF8_STRING` is x11 atom, but neon uses Wayland, and most apps do not expect such atom under Wayland, it should be `text/plain;charset=utf-8` instead.

**Comment by unxed** [comment]
Touch #23544, #23650, #24444, #24391, #23650

**Comment by paulcor** [comment]
Not KDE specific, I can reproduce a clipboard problem with Weston. There is also a second problem: `FindFocus()` isn't working, which is making the described test using the `text` sample invalid. You can avoid the `FindFocus()` problem by using the top center control in the `text` sample, which has the text starting "Prepended". Copying text from that control with the menu command doesn't work with Wayland, `wl-paste -l` just prints `TIMESTAMP`.

**Comment by vadz** [comment]
For me selecting the text in the control with "Prepended" and using "Clipboard > Copy" from the menu results in

```console
% wl-paste -l         
text/plain;charset=utf-8
UTF8_STRING
```

as expected. This is under Sway and not Weston or Kwin, however.

However I have no idea how can the behaviour of the code depend on the compositor and it's pretty bad news if it does :-( Are you testing with master?

**Comment by unxed** [comment]
> Are you testing with master?

yep

**Comment by vadz** [comment]
I can reproduce it with Weston, looking.

**Comment by vadz** [comment]
It looks like under Weston calling `gtk_selection_add_target()` only works the first time we do it, somehow, which is why only `TIMESTAMP` appears in `wl-paste -l` output: if I remove the call to `AddSupportedTarget(g_timestampAtom)` I do see `UTF8_STRING`, and if I hack the code to add `text/plain;charset=utf-8` instead, I see it too and copying it works, but this is surely not the right thing to do, as it will break something else.

Also, it looks like Weston behaves differently from kwin, so it might not even work for the latter. And it seems pretty weird that `gtk_selection_add_target()` does this in the first place, as it delegates to `gdk_wayland_selection_add_targets()` which [just calls](https://github.com/GNOME/gtk/blob/3e6fd55ee00d4209ce2f2af292829e4d6f674adc/gdk/wayland/gdkselection-wayland.c#L1821-L1826) `wl_data_source_offer()` which is supposed to add the format to the list of supported ones, without replacing them.

FWIW I've tried calling the (internal) `gdk_wayland_selection_add_targets()` directly with all our atoms at once too and it did make all of them available — but copying still didn't work. Maybe I should try with `gtk_selection_add_targets()` but, again, I just don't understand what is wrong with our current code at all.

**Comment by vadz** [comment]
OK, so using using `gtk_selection_add_targets()` does work with Weston, see #24845.

@unxed Could you please test it with KDE?

**Comment by unxed** [comment]
Still reproduced with #24845 applied :(

![изображение](https://github.com/user-attachments/assets/613238dd-852b-478e-9a06-33455e596051)

**Comment by vadz** [comment]
OK, I've got the Neon live CD and, as I suspected, adding MIME type format manually like this

```diff
diff --git a/src/gtk/clipbrd.cpp b/src/gtk/clipbrd.cpp
index 459c59bba0..45627dea3a 100644
--- a/src/gtk/clipbrd.cpp
+++ b/src/gtk/clipbrd.cpp
@@ -47,6 +47,7 @@ static GdkAtom  g_timestampAtom   = nullptr;
 
 // This is defined in src/gtk/dataobj.cpp.
 extern bool wxGTKIsSameFormat(GdkAtom atom1, GdkAtom atom2);
+extern GdkAtom wxGTKGetAltFormat(GdkAtom atom);
 
 static wxString wxAtomName(GdkAtom atom)
 {
@@ -701,6 +702,8 @@ bool wxClipboard::AddData( wxDataObject *data )
 #endif // __WXGTK3__
 
         atomNames.push_back(wxAtomName(format));
+        if ( GdkAtom altFormat = wxGTKGetAltFormat(format) )
+            atomNames.push_back(wxAtomName(altFormat));
     }
 
     std::vector<GtkTargetEntry> targets(atomNames.size());
diff --git a/src/gtk/dataobj.cpp b/src/gtk/dataobj.cpp
index 6676a4a705..327e39afff 100644
--- a/src/gtk/dataobj.cpp
+++ b/src/gtk/dataobj.cpp
@@ -188,6 +188,22 @@ extern bool wxGTKIsSameFormat(GdkAtom atom1, GdkAtom atom2)
     return false;
 }
 
+// Also used by wxClipboard to check for the alternative atom to use for text
+// formats.
+extern GdkAtom wxGTKGetAltFormat(GdkAtom atom)
+{
+    if (atom == g_u8strAtom)
+        return g_u8textAtom.Get();
+    if (atom == g_u8textAtom)
+        return g_u8strAtom.Get();
+    if (atom == g_strAtom)
+        return g_textAtom.Get();
+    if (atom == g_textAtom)
+        return g_strAtom.Get();
+
+    return nullptr;
+}
+
 bool wxDataFormat::operator==(const wxDataFormat& other) const
 {
     if ( m_type != other.m_type )
```

fixes the problem.

But I have absolutely *no* idea why do we need to do it there, when GDK clearly [already adds these MIME types](https://github.com/GNOME/gtk/blob/3e6fd55ee00d4209ce2f2af292829e4d6f674adc/gdk/wayland/gdkselection-wayland.c#L1812-L1815) itself. Could this distribution have modified GDK?

**Comment by vadz** [comment]
Oh, the mystery is explained much more easily: this code in GDK is only there since 3.24.35 and this is based on Ubuntu 22.04 which used 3.24.33.

So we do need to do this for older GTK versions, I'll cleanup the patch above and push it soon.

**Comment by unxed** [comment]
Great, thanks! This fix probably sound be added to the next minor release also, right?
