### ISSUE TITLE
wxHyperlinkCtrl doesn't respond to dark mode on MacOS

### ISSUE THREAD

**Issue by jey5nd6** [wxWidgets/wxWidgets#24719]
Or at least if it does, it does so with a colour that's very hard to read.

See: https://gitlab.com/kicad/code/kicad/-/issues/18427

![](https://gitlab.com/-/project/15502567/uploads/cdf449bdc3f4b1d3ee18099403c5e8e4/Screenshot_2024-07-21_at_08.59.24.JPG)

### Platform and version information

Platform: macOS Sonoma Version 14.4.1 (Build 23E224), 64 bit, Little endian, wxMac
wxWidgets: 3.2.5 (wchar_t,wx containers)

**Comment by vadz** [comment]
This was (supposed to be) already fixed in master in 082b19f863 (Use more appropriate colour for wxHyperlinkCtrl in dark mode, 2023-05-15), at least this is how this control looks to me now in the widgets sample:

![image](https://github.com/user-attachments/assets/0c8d9b5a-1cd1-422d-b051-850374161d71)

I've partially cherry-picked this to 3.2 now and made it part of #24706, so I think this can be closed now.
