### ISSUE TITLE
Invalid use of incomplete type ‘class wxToolTip’

### ISSUE THREAD

**Issue by clickworkorange** [wxWidgets/wxWidgets#24788]
### Build System Used
I build wxWidgets and/or my application using:

- [x] CMake
- [ ] configure
- [ ] mingw32-make with makefile.gcc
- [ ] MSBuild (Microsoft Visual Studio solution file)
- [ ] nmake with makefile.vc
- [ ] Xcode

### CMake configuration output
```
-- Which libraries should wxWidgets use?
    wxUSE_STL:        OFF      (use C++ STL classes)
    wxUSE_REGEX:      sys      (enable support for wxRegEx class)
    wxUSE_ZLIB:       sys      (use zlib for LZW compression)
    wxUSE_EXPAT:      sys      (use expat for XML parsing)
    wxUSE_LIBJPEG:    sys      (use libjpeg (JPEG file format))
    wxUSE_LIBPNG:     sys      (use libpng (PNG image format))
    wxUSE_LIBTIFF:    sys      (use libtiff (TIFF file format))
    wxUSE_NANOSVG:    builtin  (use NanoSVG for rasterizing SVG)
    wxUSE_LIBLZMA:    OFF      (use liblzma for LZMA compression)
    wxUSE_LIBSDL:     ON       (use SDL for audio on Unix)
    wxUSE_LIBMSPACK:  OFF      (use libmspack (CHM help files loading))

-- Configured wxWidgets 3.2.5 for Linux-6.6.31+rpt-rpi-v8
    Min OS Version required at runtime:                Linux aarch64
    Which GUI toolkit should wxWidgets use?            motif  
    Should wxWidgets be compiled into single library?  OFF
    Should wxWidgets be linked as a shared library?    ON
    Should wxWidgets support Unicode?                  ON
    What wxWidgets compatibility level should be used? 3.0
-- Configuring done
-- Generating done
-- Build files have been written to: /home/me/Sources/wxWidgets-3.2.5/build
```
### Description
Trying to build wxWidgets 3.2.5 "release" under Arm64 PiOS Bookworm w. kernel 6.6.31 using the "motif" X11 GUI toolkit. Build halts on `combocmn.cpp.o` with 

```
/home/me/Sources/wxWidgets-3.2.5/src/common/combocmn.cpp: In member function ‘virtual void wxComboCtrlBase::DoSetToolTip(wxToolTip*)’:
/home/me/Sources/wxWidgets-3.2.5/src/common/combocmn.cpp:1366:38: error: invalid use of incomplete type ‘class wxToolTip’
 1366 |         const wxString &tip = tooltip->GetTip();
      |                                      ^~
In file included from /home/me/Sources/wxWidgets-3.2.5/include/wx/wx.h:38,
                 from /home/me/Sources/wxWidgets-3.2.5/include/wx/wxprec.h:42,
                 from /home/me/Sources/wxWidgets-3.2.5/build/libs/core/CMakeFiles/wxcore.dir/cmake_pch.hxx:5,
                 from <command-line>:
/home/me/Sources/wxWidgets-3.2.5/include/wx/window.h:63:28: note: forward declaration of ‘class wxToolTip’
   63 | class WXDLLIMPEXP_FWD_CORE wxToolTip;
      |                            ^~~~~~~~~
make[2]: *** [libs/core/CMakeFiles/wxcore.dir/build.make:413: libs/core/CMakeFiles/wxcore.dir/__/__/__/__/src/common/combocmn.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:506: libs/core/CMakeFiles/wxcore.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

### Platform and version information

- wxWidgets version you are building: 3.2.5
- wxWidgets port you are building: wxX11?
- OS and its version: Arm64 PiOS Bookworm
- Compiler being used: gcc (Debian 12.2.0-14) 12.2.0
- Non-default compiler options, if any: none

**Comment by vadz** [comment]
Are you sure you want to use wxMotif? This port, as you've discovered, is not really maintained and, honestly, I don't know who would be interested in maintaining it and why, so it was already removed entirely from wx master.

If you really want to build it in 3.2, you need to set `wxUSE_TOOLTIPS` to 0 in the generated `setup.h` because this class is not implemented in wxMotif. Configure correctly disables it, I think, but CMake apparently does not, so if you don't want to much with the build system, you could just use configure instead. Otherwise patching this in `build/cmake/options.cmake` shouldn't be difficult...

**Comment by clickworkorange** [comment]
I understand - I picked "Motif" because I'm experimenting with building a super minimal environment to run a single desktop application in "kiosk" mode. I just want the lightest possible desktop environment. Maybe "X11" is the way to go if I want something lighter than GTK2/3 or Qt?

**Comment by lanurmi** [comment]
> Thank you, I understand - I picked "Motif" because I'm experimenting with building a super minimal environment to run a single desktop application in "kiosk" mode.

You should be aware that the Motif port is not really usable _at all_. Not even the 'minimal' sample works 100% flawlessly with Motif. Probably most of the samples will simply crash if you try using them.

**Comment by clickworkorange** [comment]
Thank you, I understand.

**Comment by oneeyeman1** [comment]
@clickworkorange ,
You should also be aware that using X11/universal part may also not work reliably. Not too much effort goes to keep it up to date. And if you choose it - fixing it will be your task.

**Comment by vadz** [comment]
> The application builds using wxWidgets-GTK3 but crashes with `gtk_box_gadget_distribute: assertion 'size>=0' failed in GtkScrollbar`.

In spite of being "FATAL" GTK error this is actually harmless and doesn't explain the crash. You need to run your application under gdb to find out why does it really crash. If you think it's due to a bug in wxGTK itself, as opposed to an application bug, please open a new issue explaining the problem (and ideally providing the simplest possible way to reproduce it).

> I am unable to build it against wxWidgets-GTK2 as compilation fails with `no such file gdk/gdk.h` despite this being present in /usr/lib.

Please check that `gtk+-2.0.pc` exists and is found by `pkg-config`, building using GTK 2 is still supported and should work.

> Building against wxWidgets-X11 fails because the application in question doesn't configure OpenGL correctly for X11 windows

Sorry, I am not sure what does this mean, but building using wxX11 is also supported. But this port is of alpha quality, so unless you're interested in working on improving it (which would, of course, be very welcome) you should rather check what the real problem is with wxGTK3.

Good luck!

**Comment by clickworkorange** [comment]
Thank you! You're quite right; I misinterpreted the error with GTK3; apparently GTK3 has a habit of spitting out these "CRITICAL" and "FATAL" messages all the time and despite the menacing appearance they don't really mean anything. Just part of running a modern desktop toolkit, I guess :) The segfault is in [libdnet](https://github.com/ofalk/libdnet/) and has nothing to do with either wxWidgets or GTK3 - closing!
