### ISSUE TITLE
[wxMSW] Problems with displaying wxDataViewCtrl when showing a modal dialog

### ISSUE THREAD

**Issue by vasiliykk** [wxWidgets/wxWidgets#24805]
We have a program that uses `wxDataViewCtrl` and can show modal dialogs. Before showing the dialog, we call the `Hide()` method for one of the widgets of the displayed window and `Layout()`. Because of this, as I believe, the table size is recalculated, it does not have time to complete and the table becomes gray. Only the table. In addition, the table remains gray after the dialog is closed until the focus is set on it. If you do not call the `Hide()` and `Layout()` methods before showing the dialog, then the table does not change in any way when the dialog is shown.

I found an [issue](https://github.com/wxWidgets/wxWidgets/issues/18011) with a similar problem. I found a similar place in the `wxDataViewCustomRendererBase::renderText` method. The following change fixes my problem:
```
Index: datavcmn.cpp
===================================================================
--- datavcmn.cpp	(revision 277419)
+++ datavcmn.cpp	(working copy)
@@ -1088,8 +1088,13 @@
     int flags = 0;
     if ( state & wxDATAVIEW_CELL_SELECTED )
         flags |= wxCONTROL_SELECTED;
+#if defined(__UNIX__)
     if ( !(GetOwner()->GetOwner()->IsEnabled() && GetEnabled()) )
         flags |= wxCONTROL_DISABLED;
+#else
+    if ( !(IsWindowEnabled(GetOwner()->GetOwner()->GetHWND()) && GetEnabled()) )
+        flags |= wxCONTROL_DISABLED;
+#endif
 
     wxRendererNative::Get().DrawItemText(
         GetOwner()->GetOwner(),
```

To reproduce the error, it is enough to change the file `samples/dataview/dataview.cpp` (the patch is presented below), go to the `MyListModel` tab, click the `Goto 50` button, close the dialog. After closing the dialog, some of the lines will remain gray.
```
Index: dataview.cpp
===================================================================
--- dataview.cpp	(revision 277632)
+++ dataview.cpp	(working copy)
@@ -509,7 +509,7 @@
 
     EVT_BUTTON( ID_PREPEND_LIST, MyFrame::OnPrependList )
     EVT_BUTTON( ID_DELETE_LIST, MyFrame::OnDeleteList )
-    EVT_BUTTON( ID_GOTO, MyFrame::OnGoto)
+    EVT_BUTTON( ID_GOTO, MyFrame::OnAbout)
     EVT_BUTTON( ID_ADD_MANY, MyFrame::OnAddMany)
     EVT_BUTTON( ID_HIDE_ATTRIBUTES, MyFrame::OnHideAttributes)
     EVT_BUTTON( ID_SHOW_ATTRIBUTES, MyFrame::OnShowAttributes)
@@ -1391,6 +1391,8 @@
 
 void MyFrame::OnAbout( wxCommandEvent& WXUNUSED(event) )
 {
+    m_log->Hide();
+    Layout();
     wxAboutDialogInfo info;
     info.SetName(_("DataView sample"));
     info.SetDescription(_("This sample demonstrates wxDataViewCtrl"));
```

**Comment by AliKet** [comment]
The following patch:
```
diff --git a/src/common/utilscmn.cpp b/src/common/utilscmn.cpp
index abbdadd4dc..38013b4a77 100644
--- a/src/common/utilscmn.cpp
+++ b/src/common/utilscmn.cpp
@@ -1536,7 +1536,10 @@ wxWindowDisabler::wxWindowDisabler(wxWindow *winToSkip, wxWindow *winToSkip2)
     if ( winToSkip )
         m_windowsToSkip.push_back(winToSkip);
     if ( winToSkip2 )
+    {
+        winToSkip2->Update();
         m_windowsToSkip.push_back(winToSkip2);
+    }
 
     DoDisable();
 
```
Fixes this and the other issue #24776 for me. but... while I have an explanation as to why the patch fixes the other (i.e. #24776), I have nothing to say about this problem, other than that it is no longer reproducible with the aforementioned patch (at least under Windows 10, because under Linux + Wine the bug is still there!).

**Comment by vadz** [comment]
I guess the problem is due to postponing the repaint until idle time in the (generic version of) wxDVC and by the time the idle handler is invoked, a dialog is already shown and so the window is really disabled.

So I think the originally proposed fix makes sense, i.e. if we agree that the window should only be greyed out if it was explicitly disabled and not disabled due to a dialog being shown, then repainting it should work correctly even if happens while a dialog is shown and the proposed patch should be used, although we probably should add some `wxWindow::AppearsEnabled()` or `IsGreyedOut()` to avoid writing MSW-specific code here.

Updating the window before (implicitly) disabling it in `wxWindowDisabler` also helps in this particular case, but it would still result in wrong appearance if the window gets repainted while the dialog is shown for whatever reason, so this doesn't look like the right fix to me.

Thoughts?

**Comment by vasiliykk** [comment]
I apologize for the long answer. I think it's a good idea to grey out a widget only when it's explicitly disabled. It is definitely wrong to grey out one widget. As for the implementation, I think it's better for you to decide. But the IsGreyedOut() method seems to be a good idea! Thanks for the answer!

**Comment by vadz** [comment]
Actually we can just use `wxWindow::IsThisEnabled()` here, without doing anything MSW-specific. This won't disable the text in the other implementations too, but I think it's actually a good thing, nobody expects all the text to become greyed out.

I'll push the fix soon, please comment/reopen if you still see any problems with it.
