### ISSUE TITLE
Height of `wxEnumProperty` dropdown list is too small at high DPI

### ISSUE THREAD

**Issue by taler21** [wxWidgets/wxWidgets#24850]
The height of the dropdown list of a `wxEnumProperty` is too small at high DPI.

The issue can be reproduced in the propgrid sample with the following changes:

```patch
diff --git "a/samples/propgrid/propgrid.cpp" "b/samples/propgrid/propgrid.cpp"
index 38b5e8e169..ee8850e7b6 100644
--- "a/samples/propgrid/propgrid.cpp"
+++ "b/samples/propgrid/propgrid.cpp"
@@ -1356,6 +1356,12 @@ void FormMain::PopulateWithExamples ()
     wxBitmap bmpVal = wxArtProvider::GetBitmap(wxART_REMOVABLE);
     pg->SetPropertyImage("EnumProperty 5", bmpVal);
 
+    wxArrayString choices;
+    for ( int i = 0; i < 30; ++i )
+        choices.Add( wxString::Format("Item %d", i + 1) );
+    pg->Append( new wxEnumProperty("EnumProperty With Large List",wxPG_LABEL,
+        choices) );
+
     // Password property example.
     pg->Append( new wxStringProperty("Password",wxPG_LABEL, "password") );
     pg->SetPropertyAttribute( "Password", wxPG_STRING_PASSWORD, true );

```

At a DPI scaling of 100%:

![wxEnumProperty-DropDown-dpi-100](https://github.com/user-attachments/assets/47a31a23-9314-4f29-ad42-39af2ceb0f06)

At a DPI scaling of 200%:

![wxEnumProperty-DropDown-dpi-200](https://github.com/user-attachments/assets/02eb5284-6d81-4e4d-8836-c1c644cf907e)

### Platform and version information

- wxWidgets version  you use: 3.2.6
- wxWidgets port  you use: wxMSW
- OS  and its version: Windows 10

**Comment by MaartenBent** [comment]
I think the main problem is the hardcoded 400px height of `DEFAULT_POPUP_HEIGHT` in `wxComboCtrlBase::ShowPopup`:
https://github.com/wxWidgets/wxWidgets/blob/70de12cd320e85e9102f42081c4eb4ce2ccc9c23/src/common/combocmn.cpp#L2163 

But I also noticed some hardcoded sizes in `wxVListBoxComboPopup::GetAdjustedSize`, which would affect the height of empty dropdown lists. Wrapping all with `FromDIP(...)` fixes it. I can create a PR doing this.

The height of the dropdown is in pixels, so it wont show the same amount of visible elements in the list at different DPI. This happens because the height of the list elements are determined by the character height, which does not scale linear with DPI.

**Comment by vadz** [comment]
Thanks for looking at this!

Could we use `GetCharHeight()` times something for the dropdown height instead, as we already do in some other controls or is too early to have valid text metrics here yet?

**Comment by MaartenBent** [comment]
I created https://github.com/wxWidgets/wxWidgets/pull/24898 to fix this.

I tried to use `GetCharHeight()` to get an estimate, but the height depends on more than just the character height and borders.
For example in `wxPropGrid` it is calculated from `wxPGComboBox::OnMeasureItem`.
