### ISSUE TITLE
wx._core.wxAssertionError on Acceleration table use

### ISSUE THREAD

**Issue by AlessandroMattiazzi** [wxWidgets/wxWidgets#24865]
I get this error:

```
wx._core.wxAssertionError: C++ assertion ""Assert failure"" failed at ..\..\src\common\log.cpp(498) in wxLog::DoLogText(): must be overridden if it is called

The above exception was the direct cause of the following exception:

SystemError: <class 'wx._core.UpdateUIEvent'> returned a result with an exception set
```

when executing the command on this accelerator table:

```python
self.SetAcceleratorTable(wx.AcceleratorTable([ (wx.ACCEL_ALT,  wx.WXK_LEFT, ids.ID_BACK.value)]))
```

Note that even if the error is showed, everything in the code is working fine

**Comment by vadz** [comment]
Sorry, I have no idea how to reproduce this and I don't see what does it have to do with the acceleration table — the error message is clearly about `wxLog::DoLogText()` not being overridden in some class deriving from `wxLog`, so you should look at the log target used by your program.

Please reopen if you can provide some simple way to reproduce this, otherwise I don't think we can do anything about this.
