### ISSUE TITLE
Your antipathy for Wayland is keeping Kicad 16 years behind modernity

### ISSUE THREAD

**Issue by raksphoto** [wxWidgets/wxWidgets#24905]

**Comment by raksphoto** [comment]
Nothing to say. You don't care.

**Comment by marekr** [comment]
Eh? wx isn't the problem for KiCad with Wayland.

Wayland is the problem with Wayland.

Wayland has had developers opposing efforts to add functionality to Wayland that would restore behavior that isn't only part of Xorg, but that is also defacto expected for desktop GUI applications on Windows and macOS. 

They have also turned the general process of fixing wayland into bureaucratic hell in the name of standardization. But the problem is that it creates an absolutely enormous burden for those already with minimal time for OSS development to have to spend months debating implementation, getting into philosophical debates endlessly and digging up support.

**Comment by oneeyeman1** [comment]
@marekr ,
Do you have an example?

**Comment by oneeyeman1** [comment]
@marekr ,
You are correct.
I tried and was immediately turned down by saying We will not add this. Sorry.

**Comment by vadz** [comment]
This is ridiculous, there is no antipathy towards Wayland whatsoever. There are a number of known problems with Wayland, however, and any help with fixing them is welcome. However posting inflammatory comments on the issue tracker is not only wrong (at least please use forums/mailing list/whatever for venting and not the tracker) but completely unhelpful. Please don't do this.

**Comment by ratnik2** [comment]
Aww man. After Chromium CEF gets merged somewhat soon (https://www.phoronix.com/news/Chromium-CEF-Wayland-Progress), the only apps I have that will use X are KiCad and MATLAB. I was really hoping in getting rid of the dependency on Xorg and XWayland.
