### ISSUE TITLE
[ListBox] [Sample] wxOWNERDRAW style uses grey background for text

### ISSUE THREAD

**Issue by Vulpine05** [wxWidgets/wxWidgets#24917]
#### Bug description:

When creating a list box with the wxOwnerdraw setting, the background color to any line with text is grey.  When this setting is not used, the default is white.

#### Expected vs observed behaviour:

I would expect the background color for each text entry to be white by default.

Even if nothing can be done, this comment in the sample should technically be revised:
https://github.com/wxWidgets/wxWidgets/blob/c301af42f923a9997e99bf8d3b8f00df667f88f9/samples/ownerdrw/ownerdrw.cpp#L342

#### Stack trace:

N/A

#### Patch or snippet allowing to reproduce the problem:

Refer to current Ownerdraw sample.

#### To Reproduce:

1. Create a new wxListBox and add "wxLB_OWNERDRAW" as a style.
2. Build program, observe background color text is grey.
3. Remove wxLB_OWNERDRAW style, rebuild, and notice background color is white.

### Platform and version information

- wxWidgets version:  3.2.6
- wxWidgets port:  wxMSW
- OS:  Windows 10 home 22H2, build 19045.5073

  + Current theme: Dark mode, but it doesn't have any affect on the sample (nor expected).

**Comment by vadz** [comment]
Should be fixed by #24918 (only [this commit](https://github.com/wxWidgets/wxWidgets/pull/24918/commits/1826e65a7460d717a7f76b13ad55626f4f4838df) is really needed and it can be backported to 3.2).

Funny how it went unnoticed for so many years, when the same problem for `wxCheckListBox` was fixed in 0d09813094 (use correct background colour for items drawing (closes 1192073); use AutoXXX classes instead of manually dealing with GDI objects; fixed visual bug with background of selected items, 2005-05-22) almost 20 years ago... (see #21819).
