### ISSUE TITLE
Make wxMessageBox respect the native windows dark theme.

### ISSUE THREAD

**Issue by EinTim23** [wxWidgets/wxWidgets#24973]
Hello, I enable the dark mode of wxwidgets during the initialization of my application if it's enabled in the windows settings like this:
```cpp
if (wxSystemSettings::GetAppearance().IsSystemDark()) 
            this->SetAppearance(wxAppBase::Appearance::Dark);```

This works fine on the app itself and components like the tray, but wxMessageBox seems to be entirely unaffected and still displays in light mode on windows.

**Comment by PBfordev** [comment]
This is one of documented limitations of Windows dark mode, see https://docs.wxwidgets.org/latest/classwx_app.html#af8c93d7e3345e62a58325f3ab1d158d6

Unfortunately, it is because Windows itself does not do that, see the glowing-white message boxes displayed by e.g. Explorer in dark mode (unless something has changed recently and MS does not use the native dialog anymore).

**Comment by vadz** [comment]
Indeed, and I don't think there is anything we can do about this, unfortunately.
